const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createArtKnowledge}=require('../desktop/art-knowledge.cjs'),{createArtFiles}=require('../desktop/art-files.cjs');
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/aV8AAAAASUVORK5CYII=','base64');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'gc-art-knowledge-')),directory=path.join(root,'library'),artFiles=createArtFiles(path.join(root,'project-data')),api=createArtKnowledge({directory,artFiles,thumbnail:async()=>({width:1,height:1,bytes:PNG})}),source=path.join(root,'reference.png');await fs.writeFile(source,PNG);t.after(async()=>{api.close();assert.equal(path.dirname(root),path.resolve(os.tmpdir()));await fs.rm(root,{recursive:true,force:true});});return {root,directory,artFiles,api,source};}
test('independent SQLite library deduplicates images, saves metadata with revision checks and restores from backup',async t=>{const f=await fixture(t);let list=await f.api.importImages([f.source,f.source]);assert.equal(list.images.length,1);assert.equal((await f.api.importImages([f.source])).images.length,1);const r=list.images[0];list=await f.api.update(r.id,r.revision,{...r,name:'卡通角色',tags:['shape:round','subject:character'],source:'个人练习',creator:'作者',usage:'reference'});assert.equal(list.images[0].revision,2);await assert.rejects(f.api.update(r.id,1,r),/重新读取/);await assert.rejects(f.api.update(r.id,2,{...r,tags:['anything']}),/无效/);const backup=await f.api.backup(f.root);assert.deepEqual((await f.api.choose(backup)).images,list.images);assert.match(await f.api.preview(r.id),/^data:image\/png/);});
test('project snapshots survive library changes and preserve distinct project-owned image storage',async t=>{const f=await fixture(t),r=(await f.api.importImages([f.source])).images[0],a=await f.api.snapshot(r.id,'project:a'),b=await f.api.snapshot(r.id,'project:b');const {validateReferenceBoards}=await import('../shared/art-knowledge.mjs');validateReferenceBoards([{id:'board',name:'整体',categoryId:'',references:[a]}]);assert.notEqual(a.image.storagePath,b.image.storagePath);await f.api.update(r.id,1,{...r,name:'新资料名'});assert.equal(a.metadata.name,'reference.png');assert.equal(a.revision,1);f.api.close();await fs.rename(f.directory,path.join(f.root,'detached-library'));assert.deepEqual(await f.artFiles.readBytes('project:a',a.image.storagePath),PNG);assert.deepEqual(await f.artFiles.readBytes('project:b',b.image.storagePath),PNG);});
test('malformed files, tampered originals and reference traversal cannot become project snapshots',async t=>{const f=await fixture(t),bad=path.join(f.root,'bad.png');await fs.writeFile(bad,'<svg onload=evil>');await assert.rejects(f.api.importImages([bad]),/支持/);const r=(await f.api.importImages([f.source])).images[0];await fs.writeFile(path.join(f.directory,'originals',r.hash+'.png'),'changed');await assert.rejects(f.api.snapshot(r.id,'project:a'),/变化/);const {validateReferenceBoards}=await import('../shared/art-knowledge.mjs');await assert.rejects(f.api.snapshot('../library.db','project:a'),/不存在/);assert.throws(()=>validateReferenceBoards([{id:'b',name:'B',categoryId:'',references:[{image:{storagePath:'../bad'}}]}]));});

test('a failed batch does not leave partially published library entries',async t=>{const f=await fixture(t),bad=path.join(f.root,'bad.png');await fs.writeFile(bad,'invalid');await assert.rejects(f.api.importImages([f.source,bad]));assert.equal((await f.api.list()).images.length,0);assert.equal((await f.api.importImages([f.source])).images.length,1);});
