import test from 'node:test';import assert from 'node:assert/strict';
import {createGameplay,duplicateGameplay,readGameplay,writeGameplay,validateGameplay,gameplayMarkdown} from '../src/gameplay.ts';
import {emptyStage,createStageObject,createTrack,createTimelineEvent,resizeSpace,removeStageObject,spaceOwner,stageColumn,stageIssues,eventLastStart,eventEnd,dueOccurrences,activeOccurrences,timelineStats,timelineBuckets} from '../src/gameplay-stage.ts';
function setup(){const a=createGameplay('草坪布局'),b=createGameplay('刷怪计划'),object=createStageObject('spawn',3,9),track=createTrack();object.name='第三路入口';object.anchor='right';a.space={...a.space,rows:5,columns:9,objects:[object]};track.name='第一波';b.timeline={...b.timeline,spaceOwnerId:a.id,tracks:[track],events:[{...createTimelineEvent(track.id),name:'普通僵尸',start:20,repeat:3,interval:6,quantity:2,objectId:object.id}]};return [a,b];}
test('schema1 and schema2 read without writes and migrate to schema3 on the first edit',()=>{
 for(const schema of [1,2]){const [a]=setup();delete a.space;delete a.timeline;if(schema===1){delete a.dependencies;delete a.conditionRules;delete a.stateFlow;}a.rules='保留旧的游戏规则';const initial=JSON.stringify({schema,designs:[a]});let raw=initial,writes=0;const storage={getItem:()=>raw,setItem:(_,v)=>{raw=v;writes++;}};const loaded=readGameplay(storage,'key');assert.equal(loaded.store.schema,3);assert.equal(raw,initial);assert.equal(writes,0);assert.deepEqual(loaded.store.designs[0].space,emptyStage().space);loaded.store.designs[0].space.description='5×9草坪';writeGameplay(storage,'key',initial,loaded.store);assert.equal(JSON.parse(raw).schema,3);assert.equal(JSON.parse(raw).designs[0].rules,a.rules);assert.equal(JSON.parse(raw).designs[0].id,a.id);}
});
test('schema3 rejects malformed numeric/nested data but keeps dangling references as repairable design drafts',()=>{
 const [a,b]=setup();validateGameplay({schema:3,designs:[a,b]});for(const mutate of [x=>delete x.space,x=>x.space.rows=0,x=>x.space.rows=2.5,x=>x.space.objects[0].color='bad',x=>x.space.objects.push(x.space.objects[0]),x=>x.timeline.duration=NaN,x=>x.timeline.tracks=[{id:'t',name:'',color:'__proto__'}],x=>x.timeline.events=[{...createTimelineEvent('none'),repeat:0}],x=>x.timeline.events=[{...createTimelineEvent('none'),duration:-1}]]){const copy=structuredClone(a);mutate(copy);assert.throws(()=>validateGameplay({schema:3,designs:[copy]}));}
 b.timeline.events[0].objectId='gone';b.timeline.events[0].trackId='gone';validateGameplay({schema:3,designs:[a,b]});assert.match(stageIssues(b,[a,b]).join(','),/空间对象已失效/);assert.match(stageIssues(b,[a,b]).join(','),/轨道已失效/);
});
test('resizing respects occupied footprints and boundary anchors follow the new edge',()=>{
 const [a]=setup();const wall={...createStageObject('obstacle',4,8),name:'墙',width:2,height:2};a.space.objects.push(wall);assert.throws(()=>resizeSpace(a.space,4,9),/墙/);assert.throws(()=>resizeSpace(a.space,5,8),/墙/);const next=resizeSpace(a.space,6,12);assert.equal(stageColumn(next.objects[0],next),13);assert.equal(stageColumn(next.objects[1],next),8);assert.equal(a.space.columns,9);assert.equal(next.objects.length,2);
});
test('deleting an object with local or cross-gameplay time references is blocked including archived plans',()=>{
 const [a,b]=setup();assert.equal(spaceOwner(b,[a,b]),a);b.archived=true;assert.throws(()=>removeStageObject(a,[a,b],a.space.objects[0].id),/刷怪计划/);b.timeline.events[0].objectId='';assert.equal(removeStageObject(a,[a,b],a.space.objects[0].id).objects.length,0);a.timeline.events=[{...createTimelineEvent(''),objectId:a.space.objects[0].id}];assert.throws(()=>removeStageObject(a,[a,b],a.space.objects[0].id),/草坪布局/);
});
test('time math includes exact trigger boundaries and excludes finished durations with fractional intervals',()=>{
 const e={...createTimelineEvent('t'),start:.1,repeat:3,interval:.1,duration:.1,quantity:2};assert.equal(eventLastStart(e),.3);assert.equal(eventEnd(e),.4);assert.equal(dueOccurrences(e,.09),0);assert.equal(dueOccurrences(e,.1),1);assert.equal(dueOccurrences(e,.3),3);assert.equal(activeOccurrences(e,.2),1);assert.equal(activeOccurrences(e,.4),0);const simultaneous={...e,interval:0};assert.equal(dueOccurrences(simultaneous,.1),3);assert.equal(activeOccurrences(simultaneous,.15),3);assert.equal(activeOccurrences({...e,duration:0},.1),0);
});
test('totals and buckets count schedule quantity rather than currently alive entities, and report beyond-duration plans',()=>{
 const [a,b]=setup(),t=b.timeline;assert.deepEqual(timelineStats(t,26),{occurrences:3,quantity:6,due:2,dueQuantity:4,active:0,last:32});assert.equal(timelineBuckets(t,10).reduce((n,b)=>n+b.quantity,0),6);assert.equal(timelineBuckets(t,10)[2].quantity,4);assert.throws(()=>timelineBuckets(t,0),/正数/);assert.throws(()=>timelineBuckets(t,.01),/统计窗口过小/);t.duration=25;assert.match(stageIssues(b,[a,b]).join(','),/超出计划时长/);assert.equal(timelineStats(t,25).dueQuantity,2);
});
test('copy remaps local object/track links while external layout references stay attached to their original owner',()=>{
 const [a,b]=setup();const original=b.timeline.events[0],copyB=duplicateGameplay(b);assert.notEqual(copyB.timeline.events[0].id,original.id);assert.notEqual(copyB.timeline.tracks[0].id,b.timeline.tracks[0].id);assert.equal(copyB.timeline.events[0].trackId,copyB.timeline.tracks[0].id);assert.equal(copyB.timeline.spaceOwnerId,a.id);assert.equal(copyB.timeline.events[0].objectId,a.space.objects[0].id);
 for(const self of ['',a.id]){a.timeline={...b.timeline,spaceOwnerId:self};const copy=duplicateGameplay(a);assert.notEqual(copy.space.objects[0].id,a.space.objects[0].id);assert.equal(copy.timeline.events[0].objectId,copy.space.objects[0].id);assert.equal(copy.timeline.spaceOwnerId,self?copy.id:'');copy.space.objects[0].name='副本修改';assert.equal(a.space.objects[0].name,'第三路入口');}
});
test('AI export contains positions, ranges, exact timing, repeats and linked space names',()=>{
 const [a,b]=setup();a.space.objects[0].rangeShape='line';a.space.objects[0].range=9;a.space.objects[0].direction='left';const md=gameplayMarkdown([a,b],{stories:[],datasets:[]});for(const phrase of ['5 行 × 9 列','第三路入口','右侧边界外','直线 9 格','空间来源：草坪布局','第一波','20 秒开始','共 3 次','每次 2','最后触发 32 秒','计划数量 6','不模拟战斗'])assert.ok(md.includes(phrase),phrase);
});
