import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {parseGodotFile} from '../server/godot-enum-parser.mjs';import {scanEngineDirectory,validateEngineProject} from '../server/engine-adapters.mjs';
import {selectEngine,savedEngineConfig} from '../src/engine.ts';import {sameEngineSource,portableEngineConfig,validateEngineConfig} from '../shared/engine-config.mjs';
import {emptyStore,makeSnapshot,stageSnapshot,decideChanges,syncApprovedChanges,planRelease} from '../src/enum-versions.ts';import {enumId,resolveEnumValue} from '../src/data-model.ts';
const gd=`class_name Modes
# Movement modes
enum Mode {
 IDLE, # standing
 MOVE = 4,
 DASH,
 HEX = 0x10,
 NEG = -2,
 ALIAS = 4,
}
enum { FIRST = 0b10, SECOND }
class Inner:
 enum State { LOW, HIGH }
var example = "enum Fake { NO }"
var multiline = """
enum FakeToo { WRONG }
"""
# enum Comment { NO }
`;
const config={engine:'oasis-lua',projectPath:'E:/Old',enumPath:'Script/Const',dataPath:'Script/Config',outputFormat:'lua',autoSync:false,backupBeforeSync:true};
test('GDScript parser handles named/anonymous/nested enums, comments, literals, aliases and masks strings',()=>{const s=parseGodotFile(gd,'scripts/modes.gd');assert.equal(s.dynamic.length,0);assert.deepEqual(s.groups.map(g=>g.name),['Modes.Mode','Modes.(匿名:FIRST)','Modes.Inner.State']);assert.deepEqual(s.groups[0].members.map(m=>m.value),[0,4,5,16,-2,4]);assert.equal(s.groups[0].comment,'Movement modes');assert.equal(s.groups[0].members[0].comment,'standing');assert.equal(s.groups[0].members[0].line,4);const plain=parseGodotFile('enum A { X }\nenum B { X }','types.gd');assert.notEqual(enumId(plain.groups[0]),enumId(plain.groups[1]));});
test('unsupported expressions and unsafe integers diagnose complete groups without execution or guessed values',()=>{globalThis.godotExecuted=false;for(const expression of ['1 << 2','OTHER','foo()','9007199254740993','1.5','"enum Hidden { OK }"']){const s=parseGodotFile(`enum Broken { A = ${expression}, B }\nenum Good { X }`,'test.gd');assert.equal(s.groups.length,1);assert.equal(s.dynamic.length,1);assert.equal(s.groups[0].name,'test.Good');}assert.equal(parseGodotFile('enum Bad { A, A }','x.gd').dynamic.length,1);assert.equal(parseGodotFile('enum Bad { A','x.gd').dynamic.length,1);assert.equal(parseGodotFile('enum Bad A','x.gd').dynamic.length,1);assert.equal(globalThis.godotExecuted,false);});
test('engine profiles restore independently and portable packages disconnect every engine',()=>{let godot=selectEngine(config,'godot-gdscript');assert.equal(godot.projectPath,'');godot=savedEngineConfig({...godot,projectPath:'E:/Godot',enumPath:'res://scripts',dataPath:'res://data/generated'});assert.equal(godot.enumPath,'scripts');const oasis=selectEngine(godot,'oasis-lua');assert.equal(oasis.projectPath,config.projectPath);assert.equal(selectEngine(oasis,'godot-gdscript').projectPath,'E:/Godot');const portable=portableEngineConfig(godot);assert.equal(portable.projectPath,'');assert.ok(Object.values(portable.profiles).every(p=>p.projectPath===''));assert.throws(()=>validateEngineConfig({...config,engine:'unknown'}));assert.throws(()=>validateEngineConfig({...config,profiles:{'godot-gdscript':config}}));assert.equal(sameEngineSource(config,{...config,engine:undefined}),true);assert.equal(sameEngineSource(config,{...config,engine:'godot-gdscript'}),false);});
test('real engine adapters identify projects, skip caches, normalize res paths and preserve Lua support',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gc-godot-parser-'));try{await fs.writeFile(path.join(dir,'project.godot'),'config_version=5\n[application]\nconfig/name="Test"');await fs.mkdir(path.join(dir,'scripts'));await fs.mkdir(path.join(dir,'.godot'));await fs.writeFile(path.join(dir,'scripts/modes.gd'),gd);await fs.writeFile(path.join(dir,'.godot/ignored.gd'),'enum Bad { X = foo() }');await fs.writeFile(path.join(dir,'Script.lua'),'local Const_Test = {}\nConst_Test.Mode = { A = 1, B = 2 }\nreturn Const_Test');let scan=await scanEngineDirectory(dir,'res://','godot-gdscript');assert.equal(scan.files.length,1);assert.equal(scan.incomplete,false);assert.equal(scan.groups.length,3);assert.equal((await scanEngineDirectory(dir,'.','oasis-lua')).engine,'oasis-lua');assert.equal((await validateEngineProject(dir,'res://scripts','godot-gdscript')).enumPath,'scripts');await assert.rejects(validateEngineProject(dir,'../','godot-gdscript'));await assert.rejects(validateEngineProject(dir,'scripts','unknown'));await fs.writeFile(path.join(dir,'scripts/bad.gd'),'enum Broken { A = foo() }');scan=await scanEngineDirectory(dir,'.','godot-gdscript');assert.equal(scan.incomplete,true);assert.equal(scan.dynamic[0].source,'scripts/bad.gd');await fs.writeFile(path.join(dir,'project.godot'),'config_version=4');await assert.rejects(validateEngineProject(dir,'.','godot-gdscript'),/Godot 4/);await fs.unlink(path.join(dir,'project.godot'));await assert.rejects(validateEngineProject(dir,'.','godot-gdscript'),/project.godot/);}finally{assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('gc-godot-parser-'));await fs.rm(dir,{recursive:true,force:true});}});
test('new engine/source clears approval inheritance; incomplete scans never publish; approved Godot aliases resolve',async()=>{const groups=parseGodotFile(gd,'scripts/modes.gd').groups,scan={engine:'godot-gdscript',projectPath:'E:/Godot',enumPath:'.',files:['scripts/modes.gd'],groups,dynamic:[],orderTables:[],counts:{files:1,groups:3,members:10}};let store=stageSnapshot(emptyStore({datasets:{},columns:{}}),await makeSnapshot(scan,'source'));const ids=planRelease(store);store=decideChanges(store,groups.map(g=>JSON.stringify([enumId(g),'add-group',''])),true,'test');assert.equal(store.reviews[store.candidateId].selected.length,3);const same=stageSnapshot(store,await makeSnapshot(scan,'source'));assert.equal(same.reviews[same.candidateId].selected.length,3);for(const patch of [{projectPath:'E:/Other'},{engine:'oasis-lua'},{enumPath:'scripts'}]){const next=stageSnapshot(store,await makeSnapshot({...scan,...patch},'source'));assert.equal(next.reviews[next.candidateId].selected.length,0);}const broken=stageSnapshot(store,await makeSnapshot({...scan,incomplete:true},'source'));await assert.rejects(syncApprovedChanges(broken),/扫描/);store=await syncApprovedChanges(store);const published=store.snapshots.find(s=>s.id===store.activeId);assert.equal(resolveEnumValue({type:'enum',enumId:enumId(groups[0])},'MOVE',{scan:published.scan,ready:true}),4);});

test('desktop and Vite endpoints dispatch the selected engine and reject invalid roots',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gc-godot-api-'));let desktop,vite;try{await fs.writeFile(path.join(dir,'project.godot'),'config_version=5');await fs.writeFile(path.join(dir,'mode.gd'),'enum Mode { A, B = 5 }');const {createRequire}=await import('node:module'),require=createRequire(import.meta.url);desktop=await require('../desktop/server.cjs').createDesktopServer({root:path.resolve('.')});const {createServer}=await import('vite');vite=await createServer({server:{host:'127.0.0.1',port:0},logLevel:'silent'});await vite.listen();const urls=[desktop.url,'http://127.0.0.1:'+vite.httpServer.address().port];for(const url of urls){const query=new URLSearchParams({engine:'godot-gdscript',projectPath:dir,enumPath:'res://'});let r=await fetch(url+'/api/engine/scan?'+query);assert.equal(r.status,200);const scan=await r.json();assert.equal(scan.engine,'godot-gdscript');assert.equal(scan.groups[0].members[1].value,5);r=await fetch(url+'/api/engine/validate?'+query);assert.equal(r.status,200);query.set('engine','unsupported');assert.equal((await fetch(url+'/api/engine/scan?'+query)).status,400);}}finally{if(vite)await vite.close();if(desktop)await new Promise(resolve=>{desktop.server.close(resolve);desktop.server.closeAllConnections();});assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('gc-godot-api-'));await fs.rm(dir,{recursive:true,force:true});}});

test('actual folder packaging retains Godot snapshots/bindings and unbinds both engine profiles',async()=>{const {createRequire}=await import('node:module'),require=createRequire(import.meta.url),{createWorkspaceStorage}=require('../desktop/test-workspaces.cjs'),{createProjectPackages}=require('../desktop/project-package.cjs');const {addSavedProject}=await import('../src/project-catalog.ts'),{captureProjectPackage,prepareProjectPackageImport}=await import('../src/project-package.ts');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gc-godot-package-'));try{const catalog=addSavedProject({schema:2,mode:'project',activeId:'',projects:[]},'Godot'),project=catalog.projects[0];project.config=savedEngineConfig({...selectEngine(config,'godot-gdscript'),projectPath:'E:/Godot'});const storage=createWorkspaceStorage(path.join(dir,'data'));storage.setItem('gamecreator.projects.v1',JSON.stringify(catalog));const group=parseGodotFile('enum Mode { A, B = 5 }','mode.gd').groups[0],scan={engine:'godot-gdscript',projectPath:'E:/Godot',enumPath:'.',groups:[group],files:['mode.gd'],dynamic:[],orderTables:[],counts:{files:1,groups:1,members:2}},data={datasets:{modes:[{id:'test',mode:'B'}]},columns:{modes:[{key:'id',label:'ID'},{key:'mode',label:'模式',type:'enum',enumId:enumId(group)}]}};let store=stageSnapshot(emptyStore(data),await makeSnapshot(scan,'source'));store=await syncApprovedChanges(decideChanges(store,[JSON.stringify([enumId(group),'add-group',''])],true,'test'));storage.setItem('gamecreator.enum-versions.v1:'+project.id,JSON.stringify(store));const capture=captureProjectPackage(storage,project),api=createProjectPackages({dataDirectory:path.join(dir,'data'),storage}),folder=path.join(dir,'export');await api.exportFolder({projectId:project.id,directory:folder,...capture});const imported=prepareProjectPackageImport(catalog,(await api.readFolder(folder)).document,'副本');assert.equal(imported.project.config.engine,'godot-gdscript');assert.ok(Object.values(imported.project.config.profiles).every(p=>p.projectPath===''));assert.equal(imported.project.config.projectPath,'');const archive=JSON.parse(imported.entries.find(e=>e.key.startsWith('gamecreator.enum-versions.v1:')).value);assert.deepEqual(archive,JSON.parse(JSON.stringify(store)));assert.equal(resolveEnumValue(data.columns.modes[1],'B',{scan:archive.snapshots.find(s=>s.id===archive.activeId).scan,ready:true}),5);assert.equal(storage.getItem('gamecreator.enum-versions.v1:'+project.id),JSON.stringify(store));}finally{assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('gc-godot-package-'));await fs.rm(dir,{recursive:true,force:true});}});

test('identical content from another root requires explicit provenance confirmation and preserves bindings',async()=>{const {confirmEnumSource}=await import('../src/enum-versions.ts');const groups=parseGodotFile('enum Mode { A, B }','mode.gd').groups,scan={engine:'godot-gdscript',projectPath:'E:/First',enumPath:'.',groups,files:['mode.gd'],dynamic:[],orderTables:[],counts:{files:1,groups:1,members:2}};let store=stageSnapshot(emptyStore({datasets:{},columns:{}}),await makeSnapshot(scan,'source'));store=await syncApprovedChanges(decideChanges(store,[JSON.stringify([enumId(groups[0]),'add-group',''])],true,'test'));const old=store.activeId;store=stageSnapshot(store,await makeSnapshot({...scan,projectPath:'E:/Second'},'source'));assert.equal(store.activeId,old);const confirmed=await confirmEnumSource(store,'test');assert.notEqual(confirmed.activeId,old);assert.deepEqual(confirmed.data,store.data);assert.equal(confirmed.snapshots.find(s=>s.id===confirmed.activeId).scan.projectPath,'E:/Second');assert.equal(confirmed.releases.at(-1).accepted.length,0);await assert.rejects(confirmEnumSource(confirmed,'test'));});

test('a stale Lua-only service cannot masquerade as a successful Godot scan',async t=>{const {scanEngineProject}=await import('../src/engine.ts');t.mock.method(globalThis,'fetch',async()=>({ok:true,json:async()=>({groups:[],files:[],orderTables:[],dynamic:[]})}));await assert.rejects(scanEngineProject({...config,engine:'godot-gdscript'}),/扫描服务未支持/);});
