import test from 'node:test';
import assert from 'node:assert/strict';
import {applyReferenceBoard} from '../src/reference-boards.ts';
import {emptyArtAssets,validateArtAssets} from '../src/art-assets.ts';
import {confirmArtStyle,itemStyleMarkdown,artStyleMarkdown} from '../src/art-style.ts';
const make=()=>({...emptyArtAssets(),referenceBoards:[{id:'board',name:'角色视觉参考',categoryId:'',references:[{id:'r',libraryId:'lib',referenceId:'source',revision:1,hash:'a'.repeat(64),at:new Date().toISOString(),metadata:{name:'配色参考',description:'',source:'测试来源',creator:'',work:'',sourceType:'internal',usage:'reference',usageNotes:'',tags:[]},image:{id:'123',name:'reference.png',storagePath:'11111111-1111-4111-8111-111111111111.png',mime:'image/png',size:100},use:'配色',take:'柔和暖色',avoid:'不参考服装',strength:'required',active:true,deliverImage:false}]}]});
test('applying references edits the draft only, is repeatable and removing references preserves published history',()=>{let s=applyReferenceBoard(make(),'board');validateArtAssets(s);assert.equal(s.style.versions.length,0);assert.match(s.style.draft.references[0].take,/柔和暖色/);s.style.draft.direction='手绘';s.style=confirmArtStyle(s.style,'确定方向');const published=structuredClone(s.style.versions);s=applyReferenceBoard(s,'board');assert.equal(s.style.draft.references.length,1);s.referenceBoards[0].references[0].active=false;s=applyReferenceBoard(s,'board');assert.equal(s.style.draft.references.length,0);assert.deepEqual(s.style.versions,published);});
test('category references do not leak globally and changing scope clears the prior generated block',()=>{let s=make();s.referenceBoards[0].categoryId='characters';s=applyReferenceBoard(s,'board');assert.equal(s.style.draft.references.length,0);assert.match(s.style.draft.categories[0].rules,/柔和暖色/);s=applyReferenceBoard(s,'board');assert.equal(s.style.draft.categories[0].rules.split('【参考板 board】').length,2);s.referenceBoards[0].categoryId='';s=applyReferenceBoard(s,'board');assert.equal(s.style.draft.categories[0].rules,'');assert.equal(s.style.draft.references.length,1);});
test('snapshot documents exclude image links until explicitly opted in and reject invalid managed paths',()=>{const s=make();assert.doesNotMatch(artStyleMarkdown(s),/!\[参考图片/);s.referenceBoards[0].references[0].deliverImage=true;assert.match(artStyleMarkdown(s),/!\[参考图片\]\(\.\.\/media\//);s.referenceBoards[0].references[0].image.storagePath='../external.png';assert.throws(()=>validateArtAssets(s),/快照/);});
