import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
import {validateStories,validateStoryExtras,storyExtras,makeStory,copyStory,filterStories,storyBlocks,formatStorySelection,safeStoryLink} from '../src/story-library.ts';
import {preparePrototypeProject,writePrototypeProject} from '../src/prototype-import.ts';
import {captureProjectPackage,validateProjectPackage} from '../src/project-package.ts';
const require=createRequire(import.meta.url),native=require('../shared/story-document.cjs'),{createWorkspaceStorage}=require('../desktop/test-workspaces.cjs'),{createProjectPackages}=require('../desktop/project-package.cjs');
test('legacy stories stay unchanged and optional fields have identical browser/server validation',()=>{const s=makeStory('角色','自定义');delete s.format;delete s.updatedAt;const before=JSON.stringify(s);validateStories([s]);assert.equal(JSON.stringify(s),before);assert.deepEqual(storyExtras(s),{});
 for(const patch of [{archived:'true'},{format:'html'},{references:null},{references:[{kind:'bad',targetId:'x',label:'x'}]},{references:[{kind:'story',targetId:'',label:''}]}]){assert.throws(()=>validateStoryExtras({...s,...patch}));assert.throws(()=>native.storyExtras({...s,...patch}));}
 const enhanced={...s,format:'markdown',archived:true,references:[{kind:'story',targetId:'other',label:'另一故事'}]};assert.deepEqual(storyExtras(enhanced),native.storyExtras(enhanced));assert.deepEqual(native.storyExtras({},enhanced),storyExtras(enhanced));
});
test('categories, archive filters, sorting, copies and templates preserve originals',()=>{const a=makeStory('角色A','角色设定','character'),b={...makeStory('地点B','地点设定'),archived:true},c=makeStory('世界C','世界观');a.content+='隐藏正文关键词';const docs=[a,b,c],before=JSON.stringify(docs);assert.deepEqual(filterStories(docs,'关键词',null,'all','active','title'),[a]);assert.deepEqual(filterStories(docs,'',null,'all','archived','title'),[b]);assert.deepEqual(filterStories(docs,'','角色设定','all','all','title'),[a]);const copy=copyStory(b);assert.notEqual(copy.id,b.id);assert.equal(copy.archived,false);assert.equal(copy.status,'草稿');assert.equal(JSON.stringify(docs),before);assert.ok(a.content.includes('## 目标与动机'));});
test('markdown headings ignore fenced code; selection formatting never touches surrounding prose',()=>{const text='# 开始\n\n正文\n```\n## 不是标题\n```\n## 后续\n- 一项\n> 说明';assert.deepEqual(storyBlocks(text).filter(b=>b.kind==='heading').map(b=>[b.text,b.line]),[['开始',0],['后续',6]]);const v=formatStorySelection('前 重点 后',2,4,'bold');assert.equal(v.content,'前 **重点** 后');assert.equal(v.replacement,'**重点**');assert.equal(safeStoryLink('javascript:alert(1)'),null);assert.equal(safeStoryLink('data:text/html,x'),null);assert.equal(safeStoryLink('https://example.com'),'https://example.com/');});
for(const slug of ['hollow-knight','plants-vs-zombies','stardew-valley','disco-elysium','vampire-survivors'])test(slug+' keeps legacy documents and new metadata through actual folder round trip',async()=>{
 const example=JSON.parse(await fs.readFile(new URL('../examples/prototypes/'+slug+'.json',import.meta.url))),legacy=JSON.stringify(example.stories),dir=await fs.mkdtemp(path.join(os.tmpdir(),'gc-story-library-model-'));try{
 const dataDirectory=path.join(dir,'data'),storage=createWorkspaceStorage(dataDirectory),p=preparePrototypeProject({schema:2,activeId:'',mode:'project',projects:[]},example,'故事验收');writePrototypeProject(storage,p);storage.setItem('gamecreator.projects.v1',JSON.stringify(p.catalog));assert.equal(JSON.stringify(JSON.parse(storage.getItem('gamecreator.workspace.v1:'+p.project.id+':stories'))),legacy);
 const key='gamecreator.workspace.v1:'+p.project.id+':stories',docs=JSON.parse(storage.getItem(key));docs[0]={...docs[0],format:'markdown',archived:true,references:[{kind:'gameplay',targetId:example.gameplay.designs[0].id,label:example.gameplay.designs[0].title}]};storage.setItem(key,JSON.stringify(docs));const captured=captureProjectPackage(storage,p.project),api=createProjectPackages({dataDirectory,storage});await api.exportFolder({projectId:p.project.id,directory:path.join(dir,'folder'),...captured});const read=validateProjectPackage((await api.readFolder(path.join(dir,'folder'))).document);assert.deepEqual(read.archives.stories,docs);
 }finally{assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('gc-story-library-model-'));await fs.rm(dir,{recursive:true,force:true});}});
