const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createCollaborationServer}=require('../server/collaboration.cjs');
const fields=(id='a')=>({id,title:'Story '+id,category:'Custom',status:'草稿',summary:'summary',content:'# Heading\n\nText',tags:[],outlines:['legacy outline'],relations:{characters:['legacy character'],locations:[],systems:[]},format:'markdown',archived:false,references:[]});
async function fixture(run){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gc-story-api-'));let service=await createCollaborationServer({directory:dir,port:0});const request=async(route,token,method='GET',payload)=>{const r=await fetch(service.url+'/api/team'+route,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:payload===undefined?undefined:JSON.stringify(payload)});return {status:r.status,data:await r.json()};};const login=async user=>(await request('/login','','POST',{username:user,password:user+'123'})).data.token;try{await run({request,login,restart:async()=>{await service.close();service=await createCollaborationServer({directory:dir,port:0});}});}finally{await service.close();assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('gc-story-api-'));fs.rmSync(dir,{recursive:true,force:true});}}
test('enhanced story fields survive old clients, conflicts, history and restart; viewers cannot edit',()=>fixture(async({request,login,restart})=>{let admin=await login('admin');const viewer=await login('viewer'),base='/projects/team-demo/stories';let r=await request(base,admin,'POST',fields());assert.equal(r.status,201);let story=r.data.story;const route=base+'/'+story.id;const updated=await request(route,admin,'PUT',{...story,archived:true,references:[{kind:'story',targetId:'world',label:'World'}]});assert.equal(updated.status,200);story=updated.data.story;const old={...story,content:'Old client editing body'};delete old.format;delete old.archived;delete old.references;r=await request(route,admin,'PUT',old);assert.equal(r.status,200);assert.equal(r.data.story.archived,true);assert.equal(r.data.story.format,'markdown');assert.deepEqual(r.data.story.references,story.references);story=r.data.story;
 assert.equal((await request(route,viewer,'PUT',{...story,archived:false})).status,403);r=await request(route,admin,'PUT',{...story,revision:1});assert.equal(r.status,409);assert.equal(r.data.current.format,'markdown');for(const patch of [{format:'html'},{archived:'true'},{references:[{kind:'unknown',targetId:'x',label:'x'}]}])assert.equal((await request(route,admin,'PUT',{...story,...patch})).status,400);
 const history=(await request(route+'/history',admin)).data.history;assert.equal(history.length,3);assert.equal(history[0].format,'markdown');assert.deepEqual(history[0].outlines,['legacy outline']);await restart();admin=await login('admin');assert.deepEqual((await request(route,admin)).data.story,story);
}));
test('import remaps actual story references, retains unsupported targets as source-only and does not overwrite edits on retry',()=>fixture(async({request,login})=>{const token=await login('admin'),base='/projects/team-demo/stories',origin={sourceInstanceId:'story-library-source',sourceProjectId:'source-project'};const a={...fields('a'),references:[{kind:'story',targetId:'b',label:'B'},{kind:'gameplay',targetId:'combat',label:'Combat'}]},b=fields('b');let result=await request(base+'/import',token,'POST',{...origin,stories:[a,b]});assert.equal(result.status,200);const imported=result.data.imported,aa=imported.find(s=>s.title===a.title),bb=imported.find(s=>s.title===b.title);assert.notEqual(aa.id,a.id);assert.equal(aa.references[0].targetId,bb.id);assert.equal(aa.references[0].sourceOnly,false);assert.equal(aa.references[1].sourceOnly,true);assert.deepEqual((await request(base+'/'+aa.id+'/history',token)).data.history[0].references,aa.references);
 const edit=(await request(base+'/'+aa.id,token,'PUT',{...aa,content:'Team edit'})).data.story;result=await request(base+'/import',token,'POST',{...origin,stories:[a,b]});assert.equal(result.data.skipped,2);assert.deepEqual((await request(base+'/'+aa.id,token)).data.story,edit);
 const publication=await request('/publications',token,'POST',{...origin,sourceProjectId:'published',name:'Story project',members:[{userId:'admin',role:'admin'}],stories:[a,b]});assert.equal(publication.status,201);const stories=(await request('/projects/'+publication.data.project.id+'/stories',token)).data.stories;assert.equal(stories.find(s=>s.title===a.title).references[0].targetId,stories.find(s=>s.title===b.title).id);
}));
