import type {ProjectData} from '../src/data-model';
import type {EnumScan} from '../src/engine';
export type Json = null | boolean | number | string | Json[] | {[key:string]:Json};
export type JsonFormat={shape:'object'|'rows'|'array';template:Json;mapping:Record<string,string>};
export type Canonical={shape:'object'|'rows'|'array';value?:Record<string,Json>;metadata?:Record<string,Json>;order?:string[];rows?:Record<string,Record<string,Json>>};
export type Decision={choice:'local'|'remote'|'custom'|'';value?:string;allowDelete?:boolean};
export type DataDifference={id:string;path:string[];local?:Json;remote?:Json;baseLocal?:Json;baseRemote?:Json;conflict:boolean;choice:Decision['choice'];deletion:boolean};
export type DataSyncHistory={id:string;at:string;direction:'import'|'export'|'undo';tables:string[];directory:string;scope:string};
export type DataSyncState={schema:1;bindings:Record<string,{scope:string;mapping:Record<string,string>;baseline:{local:Canonical;remote?:Canonical}}>;history:DataSyncHistory[]};
export function record(v:unknown):v is Record<string,unknown>;
export function safeKey(v:unknown):v is string;
export function jsonType(v:Json):string;
export function stable(v:unknown):string;
export function validateJson(v:unknown):void;
export function parseJson(v:string):Json;
export function dataDirectory(v:string):string;
export function tableName(v:string):string;
export function shapeOf(v:Json):JsonFormat['shape'];
export function validateMapping(v:Record<string,string>):Record<string,string>;
export function canonical(v:Json|undefined,mapping?:Record<string,string>):Canonical|undefined;
export function fromCanonical(v:Canonical,mapping?:Record<string,string>):Json;
export function toData(data:ProjectData,table:string,json:Json,mapping?:Record<string,string>,scan?:EnumScan|null):ProjectData;
export function toJson(data:ProjectData,table:string,mapping?:Record<string,string>,scan?:EnumScan|null,template?:Json):Json|undefined;
export function diffJson(local:Canonical|undefined,remote:Canonical|undefined,baseline:unknown,direction:string):DataDifference[];
export function resolveDiff(local:Canonical|undefined,rows:DataDifference[],decisions?:Record<string,Decision>):Canonical|undefined;
export function validateDataSync(store:unknown):void;
