export const projectContentModules={project:'项目概览','project-schedule':'项目排期',gameplay:'玩法设计','gameplay-core':'玩法核心','prototype-design':'原型设计','task-flows':'任务与流程','numerical-analysis':'数值分析','functional-systems':'功能系统','development-tools':'开发工具','art-assets':'素材文档',stories:'故事文档','story-orchestration':'故事编排','map-design':'地图设计','program-framework':'程序框架',definitions:'数据表定义','enum-versions':'开发配置数据'};
const record=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
export function contentJson(v){return v===undefined?'（字段不存在）':JSON.stringify(v,null,2);}
const stable=v=>Array.isArray(v)?'['+v.map(stable).join(',')+']':record(v)?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}':JSON.stringify(v);
const protectedKeys=new Set(['__proto__','constructor','prototype','id','schema','personnel','authoringHistory','feedbackHistory','proposals','assignment','positionIds','specChanges','snapshots','releases','reviews','activeId','candidateId','dataReleases','dataSync','versions','styleReview','adoptedVersionId','images','files','storagePath','revision']);
const split=path=>{if(typeof path!=='string'||path.length>1500||!path.startsWith('/'))throw new Error('项目修改字段路径无效');const parts=path.slice(1).split('/').map(s=>{if(/~(?![01])/u.test(s))throw new Error('字段路径转义无效');return s.replace(/~1/g,'/').replace(/~0/g,'~');});if(parts.some(p=>!p||['__proto__','constructor','prototype'].includes(p)))throw new Error('字段路径包含保留名称');return parts;};
export function contentLocation(root,path){let parent=root;const parts=split(path);for(let i=0;i<parts.length;i++){const part=parts[i];let key=part;if(Array.isArray(parent)){if(!part.startsWith('@'))throw new Error('列表记录使用 @ID 或 @key 定位，不能使用顺序下标');const matches=parent.flatMap((v,n)=>record(v)&&String(v.id??v.key)===part.slice(1)?[n]:[]);if(matches.length!==1)throw new Error('目标记录不存在或标识重复：'+part);key=matches[0];}else if(!record(parent)||!Object.hasOwn(parent,part))throw new Error('项目修改只支持已有字段：'+path);if(i===parts.length-1)return{parent,key,value:parent[key]};parent=parent[key];}}
function protectedView(v){if(Array.isArray(v))return v.every(x=>!record(x)&&!Array.isArray(x))?null:v.map(protectedView);if(!record(v))return null;return Object.fromEntries(Object.entries(v).flatMap(([k,x])=>protectedKeys.has(k)?[[k,x]]:record(x)||Array.isArray(x)?[[k,protectedView(x)]]:[]));}
export function assertContentChange(module,before,after,paths){
 if(!Object.hasOwn(projectContentModules,module))throw new Error('项目修改模块不受支持');
 if(stable(protectedView(before))!==stable(protectedView(after)))throw new Error('项目内容修改不能变更身份、人员授权、文件或历史记录，也不能新增或删除条目');
 for(const path of paths){const parts=split(path);if(parts.some(p=>protectedKeys.has(p)))throw new Error('此字段由独立的管理或历史流程维护');
  if(module==='enum-versions'&&parts[0]!=='data')throw new Error('只允许修改开发配置数据，不能改写枚举或稳定发布历史');
  if(module==='project-schedule'&&(!['tasks','milestones'].includes(parts[0])||parts.length<3||!['title','description','acceptance','owner','start','end','due','priority','milestoneId','dependencyIds'].includes(parts[2])))throw new Error('排期修改仅支持需求、验收标准和计划字段，人员授权与完成状态单独管理');
 }
 // Completed work is accepted via review, not by replacing an enclosing content object.
 for(const [list,fields] of module==='development-tools'?[['tools',['status','usage','delivery','scheduleAcceptance']]]:module==='functional-systems'?[['capabilities',['status']]]:module==='art-assets'?[['requirements',['status','productionStatus','scheduleProgress','delivery']],['assets',['productionStatus','scheduleProgress','delivery']]]:[]){const values=v=>(v[list]||[]).map(x=>Object.fromEntries(['id',...fields].map(k=>[k,x[k]])));if(stable(values(before))!==stable(values(after)))throw new Error('制作状态与交付结果请通过进度或验收反馈更新');}
}
export function projectChangeRows(feedback,base,current){return Object.entries(feedback.changes).map(([field,encoded])=>{const b=contentLocation(base,field).value,c=contentLocation(current,field).value,incoming=JSON.parse(encoded);return{field,label:projectContentModules[feedback.target.id]+' · '+field,base:contentJson(b),current:contentJson(c),incoming:contentJson(incoming),state:stable(c)===stable(incoming)?'unchanged':stable(c)===stable(b)?'updated':'conflict'};});}
export function applyProjectRows(module,current,rows,decisions={}){const next=structuredClone(current);for(const row of rows){if(row.state==='conflict'&&!['keep','feedback'].includes(decisions[row.field]))throw new Error('请逐项处理项目内容冲突');if(row.state==='unchanged'||decisions[row.field]==='keep')continue;const where=contentLocation(next,row.field);where.parent[where.key]=JSON.parse(row.incoming);}assertContentChange(module,current,next,rows.map(r=>r.field));return next;}
