import {beforeLogoutEvent} from './auth';
import {useEffect,useId,useState} from 'react';
import {Users,Plus,KeyRound,Route,CheckCircle2,Copy,Download,X,Minus} from 'lucide-react';
import {aiPermissionLabels,defaultWorkTeam,positionsOf,positionTasks,taskPositionIds,workAssignees,credentialTasks,type AiPosition,type AiPermission} from '../shared/ai-personnel.mjs';
import {ScheduleRecovery} from './ProjectSchedule';
import type {useProjectSchedule} from './useProjectSchedule';
import {scheduleProgressLayout} from './schedule-progress';
import {useProgressNavigation} from './useProgressNavigation';
import type {ProjectScheduleStore,ProductionTask} from './project-schedule';
import './ai-personnel.css';
type Controller=ReturnType<typeof useProjectSchedule>;
type History=import('../shared/engine-feedback.mjs').FeedbackReceipt[];
const permissions=Object.keys(aiPermissionLabels) as AiPermission[];

export function AiPersonnel({controller:c,projectId,onOpenTask,toolHistory=[],testMode=false}:{controller:Controller;projectId:string;onOpenTask:(id:string)=>void;toolHistory?:History;testMode?:boolean}){
 const [tab,setTab]=useState('positions'),[editing,setEditing]=useState<AiPosition>(),[query,setQuery]=useState(''),[taskId,setTaskId]=useState('');
 const positions=positionsOf(c.store),team=c.store.personnel,blocked=c.blocked||c.pending,task=c.store.tasks.find(t=>t.id===taskId);
 const filtered=positions.filter(p=>(p.name+p.duties).toLowerCase().includes(query.toLowerCase()));
 const savePosition=(position:AiPosition,taskIds:string[])=>c.update(s=>({...s,personnel:{...(s.personnel||defaultWorkTeam()),positions:positionsOf(s).some(p=>p.id===position.id)?positionsOf(s).map(p=>p.id===position.id?position:p):[...positionsOf(s),position]},tasks:s.tasks.map(t=>{const before=taskPositionIds(s,t),selected=taskIds.includes(t.id);return before.includes(position.id)===selected?t:{...t,positionIds:selected?[...before,position.id]:before.filter(id=>id!==position.id)};})}));
 return <section className="ai-personnel" aria-label="AI 人员分配">
  <div className="ai-heading"><div><span className="gp-kicker">ROLES & WORK</span><h2>先明确岗位工作，再分配给 AI。</h2><p>程序、美术、策划等岗位各有工作清单。签发协作令牌时，再命名执行者并多选工作。</p></div><button className="primary" disabled={blocked} onClick={()=>setEditing({id:crypto.randomUUID(),name:'',duties:'',active:true,taskKinds:[]})}><Plus size={16}/>添加岗位</button></div>
  <ScheduleRecovery controller={c}/>
  <div className="ai-stats"><div><Users/><strong>{positions.filter(p=>p.active).length}</strong><span>工作岗位</span></div><div><Route/><strong>{c.store.tasks.filter(t=>workAssignees(c.store,t.id,projectId).length).length}/{c.store.tasks.length}</strong><span>任务已分配给 AI</span></div><div><CheckCircle2/><strong>{c.store.tasks.filter(t=>t.status==='待验收').length}</strong><span>待验收任务</span></div><div><KeyRound/><strong>{team?.credentials.filter(k=>k.projectId===projectId&&!k.revokedAt&&Date.parse(k.expiresAt)>Date.now()&&team.members.some(m=>m.id===k.memberId&&m.active)).length||0}</strong><span>有效协作令牌</span></div></div>
  <div className="ar-module-tabs" role="tablist" aria-label="人员分配视图">{[['positions','岗位总览'],['work','岗位任务'],['credentials','协作令牌']].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='positions'&&<><div className="ai-toolbar"><input type="search" aria-label="搜索岗位" placeholder="搜索岗位或职责" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="ai-member-grid">{filtered.map(p=>{const tasks=positionTasks(c.store,p.id),done=tasks.filter(t=>t.status==='已完成').length;return <button className={'ai-member-card'+(!p.active?' inactive':'')} key={p.id} aria-label={'编辑岗位：'+p.name} onClick={()=>setEditing(p)}><div className="ai-member-top"><span className="ai-avatar">{p.name.slice(0,1)}</span><span>{p.active?'启用':'已停用'}</span></div><h3>{p.name}</h3><p>{p.duties||'待补充职责'}</p><div className="ai-work-preview">{tasks.slice(0,3).map(t=><span key={t.id}>{t.title}</span>)}{tasks.length>3&&<small>还有 {tasks.length-3} 项工作</small>}{!tasks.length&&<span>点击岗位添加工作内容</span>}</div><progress max={Math.max(1,tasks.length)} value={done}/><small>{done}/{tasks.length} 已完成 · {tasks.filter(t=>t.status==='进行中').length} 进行中 · {tasks.filter(t=>t.status==='待验收').length} 待验收</small></button>;})}</div>{!filtered.length&&<p className="ai-empty">没有匹配岗位。</p>}</>}
  {tab==='work'&&<><p className="gp-muted">按岗位查看工作线路。点击任务查看内容与执行者；同一任务可属于多个岗位，汇总视图只显示一次。</p><AiWorkBoard store={c.store} projectId={projectId} onOpen={setTaskId}/></>}
  {tab==='credentials'&&<AiCredentials controller={c} projectId={projectId} toolHistory={toolHistory} testMode={testMode}/>}
  {editing&&<AiDialog title={editing.name?'编辑岗位：'+editing.name:'新建岗位'} onClose={()=>setEditing(undefined)}><ScheduleRecovery controller={c}/><PositionEditor key={editing.id} position={editing} store={c.store} disabled={blocked} onSave={(p,ids)=>{if(savePosition(p,ids))setEditing(undefined);}}/></AiDialog>}
  {task&&<AiDialog title="岗位工作详情" onClose={()=>setTaskId('')}><h3>{task.title}</h3><p>{task.description||'尚未填写工作说明'}</p><p>岗位：{taskPositionIds(c.store,task).map(id=>positions.find(p=>p.id===id)?.name||'失效岗位').join('、')||'未归类'}</p><p>验收要求：{task.acceptance||'待填写'}</p><h4>当前执行者</h4>{workAssignees(c.store,task.id,projectId).map(k=><p key={k.id}>{team?.members.find(m=>m.id===k.memberId)?.name} · {k.permissions.map(p=>aiPermissionLabels[p]).join('、')}</p>)}{!workAssignees(c.store,task.id,projectId).length&&<p>尚未分配。到协作令牌中选择这项工作。</p>}<button className="gp-secondary" onClick={()=>{setTaskId('');onOpenTask(task.id);}}>查看排期与验收详情</button></AiDialog>}
 </section>;
}
function AiDialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <dialog className="gp-dialog ai-dialog" aria-label={title} ref={node=>{if(node&&!node.open)node.showModal();}} onCancel={e=>{e.preventDefault();onClose();}}><div className="gp-card-heading"><h3>{title}</h3><button className="gp-icon" aria-label={'关闭'+title} onClick={onClose}><X/></button></div>{children}</dialog>;}

function PositionEditor({position,store,disabled,onSave}:{position:AiPosition;store:ProjectScheduleStore;disabled:boolean;onSave:(p:AiPosition,ids:string[])=>void}){
 const [draft,setDraft]=useState(position),[ids,setIds]=useState(positionTasks(store,position.id).map(t=>t.id)),[query,setQuery]=useState('');
 const invalid=!draft.name.trim()||positionsOf(store).some(p=>p.id!==position.id&&p.name.trim().toLowerCase()===draft.name.trim().toLowerCase());
 const tasks=store.tasks.filter(t=>(t.title+t.description).toLowerCase().includes(query.toLowerCase()));
 return <form onSubmit={e=>{e.preventDefault();if(!invalid)onSave({...draft,name:draft.name.trim()},ids);}}><fieldset className="ar-fields" disabled={disabled}>
  <label className="gp-field">岗位名称<input aria-label="岗位名称" maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="例如：程序、美术、关卡设计"/></label>
  <label className="gp-field">岗位职责<textarea aria-label="岗位职责" rows={4} maxLength={10000} value={draft.duties} onChange={e=>setDraft({...draft,duties:e.target.value})}/></label>
  <label><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>启用岗位</label>
  <p className="gp-muted">{draft.taskKinds.length?'默认归入'+draft.taskKinds.join('、')+'方向的排期任务，可在下面调整。':'选择该岗位负责的排期任务。'}调整岗位不更改任务完成状态，也不自动给令牌增加任务。</p>
  <h4>工作内容 · 已选 {ids.length} 项</h4><input type="search" aria-label="搜索岗位工作" placeholder="搜索任务" value={query} onChange={e=>setQuery(e.target.value)}/>
  <div className="ai-work-selection">{tasks.map(t=><label key={t.id}><input type="checkbox" aria-label={'岗位工作：'+t.title} checked={ids.includes(t.id)} onChange={e=>setIds(v=>e.target.checked?[...v,t.id]:v.filter(id=>id!==t.id))}/><span><strong>{t.title}</strong><small>{t.kind} · {t.status}</small></span></label>)}</div>
  {!tasks.length&&<p>暂无匹配任务，可在项目排期中新增。</p>}{invalid&&<p role="alert">请输入唯一的岗位名称。</p>}<button className="primary" disabled={invalid}>保存岗位</button>
 </fieldset></form>;
}

function AiWorkBoard({store,projectId,onOpen}:{store:ProjectScheduleStore;projectId:string;onOpen:(id:string)=>void}){
 const [positionId,setPositionId]=useState('all'),[status,setStatus]=useState('all'),[milestone,setMilestone]=useState('all'),positions=positionsOf(store),marker=useId().replace(/:/g,''),{scroll,zoom,setZoom,panning}=useProgressNavigation(!!store.tasks.length);
 const base=scheduleProgressLayout(store.tasks),ranks=new Map(base.nodes.map(n=>[n.task.id,n.column]));
 const visible=store.tasks.filter(t=>(positionId==='all'||(positionId==='none'?!taskPositionIds(store,t).length:taskPositionIds(store,t).includes(positionId)))&&(status==='all'||t.status===status)&&(milestone==='all'||t.milestoneId===milestone));
 const laneFor=(t:ProductionTask)=>positionId!=='all'&&positionId!=='none'?positionId:taskPositionIds(store,t)[0]||'';
 const laneIds=[...new Set([...positions.map(p=>p.id),'',...visible.map(laneFor)])];let y=48;const nodes:{task:ProductionTask;x:number;y:number}[]=[],lanes:{id:string;name:string;top:number;height:number}[]=[];
 for(const id of laneIds){const tasks=visible.filter(t=>laneFor(t)===id);if(!tasks.length)continue;const counts=new Map<number,number>(),top=y;for(const task of tasks){const column=ranks.get(task.id)||0,row=counts.get(column)||0;nodes.push({task,x:200+column*290,y:top+20+row*154});counts.set(column,row+1);}const height=Math.max(1,...counts.values())*154+35;lanes.push({id,name:positions.find(p=>p.id===id)?.name||(id?'失效岗位':'未归类'),top,height});y+=height;}
 const width=Math.max(800,base.columns*290+220),byId=new Map(nodes.map(n=>[n.task.id,n]));
 return <><div className="ai-toolbar"><select aria-label="岗位任务筛选" value={positionId} onChange={e=>setPositionId(e.target.value)}><option value="all">全部岗位</option><option value="none">未归类</option>{positions.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><select aria-label="分配任务状态筛选" value={status} onChange={e=>setStatus(e.target.value)}>{['all','待开始','进行中','待验收','已完成','受阻'].map(s=><option value={s} key={s}>{s==='all'?'全部状态':s}</option>)}</select><select aria-label="分配里程碑筛选" value={milestone} onChange={e=>setMilestone(e.target.value)}><option value="all">全部里程碑</option>{store.milestones.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select><span className="ai-grow"/><small>右键拖动 · 滚轮缩放</small><button aria-label="缩小岗位线路" onClick={()=>setZoom(zoom-.1)}><Minus size={14}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="放大岗位线路" onClick={()=>setZoom(zoom+.1)}><Plus size={14}/></button></div>
 {!nodes.length?<p className="ai-empty">没有匹配任务。可在项目排期新建任务，或调整筛选条件。</p>:<div className={'ai-board'+(panning?' panning':'')} ref={scroll} tabIndex={0} aria-label="岗位任务线路画布"><div className="ai-board-canvas" style={{width,height:y,zoom}}><div className="ai-axis">工作岗位{Array.from({length:base.columns},(_,i)=><span key={i} style={{left:200+i*290}}>{i?'推进阶段 '+(i+1):'起步任务'}</span>)}</div>{lanes.map(l=><div className="ai-lane" key={l.id} style={{top:l.top,height:l.height,width}}><strong>{l.name}</strong></div>)}<svg width={width} height={y} className="ai-lines" aria-hidden="true"><defs><marker id={marker} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="#a58bc8"/></marker></defs>{nodes.flatMap(n=>n.task.dependencyIds.flatMap(id=>{const prev=byId.get(id);return prev?[<path key={id+n.task.id} d={`M ${prev.x+245} ${prev.y+62} C ${prev.x+275} ${prev.y+62},${n.x-30} ${n.y+62},${n.x} ${n.y+62}`} markerEnd={'url(#'+marker+')'}/>]:[];}))}</svg>{nodes.map(n=><button key={n.task.id} className={'ai-task-node status-'+n.task.status} aria-label={'岗位任务：'+n.task.title} style={{left:n.x,top:n.y}} onClick={()=>onOpen(n.task.id)}><span>{n.task.kind} · {n.task.status}</span><strong>{n.task.title}</strong><small>{workAssignees(store,n.task.id,projectId).map(k=>store.personnel?.members.find(m=>m.id===k.memberId)?.name).filter((v,i,a)=>a.indexOf(v)===i).join('、')||'待分配执行者'}</small></button>)}</div></div>}</>;
}

function AiCredentials({controller:c,projectId,toolHistory,testMode}:{controller:Controller;projectId:string;toolHistory:History;testMode:boolean}){
 const team=c.store.personnel||defaultWorkTeam(),members=team.members,positions=positionsOf(c.store);
 const [memberId,setMemberId]=useState(''),[executorName,setExecutorName]=useState(''),[name,setName]=useState('本轮工作'),[workDescription,setWorkDescription]=useState(''),[positionIds,setPositionIds]=useState<string[]>([]),[taskIds,setTaskIds]=useState<string[]>([]),[query,setQuery]=useState('');
 const [expiry,setExpiry]=useState(new Date(Date.now()+30*86400000).toISOString().slice(0,10)),[grant,setGrant]=useState<AiPermission[]>(['progress']),[secret,setSecret]=useState(''),[error,setError]=useState(''),[copied,setCopied]=useState(false),[busy,setBusy]=useState(false);
 const member=members.find(m=>m.id===memberId),disabled=c.blocked||c.pending||busy||testMode;
 const eligible=c.store.tasks.filter(t=>taskPositionIds(c.store,t).some(id=>positionIds.includes(id)&&positions.some(p=>p.id===id&&p.active))),visible=eligible.filter(t=>(t.title+t.description).toLowerCase().includes(query.toLowerCase()));
 const selected=taskIds.filter(id=>eligible.some(t=>t.id===id));
 useEffect(()=>{if(!busy&&!secret)return;const guard=(e:Event)=>e.preventDefault(),unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener(beforeLogoutEvent,guard);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener(beforeLogoutEvent,guard);window.removeEventListener('beforeunload',unload);};},[busy,secret]);
 const togglePosition=(id:string,checked:boolean)=>{const next=checked?[...positionIds,id]:positionIds.filter(p=>p!==id);setPositionIds(next);setTaskIds(ids=>ids.filter(tid=>c.store.tasks.some(t=>t.id===tid&&taskPositionIds(c.store,t).some(p=>next.includes(p)))));};
 const issue=async()=>{if(disabled||!window.desktopClient?.issueAiCredential)return;setError('');let schedule=c.store;if(!schedule.personnel){schedule={...schedule,personnel:defaultWorkTeam()};if(!c.update(()=>schedule))return;}setBusy(true);try{const result=await window.desktopClient.issueAiCredential({projectId,memberId:memberId||undefined,executorName,name,workDescription,positionIds,taskIds:selected,expiresAt:new Date(expiry+'T23:59:59').toISOString(),permissions:grant,schedule});setSecret(JSON.stringify(result.secret,null,2));setCopied(false);setMemberId(result.secret.memberId);c.reloadIfClean();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <><div className="ai-token-intro"><h3>命名执行者，分配本次工作</h3><p>一个 AI 可以领取多个岗位的多项任务。同一岗位可由不同 AI 分工；未勾选的工作不会自动授权。</p></div><div className="ai-token-layout"><section className="gp-card"><h3>生成协作令牌</h3>{testMode&&<p role="status">测试模式下可试排岗位与任务，返回正式项目后签发协作凭证。</p>}<ScheduleRecovery controller={c}/><fieldset className="ar-fields" disabled={disabled}>
  <label className="gp-field">执行者<select aria-label="选择执行者" value={memberId} onChange={e=>{setMemberId(e.target.value);setGrant(e.target.value?members.find(m=>m.id===e.target.value)?.permissions||[]:['progress']);}}><option value="">新建 AI 执行者</option>{members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}（已有执行者）</option>)}</select></label>
  {!memberId&&<label className="gp-field">AI 名称<input aria-label="AI 执行者名称" value={executorName} maxLength={100} onChange={e=>setExecutorName(e.target.value)} placeholder="例如：战斗开发助手、资源制作助手"/></label>}
  <label className="gp-field">本次分配名称<input aria-label="令牌名称" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label>
  <div className="ai-checks"><span>工作岗位（可多选）</span>{positions.map(p=><label key={p.id}><input type="checkbox" aria-label={'令牌岗位：'+p.name} disabled={!p.active} checked={positionIds.includes(p.id)} onChange={e=>togglePosition(p.id,e.target.checked)}/>{p.name}{!p.active?'（停用）':''}</label>)}</div>
  <h4>具体工作（可多选）· 已选 {selected.length} 项</h4><input type="search" aria-label="搜索令牌工作" value={query} onChange={e=>setQuery(e.target.value)} placeholder="按任务名称或说明筛选"/>
  <div className="ai-toolbar"><button type="button" disabled={!visible.length} onClick={()=>setTaskIds(ids=>[...new Set([...ids,...visible.map(t=>t.id)])])}>选择当前结果</button><button type="button" onClick={()=>setTaskIds([])}>清空选择</button></div>
  <div className="ai-work-selection">{visible.map(t=><label key={t.id}><input type="checkbox" aria-label={'令牌工作：'+t.title} checked={selected.includes(t.id)} onChange={e=>setTaskIds(ids=>e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/><span><strong>{t.title}</strong><small>{t.kind} · {t.status}{workAssignees(c.store,t.id,projectId).length?' · 已有执行者，可协作领取':''}</small></span></label>)}</div>
  {!visible.length&&<p className="gp-muted">{!positionIds.length?'先选择岗位，再选择工作内容。':'暂无匹配工作，可到岗位总览调整工作清单。'}</p>}
  <label className="gp-field">工作说明<textarea aria-label="令牌工作说明" value={workDescription} rows={3} maxLength={10000} onChange={e=>setWorkDescription(e.target.value)} placeholder="补充交付范围、协作约定或注意事项"/></label>
  <div className="ai-checks"><span>反馈权限</span>{permissions.map(p=><label key={p}><input type="checkbox" disabled={!!member&&!member.permissions.includes(p)} checked={grant.includes(p)} onChange={e=>setGrant(v=>e.target.checked?[...v,p]:v.filter(x=>x!==p))}/>{aiPermissionLabels[p]}</label>)}</div>
  <label className="gp-field">有效期至<input aria-label="令牌有效期" type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label>
  <p className="gp-muted">生成后保存明确的任务清单。撤销后可重新分配；岗位停用或任务移出所选岗位后，该部分反馈也会停止接收。</p>
  <button className="primary" disabled={(!memberId&&!executorName.trim())||!!memberId&&!member?.active||!name.trim()||!grant.length||!selected.length||!window.desktopClient?.issueAiCredential} onClick={()=>void issue()}><KeyRound size={15}/>生成并领取凭证</button>
  {!window.desktopClient?.issueAiCredential&&<p>请在桌面客户端生成签名凭证。</p>}</fieldset>{error&&<p className="ar-error" role="alert">{error}</p>}</section>
  <section className="gp-card"><h3>已分配工作</h3>{!team.credentials.length&&<p className="gp-muted">尚未签发令牌。岗位清单不需要预先创建程序A、程序B。</p>}{team.credentials.map(k=>{const status=k.projectId!==projectId?'属于原项目':k.revokedAt?'已撤销':Date.parse(k.expiresAt)<=Date.now()?'已过期':!members.find(m=>m.id===k.memberId)?.active?'执行者已停用':k.positionIds&&!credentialTasks(c.store,k).some(t=>workAssignees(c.store,t.id,projectId).some(v=>v.id===k.id))?'暂无可用工作':'有效';const used=[...(c.store.feedbackHistory||[]),...toolHistory].filter(r=>r.identity?.credentialId===k.id).sort((a,b)=>b.at.localeCompare(a.at))[0];return <article className="ai-credential" key={k.id}><div><strong>{members.find(m=>m.id===k.memberId)?.name||'历史执行者'}</strong><span>{status}</span></div><b>{k.name}</b><p>{k.positionIds?k.positionIds.map(id=>positions.find(p=>p.id===id)?.name||'失效岗位').join('、'):'旧版成员分配'} · {k.permissions.map(p=>aiPermissionLabels[p]).join('、')}</p>{k.workDescription&&<p>{k.workDescription}</p>}<details><summary>工作清单 · {credentialTasks(c.store,k).length} 项</summary>{credentialTasks(c.store,k).map(t=><p key={t.id}>{t.title} · {t.status}</p>)}</details><small>有效期：{k.expiresAt.slice(0,10)}</small><code>{k.id}</code><small>{used?'最近处理：'+new Date(used.at).toLocaleString():'尚无已处理反馈'}</small><button className="gp-secondary" disabled={disabled||!!k.revokedAt} onClick={()=>{if(window.confirm('撤销“'+k.name+'”？尚未应用的反馈将重新核验权限。'))c.update(s=>({...s,personnel:{...s.personnel!,credentials:s.personnel!.credentials.map(v=>v.id===k.id?{...v,revokedAt:new Date().toISOString()}:v)}}));}}>撤销令牌</button></article>;})}
  {!!members.length&&<details className="ai-legacy"><summary>执行者记录 · {members.length}</summary>{members.map(m=><div key={m.id}><strong>{m.name}</strong><p>{m.roles.join('、')} · {m.duties}</p><label><input type="checkbox" disabled={disabled} checked={m.active} onChange={e=>c.update(s=>({...s,personnel:{...s.personnel!,members:s.personnel!.members.map(v=>v.id===m.id?{...v,active:e.target.checked}:v)}}))}/>启用执行者</label></div>)}</details>}
  </section></div>
  {busy&&<AiDialog title="正在签发协作凭证" onClose={()=>{}}><p>正在保存工作分配，请稍候。</p></AiDialog>}
  {secret&&<AiDialog title="领取 AI 协作凭证" onClose={()=>{if(window.confirm('确认已保存凭证？关闭后无法再次查看私钥，遗失时请重新签发。'))setSecret('');}}><p>把此凭证单独交给对应 AI。不要放入公用工程文档或版本库。</p><textarea aria-label="AI 私有协作凭证" className="ai-secret" readOnly value={secret}/><div className="ai-toolbar"><button className="gp-secondary" onClick={()=>void navigator.clipboard.writeText(secret).then(()=>setCopied(true)).catch(()=>setError('复制失败，请手动复制凭证。'))}><Copy size={14}/>{copied?'已复制':'复制凭证'}</button><button className="primary" onClick={()=>{const url=URL.createObjectURL(new Blob([secret],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ai-credential-'+JSON.parse(secret).credentialId+'.json';a.click();URL.revokeObjectURL(url);}}><Download size={14}/>保存凭证文件</button></div>{error&&<p role="alert">{error}</p>}<p className="gp-muted">引擎同步会输出本次工作清单。此令牌仅包含刚才选中的工作，后续新增任务需重新分配。</p></AiDialog>}
 </>;
}
