import {taskAssignment,credentialTasks,credentialExpiry,positionsOf,taskPositionIds,aiPermissionLabels,type AiMember} from '../shared/ai-personnel.mjs';
import type {ProductionTask,ProjectScheduleStore} from './project-schedule';
export function AiTaskAssignment({task,members,disabled,onChange,store}:{task:ProductionTask;members:AiMember[];disabled:boolean;onChange:(fields:Partial<ProductionTask>)=>void;store?:ProjectScheduleStore}){
 if(store){const ids=taskPositionIds(store,task),credentials=store.personnel?.credentials.filter(k=>credentialTasks(store,k).some(t=>t.id===task.id))||[];return <fieldset className="ai-assignment-fields" disabled={disabled}><legend>工作岗位与执行分配</legend><div className="ai-checks">{positionsOf(store).map(p=><label key={p.id}><input type="checkbox" aria-label={'任务岗位：'+p.name} disabled={!p.active&&!ids.includes(p.id)} checked={ids.includes(p.id)} onChange={e=>onChange({positionIds:e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id)})}/>{p.name}</label>)}</div><p className="sch-muted">到“人员分配 → 开发者与令牌”维护开发者和任务分配；选择岗位范围的开发者也能处理该岗位后续新增的任务。</p><div>{credentials.map(k=><p key={k.id}>{members.find(m=>m.id===k.memberId)?.name||'历史执行者'} · {k.name} · {k.permissions.map(p=>aiPermissionLabels[p]).join('、')}{k.revokedAt?' · 已撤销':Date.parse(credentialExpiry(store,k))<=Date.now()?' · 已过期':''}</p>)}{!credentials.length&&<p>尚未分配开发者。</p>}{task.assignment&&<details><summary>历史成员分配（保留）</summary><p>主负责人：{members.find(m=>m.id===task.assignment?.primaryId)?.name||task.owner||'未分配'}</p><p>验收负责人：{members.find(m=>m.id===task.assignment?.reviewerId)?.name||'未指定'}</p></details>}</div></fieldset>;}
 const a=taskAssignment(task),available=members.filter(m=>m.active||[a.primaryId,a.reviewerId,...a.collaboratorIds].includes(m.id));
 const options=(id:string)=>[...available.map(m=><option key={m.id} value={m.id} disabled={!m.active}>{m.name}{!m.active?'（停用）':''}</option>),...(id&&!members.some(m=>m.id===id)?[<option key={id} value={id}>成员已失效</option>]:[])];
 return <fieldset className="ai-assignment-fields" disabled={disabled}><legend>AI 任务分配</legend>
 <label>主负责人<select aria-label="AI 主负责人" value={a.primaryId} onChange={e=>onChange({assignment:{...a,primaryId:e.target.value,collaboratorIds:a.collaboratorIds.filter(id=>id!==e.target.value)},owner:members.find(m=>m.id===e.target.value)?.name||''})}><option value="">未分配{!a.primaryId&&task.owner?' · 原负责人：'+task.owner:''}</option>{options(a.primaryId)}</select></label>
 <label>验收负责人<select aria-label="AI 验收负责人" value={a.reviewerId} onChange={e=>onChange({assignment:{...a,reviewerId:e.target.value}})}><option value="">未指定</option>{options(a.reviewerId)}</select></label>
 <div className="ai-checks"><span>协作者</span>{available.filter(m=>m.id!==a.primaryId).map(m=><label key={m.id}><input type="checkbox" disabled={!m.active&&!a.collaboratorIds.includes(m.id)} checked={a.collaboratorIds.includes(m.id)} onChange={e=>onChange({assignment:{...a,collaboratorIds:e.target.checked?[...a.collaboratorIds,m.id]:a.collaboratorIds.filter(id=>id!==m.id)}})}/>{m.name}</label>)}</div>
 {a.reviewerId&&!members.find(m=>m.id===a.reviewerId)?.permissions.includes('review')&&<p className="sch-muted">该成员尚无提交验收结论的权限，请在人员分配中配置。</p>}
 </fieldset>;
}
