import { useState, type FormEvent } from 'react';
import { ArrowDown, ArrowRight, ArrowUp, Folder, UserRound, Swords, Map, Gem, Clapperboard, Sparkles, PanelsTopLeft, Shapes, Music, Pencil, Plus, Trash2, X } from 'lucide-react';
import { artLibrary, artCategoryId, artCategoryName, saveArtCategory, removeArtCategory, moveArtCategory, type ArtItemKind } from './art-library';
import type { ArtStore } from './art-assets';
const categoryIcons: Record<string,typeof Folder> = {角色:UserRound, '敌人与首领':Swords, 场景:Map, 道具:Gem, 动画:Clapperboard, 特效:Sparkles, UI:PanelsTopLeft, 图标:Shapes, 音频:Music};
function ArtCategoryIcon({name}:{name:string}) {const Icon=categoryIcons[name]||Folder;return <Icon size={23}/>;}
export function ArtCategoryHome({store,query,range,onEnter,onSelect,onManage,blocked}:{store:ArtStore;query:string;range:string;onEnter:(id:string)=>void;onSelect:(kind:ArtItemKind,id:string)=>void;onManage:()=>void;blocked:boolean}) {
 const library=artLibrary(store),visible=(archived:boolean)=>range==='all'||(range==='archived'?archived:!archived);
 const requirements=store.requirements.filter(r=>visible(r.archived)),assets=store.assets.filter(a=>visible(a.archived)),q=query.trim().toLocaleLowerCase();
 const matches=[...requirements.map(r=>({kind:'requirement' as const,id:r.id,name:r.name,text:r.description+' '+r.owner,status:r.archived?'已归档':r.status})),...assets.map(a=>({kind:'asset' as const,id:a.id,name:a.name,text:a.description+' '+a.versions.map(v=>v.files.map(f=>f.name).join(' ')).join(' '),status:a.archived?'已归档':a.versions.length+' 个版本'}))].filter(i=>(i.name+' '+i.text+' '+artCategoryName(library,artCategoryId(library,i.kind,i.id))).toLocaleLowerCase().includes(q));
 return q?<><div className="gl-section-heading"><h2>搜索结果</h2><span>{matches.length} 项 · 跨分类查找</span></div><div className="gl-document-grid">{matches.map(i=><button className="gp-list-card ar-search-result" key={i.kind+i.id} onClick={()=>onSelect(i.kind,i.id)}><small>{artCategoryName(library,artCategoryId(library,i.kind,i.id))} / {i.kind==='requirement'?'制作需求':'资产文件'}</small><strong>{i.name}</strong><p>{i.status}</p></button>)}</div>{!matches.length&&<p className="gl-no-documents">没有匹配内容，试试其他名称、说明或文件名。</p>}</>:<>
 <div className="gl-intro"><div><span className="gp-kicker">ART CATEGORIES</span><h2>按内容组织美术制作</h2><p>进入一个分类，查看制作需求、交付文件与验收进度。</p></div><span>{requirements.length} 份需求 · {assets.length} 份资产</span></div>
 <div className="gl-category-grid">{[...library.categories,{id:'',name:'未分类',description:'尚未归类的内容，以及需要手动整理的共用资产。'}].map(c=>{const rs=requirements.filter(r=>artCategoryId(library,'requirement',r.id)===c.id),as=assets.filter(a=>artCategoryId(library,'asset',a.id)===c.id);return <button className="gl-category-card" key={c.id} aria-label={'打开美术分类：'+c.name} onClick={()=>onEnter(c.id)}><span className="gl-category-top"><span className="gl-category-icon"><ArtCategoryIcon name={c.name}/></span><small>{rs.length} 需求 · {as.length} 资产</small></span><strong>{c.name}</strong><p>{c.description}</p><span className="al-category-progress"><span>{rs.filter(r=>r.status==='待制作'||r.status==='需修改').length} 待制作</span><span>{rs.filter(r=>r.status==='待审核').length} 待验收</span><span>{rs.filter(r=>r.status==='已通过').length} 已通过</span></span><span className="gl-category-enter">查看分类<ArrowRight size={14}/></span></button>;})}<button className="gl-add-category" disabled={blocked} onClick={onManage}><Plus size={25}/><strong>新建分类</strong><span>按项目需要组织美术内容</span></button></div></>;
}
export function ArtCategoryManager({store,blocked,apply,onClose}:{store:ArtStore;blocked:boolean;apply:(f:(s:ArtStore)=>ArtStore)=>boolean;onClose:()=>void}) {
 const [id,setId]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState(''),categories=artLibrary(store).categories;
 const clear=()=>{setId('');setName('');setDescription('');setError('');};
 const run=(op:(s:ArtStore)=>ArtStore)=>{try{setError('');const next=op(store);const ok=apply(()=>next);if(!ok)setError('分类修改未保存，请关闭此窗口查看保存提示并重试。');return ok;}catch(e){setError(String(e));return false;}};
 const submit=(e:FormEvent)=>{e.preventDefault();if(run(s=>saveArtCategory(s,name,description,id||undefined)))clear();};
 return <dialog className="gp-dialog gl-category-dialog" aria-label="管理美术分类" ref={node=>{if(node&&!node.open)node.showModal();}} onCancel={e=>{e.preventDefault();onClose();}}><div className="gp-card-heading"><h2>管理美术分类</h2><button className="gp-icon" aria-label="关闭美术分类管理" onClick={onClose}><X size={18}/></button></div><p className="gp-muted">删除分类会将内容移入未分类，保留所有文件与关联。</p><div className="gl-category-manage-list">{categories.map((c,index)=><div className="gl-category-manage-row" key={c.id}><Folder size={16}/><strong>{c.name}</strong><button className="gp-icon" aria-label={'上移美术分类：'+c.name} disabled={blocked||index===0} onClick={()=>run(s=>moveArtCategory(s,c.id,-1))}><ArrowUp size={14}/></button><button className="gp-icon" aria-label={'下移美术分类：'+c.name} disabled={blocked||index===categories.length-1} onClick={()=>run(s=>moveArtCategory(s,c.id,1))}><ArrowDown size={14}/></button><button className="gp-icon" aria-label={'编辑美术分类：'+c.name} disabled={blocked} onClick={()=>{setId(c.id);setName(c.name);setDescription(c.description);}}><Pencil size={14}/></button><button className="gp-icon" aria-label={'删除美术分类：'+c.name} disabled={blocked} onClick={()=>{if(window.confirm('删除分类“'+c.name+'”？内容会移入未分类，文件和关联保留。'))if(run(s=>removeArtCategory(s,c.id))&&id===c.id)clear();}}><Trash2 size={14}/></button></div>)}</div><form onSubmit={submit}><fieldset disabled={blocked}><label className="gp-field">美术分类名称<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label className="gp-field">美术分类说明<textarea rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></label>{error&&<p className="ar-error" role="alert">{error}</p>}<div className="gp-dialog-actions">{id&&<button type="button" className="gp-secondary" onClick={clear}>取消编辑</button>}<button className="primary" type="submit">{id?'保存美术分类':'创建美术分类'}</button></div></fieldset></form></dialog>;
}
