import {useEffect,useState} from 'react';
import {BookImage,FolderOpen,ImagePlus,Search,X,ArrowRight,Database,Download} from 'lucide-react';
import {knowledgeTags,referenceSourceTypes,referenceUsages,type KnowledgeImage,type KnowledgeListing} from '../shared/art-knowledge.mjs';
import './art-knowledge.css';
export function ReferenceImage({id,workspaceId,storagePath}:{id?:string;workspaceId?:string;storagePath?:string}){const [url,setUrl]=useState('');useEffect(()=>{let live=true;setUrl('');const p=id?window.desktopClient?.artKnowledge?.preview(id):workspaceId&&storagePath?window.desktopClient?.artFiles?.readPreview(workspaceId,storagePath).then(r=>r?.dataUrl||''):undefined;p?.then(v=>{if(live)setUrl(v);}).catch(()=>{});return()=>{live=false;};},[id,workspaceId,storagePath]);return url?<img src={url} alt="参考图片" loading="lazy"/>:<div className="ak-image-placeholder"><BookImage/><span>预览暂不可用</span></div>;}
export function ArtKnowledge({onUse}:{onUse?:(image:KnowledgeImage)=>Promise<void>}){
 const api=window.desktopClient?.artKnowledge,[data,setData]=useState<KnowledgeListing>(),[query,setQuery]=useState(''),[tags,setTags]=useState<string[]>([]),[editing,setEditing]=useState<KnowledgeImage>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;api?.list().then(v=>{if(live)setData(v);}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[]);
 const run=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const list=(data?.images||[]).filter(r=>[r.name,r.description,r.creator,r.work,r.source,...r.tags.map(t=>knowledgeTags[t])].join(' ').toLowerCase().includes(query.trim().toLowerCase())&&tags.every(t=>r.tags.includes(t)));
 return <section className="art-knowledge" aria-label="美术知识库"><header className="ak-header"><div><span className="gp-kicker">ART KNOWLEDGE</span><h2>积累参考，为每个项目找到视觉方向。</h2><p>跨项目共享的参考资料。项目采用后保存独立快照，资料库更新不会改变已采用内容。</p></div><BookImage size={36}/></header>
 {!api&&<p role="alert">请在桌面客户端打开美术知识库。</p>}{error&&<p className="ar-error" role="alert">{error}</p>}{notice&&<p className="ak-notice" role="status">{notice}</p>}
 <div className="ak-toolbar"><button className="primary" disabled={busy||!api} onClick={()=>void run(async()=>{const next=await api!.importImages();if(next){setNotice('导入完成，新增 '+Math.max(0,next.images.length-(data?.images.length||0))+' 张；相同图片已去重。');setData(next);}})}><ImagePlus size={16}/>导入参考图</button><button disabled={busy||!api} onClick={()=>void run(async()=>{const next=await api!.choose();if(next){setData(next);setTags([]);setQuery('');}})}><FolderOpen size={16}/>打开资料库</button><button disabled={busy||!api} onClick={()=>void run(async()=>{const dir=await api!.backup();if(dir)setNotice('备份已保存：'+dir+'。可通过“打开资料库”恢复使用。');})}><Download size={16}/>备份资料库</button><button disabled={busy||!api} onClick={()=>void run(()=>api!.reveal())}>打开所在文件夹</button><button disabled={busy||!api} onClick={()=>void run(async()=>setData(await api!.list()))}>刷新</button></div>
 <div className="ak-location"><Database size={15}/><span>{data?.directory||'读取独立资料库…'}</span><small>{data?.images.length||0} 张参考</small></div>
 <div className="ak-search"><Search size={18}/><input aria-label="搜索美术知识库" placeholder="搜索名称、作品、作者、描述…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <details className="ak-tags"><summary>多维标签筛选 · {tags.length?tags.length+' 项（同时满足）':'全部'} </summary><div>{Object.entries(knowledgeTags).map(([id,label])=><label key={id}><input type="checkbox" checked={tags.includes(id)} onChange={e=>setTags(e.target.checked?[...tags,id]:tags.filter(t=>t!==id))}/>{label}</label>)}</div><button onClick={()=>setTags([])}>清空筛选</button></details>
 {!list.length?<div className="ak-empty"><BookImage size={44}/><h3>{data?.images.length?'没有匹配的参考图':'从一张值得借鉴的图片开始'}</h3><p>导入图片，补充来源与标签；在项目参考板中说明借鉴什么、避免什么。</p></div>:<div className="ak-grid">{list.map(r=><article className="ak-card" key={r.id}><button className="ak-thumbnail" aria-label={'编辑参考：'+r.name} onClick={()=>setEditing(structuredClone(r))}><ReferenceImage id={r.id}/></button><div className="ak-card-body"><h3>{r.name}</h3><p>{r.work||'作品未登记'} · {referenceUsages[r.usage]}</p><div className="ak-chips">{r.tags.map(t=><span key={t}>{knowledgeTags[t]}</span>)}</div><div className="ak-toolbar"><button disabled={busy} onClick={()=>setEditing(structuredClone(r))}>编辑资料</button>{onUse&&<button disabled={busy} onClick={()=>void run(async()=>{await onUse(r);setNotice('已加入项目参考板，图片与资料快照已保存。');})}>加入项目参考板 <ArrowRight size={15}/></button>}</div></div></article>)}</div>}
 {editing&&<dialog className="gp-dialog ak-editor" aria-label="编辑参考资料" ref={el=>{if(el&&!el.open)el.showModal();}} onCancel={e=>{if(busy)e.preventDefault();else setEditing(undefined);}}><div className="gp-card-heading"><h3>编辑参考资料 · V{editing.revision}</h3><button disabled={busy} aria-label="关闭参考资料" onClick={()=>setEditing(undefined)}><X/></button></div><ReferenceImage id={editing.id}/><fieldset disabled={busy}>{(['name','work','creator','source','description','usageNotes'] as const).map(key=><label className="gp-field" key={key}>{{name:'参考名称',work:'所属作品',creator:'作者',source:'来源链接或说明',description:'视觉特点',usageNotes:'使用范围与署名说明'}[key]}<textarea aria-label={'参考资料：'+key} rows={key==='description'||key==='usageNotes'?3:1} maxLength={['name','work','creator'].includes(key)?200:key==='source'?2000:4000} value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})}/></label>)}<div className="ak-two">{(['sourceType','usage'] as const).map(key=><label className="gp-field" key={key}>{key==='usage'?'使用权限登记':'资料来源类型'}<select aria-label={'参考资料：'+key} value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})}>{Object.entries(key==='usage'?referenceUsages:referenceSourceTypes).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>)}</div><div className="ak-tags"><p>视觉标签</p><div>{Object.entries(knowledgeTags).map(([id,label])=><label key={id}><input type="checkbox" aria-label={'资料标签：'+label} checked={editing.tags.includes(id)} onChange={e=>setEditing({...editing,tags:e.target.checked?[...editing.tags,id]:editing.tags.filter(t=>t!==id)})}/>{label}</label>)}</div></div></fieldset>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy||!editing.name.trim()} onClick={()=>void run(async()=>{setData(await api!.update(editing.id,editing.revision,editing));setEditing(undefined);})}>保存参考资料</button></dialog>}
 </section>;
}
