import {useState} from 'react';
import {ArrowRight,Check,Palette,Plus,Trash2} from 'lucide-react';
import {artLibrary,artCategoryName} from './art-library';
import {materialItems,type MaterialTarget} from './material-items';
import {artStyleFields,emptyArtStyle,currentArtStyle,confirmArtStyle,styleDraftChanged,styleDefinitionMarkdown,itemStyleContext,itemStyleMarkdown,styleExceptionOf,styleReviewLabels,reviewArtStyle,type StyleDefinition,type StyleField} from './art-style';
import type {ArtController} from './useArtAssets';
import type {ArtStore} from './art-assets';
import './art-style.css';

type Change=(fn:(store:ArtStore)=>ArtStore)=>boolean;
export function ArtStyleGuide({controller,onOpen}:{controller:ArtController;onOpen:(target:MaterialTarget)=>void}){
 const {store,blocked,pending}=controller,style=store.style||emptyArtStyle(),draft=style.draft,version=currentArtStyle(style),library=artLibrary(store);
 const [note,setNote]=useState(''),[error,setError]=useState('');
 const apply:Change=fn=>{try{setError('');return controller.update(fn);}catch(e){setError(e instanceof Error?e.message:String(e));return false;}};
 const patch=(fn:(draft:StyleDefinition)=>StyleDefinition)=>apply(s=>{const current=s.style||emptyArtStyle();return {...s,style:{...current,draft:fn(current.draft)}};});
 const items=materialItems(store).filter(i=>!i.archived),reviews=items.map(i=>({...i,...itemStyleContext(store,i.kind,i.id)})),waiting=reviews.filter(i=>i.state==='pending'||i.state==='changed');
 const categoryIds=[...library.categories.map(c=>c.id),...draft.categories.filter(c=>!library.categories.some(v=>v.id===c.id)).map(c=>c.id)];
 return <section className="as-guide" aria-label="项目美术风格">
  <header className="gp-editor-heading"><div><span className="gp-kicker">ART DIRECTION</span><h2>让每一份素材遵循同一套视觉语言。</h2><p className="gp-muted">先确定项目基准，再补充角色、场景、UI 等分类要求。未填写的内容保持待确定。</p></div><Palette size={32}/></header>
  <div className="as-summary"><article><small>项目风格基准</small><strong>{version?'V'+version.revision+(pending?' · 尚未保存':' · 已确认'):'待确定'}</strong><p>{version?.definition.direction||'填写整体方向后确认基准'}</p></article><article><small>分类补充</small><strong>{version?.definition.categories.filter(c=>c.rules.trim()&&library.categories.some(v=>v.id===c.id)).length||0} / {library.categories.length}</strong><p>沿用现有素材分类，可分别补充规则</p></article><article><small>风格复核</small><strong>{version?waiting.length+' 项待复核':'尚未建立基准'}</strong><p>仅核对风格，素材完成与验收状态保持独立</p></article></div>
  {version&&<details className="gp-card as-inherited"><summary>{pending?'基准预览（尚未保存）':'查看当前生效基准'} · V{version.revision}</summary><p>{version.note} · {new Date(version.at).toLocaleString()}</p><pre>{styleDefinitionMarkdown(version.definition,library.categories)}</pre></details>}
  <section className="gp-card as-draft"><div className="gp-card-heading"><h3>风格草稿</h3><span className="gp-badge">{styleDraftChanged(style)?'有待确认调整':version?'与当前基准一致':'待填写'}</span></div><p className="gp-muted">草稿随编辑保存。确认后才会进入素材制作标准；空白项会明确标为“待确定”。</p>
   <div className="as-field-grid">{(Object.entries(artStyleFields) as [StyleField,string][]).map(([key,label])=><label className="gp-field" key={key}>{label}<textarea aria-label={'美术风格：'+label} rows={key==='direction'?3:2} maxLength={4000} disabled={blocked} value={draft[key]} placeholder="待确定" onChange={e=>patch(d=>({...d,[key]:e.target.value}))}/></label>)}</div>
  </section>
  <section className="gp-card"><div className="gp-card-heading"><div><h3>项目色板</h3><p className="gp-muted">为每种颜色写明用途，例如主体、背景、强调或警告。</p></div><button className="gp-secondary" disabled={blocked||draft.palette.length>=32} onClick={()=>patch(d=>({...d,palette:[...d.palette,{id:crypto.randomUUID(),name:'',color:'',usage:''}]}))}><Plus size={15}/>添加颜色</button></div>
   {!draft.palette.length&&<p className="gp-muted">色板待确定。</p>}<div className="as-colors">{draft.palette.map((c,i)=><article key={c.id} className="as-color"><div className="as-swatch" style={c.color?{background:c.color}:{}} aria-label={c.color||'色值待确定'}/><label className="gp-field">颜色名称<input aria-label={'颜色名称 '+(i+1)} maxLength={200} disabled={blocked} value={c.name} onChange={e=>patch(d=>({...d,palette:d.palette.map(v=>v.id===c.id?{...v,name:e.target.value}:v)}))}/></label><label className="as-color-picker">色值<input type="color" aria-label={'色值 '+(i+1)} disabled={blocked} value={c.color||'#000000'} onChange={e=>patch(d=>({...d,palette:d.palette.map(v=>v.id===c.id?{...v,color:e.target.value}:v)}))}/><code>{c.color||'待确定'}</code></label><label className="gp-field">用途<textarea aria-label={'颜色用途 '+(i+1)} rows={2} maxLength={1000} disabled={blocked} value={c.usage} onChange={e=>patch(d=>({...d,palette:d.palette.map(v=>v.id===c.id?{...v,usage:e.target.value}:v)}))}/></label><button className="gp-secondary" disabled={blocked} aria-label={'移除颜色 '+(i+1)} onClick={()=>patch(d=>({...d,palette:d.palette.filter(v=>v.id!==c.id)}))}><Trash2 size={14}/>移除</button></article>)}</div>
  </section>
  <section className="gp-card"><h3>分类补充</h3><p className="gp-muted">全局基准适用于所有视觉素材。为需要的分类补充比例、构图、尺寸、边距等要求；音频等非视觉分类可注明不适用。</p><div className="as-field-grid">{categoryIds.map(id=><label key={id} className="gp-field">{library.categories.some(c=>c.id===id)?artCategoryName(library,id):'已移除分类（'+id+'）'}<textarea aria-label={'分类风格：'+(library.categories.find(c=>c.id===id)?.name||id)} rows={3} maxLength={6000} disabled={blocked} value={draft.categories.find(c=>c.id===id)?.rules||''} placeholder="继承项目基准，无额外要求" onChange={e=>patch(d=>({...d,categories:e.target.value?d.categories.some(c=>c.id===id)?d.categories.map(c=>c.id===id?{...c,rules:e.target.value}:c):[...d.categories,{id,rules:e.target.value}]:d.categories.filter(c=>c.id!==id)}))}/></label>)}</div></section>
  <section className="gp-card"><div className="gp-card-heading"><div><h3>参考与反例</h3><p className="gp-muted">记录参考的来源、要采用的特点与要避免的表现。可填写文档、网址或工程内图片路径。</p></div><button className="gp-secondary" disabled={blocked||draft.references.length>=30} onClick={()=>patch(d=>({...d,references:[...d.references,{id:crypto.randomUUID(),title:'',source:'',take:'',avoid:''}]}))}><Plus size={15}/>添加参考</button></div>
   <div className="as-references">{draft.references.map((r,i)=><article className="as-reference" key={r.id}>{(['title','source','take','avoid'] as const).map(key=><label className="gp-field" key={key}>{({title:'参考名称',source:'来源或路径',take:'采用特点',avoid:'避免表现'})[key]}<textarea rows={key==='take'||key==='avoid'?3:1} maxLength={key==='title'?200:2000} aria-label={({'title':'参考名称','source':'参考来源','take':'参考采用特点','avoid':'参考避免表现'})[key]+' '+(i+1)} disabled={blocked} value={r[key]} onChange={e=>patch(d=>({...d,references:d.references.map(v=>v.id===r.id?{...v,[key]:e.target.value}:v)}))}/></label>)}<button className="gp-secondary" aria-label={'移除参考 '+(i+1)} disabled={blocked} onClick={()=>patch(d=>({...d,references:d.references.filter(v=>v.id!==r.id)}))}><Trash2 size={14}/>移除参考</button></article>)}</div>{!draft.references.length&&<p className="gp-muted">尚未添加参考。</p>}
  </section>
  <section className="gp-card as-confirm"><h3>{version?'确认风格调整':'确认首版风格基准'}</h3><p className="gp-muted">确认后，受影响素材会提示复核；已有制作进度、交付记录和验收结果保留。</p><label className="gp-field">确认说明<textarea aria-label="风格确认说明" rows={2} maxLength={2000} disabled={blocked} value={note} onChange={e=>setNote(e.target.value)} placeholder="说明这次确定了什么，以及调整的原因"/></label>{error&&<p className="ar-error" role="alert">{error}</p>}<button className="primary" disabled={blocked||pending||!draft.direction.trim()||!note.trim()||!styleDraftChanged(style)} onClick={()=>{if(apply(s=>({...s,style:confirmArtStyle(s.style||emptyArtStyle(),note)})))setNote('');}}><Check size={16}/>确认美术风格基准</button></section>
  {version&&<section className="gp-card"><h3>待风格复核 · {waiting.length}</h3><p className="gp-muted">进入素材核对项目基准、分类补充和单项特殊要求，再标记风格复核。</p><div className="as-review-list">{waiting.map(i=><button className="gp-secondary" key={i.key} onClick={()=>onOpen(i)}><span>{i.name}<small>{styleReviewLabels[i.state]} · {artCategoryName(library,i.categoryId)}</small></span><ArrowRight size={16}/></button>)}</div>{!waiting.length&&<p className="gp-muted">所有有效素材均已核对当前适用风格。</p>}</section>}
  {!!style.versions.length&&<details className="gp-card as-history"><summary>风格变更记录 · {style.versions.length}</summary>{[...style.versions].reverse().map(v=><details key={v.revision}><summary>V{v.revision} · {new Date(v.at).toLocaleString()} · {v.note}</summary><pre>{styleDefinitionMarkdown(v.definition,library.categories)}</pre></details>)}</details>}
 </section>;
}

export function MaterialStyleRequirements({controller,target,apply}:{controller:ArtController;target:MaterialTarget;apply:Change}){
 const {item,version,state,categoryId}=itemStyleContext(controller.store,target.kind,target.id),exception=styleExceptionOf(item),disabled=controller.blocked||!!item?.archived;
 if(!item)return null;
 const patch=(changes:Partial<typeof item>)=>apply(s=>({...s,[target.kind==='requirement'?'requirements':'assets']:s[target.kind==='requirement'?'requirements':'assets'].map(v=>v.id===target.id?{...v,...changes,updatedAt:new Date().toISOString()}:v)}));
 return <section className="gp-card as-item" aria-label="素材适用美术风格"><div className="gp-card-heading"><h3>适用美术风格</h3><span className={'gp-badge as-state-'+state}>{styleReviewLabels[state]}</span></div><p>{version?'继承项目基准 V'+version.revision+'：'+version.definition.direction:'项目美术风格待确定，请在“美术风格”页签中明确基准。'}</p><details className="as-inherited"><summary>查看项目基准与分类补充</summary><pre>{itemStyleMarkdown(controller.store,target.kind,target.id)}</pre></details><div className="as-field-grid"><label className="gp-field">单项特殊要求<textarea aria-label="素材风格特殊要求" rows={3} maxLength={3000} disabled={disabled} value={exception.requirements} placeholder="无特殊要求，继承项目与分类规则" onChange={e=>patch({styleException:{...exception,requirements:e.target.value}})}/></label><label className="gp-field">特殊要求原因<textarea aria-label="素材风格特殊要求原因" rows={3} maxLength={3000} disabled={disabled} value={exception.reason} placeholder="说明为何需要偏离或补充项目基准" onChange={e=>patch({styleException:{...exception,reason:e.target.value}})}/></label></div><button className="gp-secondary" disabled={disabled||controller.pending||!version||state==='reviewed'||!!exception.requirements.trim()&&!exception.reason.trim()} onClick={()=>patch({styleReview:reviewArtStyle(controller.store.style,item,categoryId)})}><Check size={15}/>标记风格已复核</button><p className="gp-muted">核对风格后单独标记，不改变制作进度或验收结果。</p></section>;
}
