import type {EngineConfig} from './engine';
import type {ArtStore} from './art-assets';
import type {AiDocument} from './ai-export';
import type {SyncSettings} from '../shared/engine-sync.mjs';
import type {Feedback,FeedbackRow,FeedbackReceipt} from '../shared/engine-feedback.mjs';
import type {ProjectScheduleStore} from './project-schedule';
import type {DevelopmentToolsStore} from './development-tools';
export type CollaborationSource={schedule:ProjectScheduleStore;tools:DevelopmentToolsStore};
export type FeedbackEntry={legacy?:boolean;identity?:import('../shared/engine-feedback.mjs').FeedbackIdentity;path:string;state:'pending'|'invalid'|'processed';feedback?:Feedback;title?:string;rows:FeedbackRow[];token?:string;error?:string;receipt?:FeedbackReceipt;designChanged?:boolean};
export type FeedbackScan={root:string;entries:FeedbackEntry[];history:FeedbackReceipt[];missingReceipts:string[]};
export type FeedbackApplyResult={receipt:FeedbackReceipt;warning:string};
export type FeedbackBatchResult={applied:FeedbackApplyResult[];skipped:{path:string;reason:string}[];failed:{path:string;reason:string}[]};
export type SyncContext={projectId:string;config:EngineConfig};
export type SyncInput=SyncContext&{settings:SyncSettings;document:AiDocument;art:ArtStore;collaboration:CollaborationSource};
export type SyncRow={id:string;path:string;kind:'document'|'asset'|'collaboration';label:string;version:string;versionId?:string;placeholder?:boolean;remove?:boolean;status:'added'|'updated'|'removed'|'unchanged'|'conflict';reason:string};
export type SyncHistory={id:string;at:string;status:'success'|'failed';kind?:'rebind';fromProjectId?:string;toProjectId?:string;message:string;files:{path:string;action:string;version:string;versionId:string}[];backupDirectory?:string};
export type SyncBinding={status:'unbound'|'current'|'project-mismatch'|'engine-mismatch';root:string;projectId:string;engine:EngineConfig['engine'];ownerProjectId:string|null;ownerEngine:EngineConfig['engine']|null;fileCount:number;historyCount:number;token?:string;reason:string};
export type SyncPlan={token:string;root:string;rows:SyncRow[];warnings:string[];history:SyncHistory[]};
export type EngineSyncAPI=import('./data-sync').DataSyncAPI&{
  feedbackScan:(input:SyncContext&{collaboration:CollaborationSource})=>Promise<FeedbackScan>;
  feedbackApply:(input:{token:string;decisions:Record<string,'keep'|'feedback'>;dismiss:boolean;acceptCompletion:boolean;acceptLegacy?:boolean})=>Promise<FeedbackApplyResult>;
  feedbackApplyBatch:(input:{tokens:string[];acceptCompletion:boolean})=>Promise<FeedbackBatchResult>;
  feedbackRepair:(input:SyncContext)=>Promise<{count:number}>;
  binding:(input:SyncContext)=>Promise<SyncBinding>;
  rebind:(input:{token:string})=>Promise<SyncHistory>;
  preview:(input:SyncInput)=>Promise<SyncPlan>;
  apply:(input:{token:string;decisions:Record<string,'keep'|'replace'>;removals:string[]})=>Promise<SyncHistory>;
  history:(input:SyncContext)=>Promise<{entries:SyncHistory[];interrupted:boolean}>;
  recover:(input:SyncContext)=>Promise<{message:string}>;
  release:(token:string)=>Promise<void>;
};
