import { StageBoard } from './SpatialEditor';
import { spatialObjectLocation, type SpatialView } from './spatial-layout';
export { GameplaySpace } from './SpatialEditor';
import { useEffect, useRef, useState } from 'react';
import { Plus, Trash2, Copy, Play, Pause, RotateCcw } from 'lucide-react';
import type { GameplayDesign } from './gameplay';
import { stageColors, createTrack, createTimelineEvent, spaceOwner, stageIssues, eventEnd, eventLastStart, timelineStats, timelineBuckets, dueOccurrences, activeOccurrences, type GameplayTimeline, type TimelineEvent } from './gameplay-stage';
import './gameplay-stage.css';
type Common = { design: GameplayDesign; designs: GameplayDesign[]; disabled: boolean; onChange: (changes: Partial<GameplayDesign>) => void; onNavigate: (id: string, view?: SpatialView) => void };
function NumberField({ label, value, min, max, step = 1, disabled, onChange }: { label: string; value: number; min: number; max: number; step?: number; disabled?: boolean; onChange: (value: number) => void | boolean }) {
  const [draft, setDraft] = useState(String(value)), [error, setError] = useState('');
  useEffect(() => { setDraft(String(value)); setError(''); }, [value]);
  const commit = () => { const n = Number(draft); if (!draft.trim() || !Number.isFinite(n) || n < min || n > max || (step === 1 && !Number.isInteger(n))) { setError(`请输入 ${min}–${max} ${step === 1 ? '之间的整数' : '之间的数值'}`); return; } setError(''); if (n !== value && onChange(n) === false) setDraft(String(value)); };
  return <label className="gp-field">{label}<input type="number" aria-label={label} aria-invalid={!!error} value={draft} min={min} max={max} step={step} disabled={disabled} onChange={e => setDraft(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); commit(); } }} />{error && <small className="field-error" role="alert">{error}</small>}</label>;
}
function StageIssues({ issues }: { issues: string[] }) { return issues.length ? <div className="gs-issues" role="status"><strong>空间与时间检查</strong><ul>{issues.map(s => <li key={s}>{s}</li>)}</ul></div> : null; }
function ColorField({ label, value, onChange }: { label: string; value: keyof typeof stageColors; onChange: (c: keyof typeof stageColors) => void }) { return <label className="gp-field">{label}<select aria-label={label} value={value} onChange={e => onChange(e.target.value as typeof value)}>{Object.keys(stageColors).map((c, i) => <option key={c} value={c}>{['绿色', '紫色', '蓝色', '黄色', '红色'][i]}</option>)}</select></label>; }
function TimelineBoard({ timeline: t, cursor, selected, onSelect, onCursor }: { timeline: GameplayTimeline; cursor: number; selected: string; onSelect: (id: string) => void; onCursor: (n: number) => void }) {
  const domain = Math.max(t.duration, timelineStats(t).last), plot = 800, left = 155, width = left + plot + 24;
  const lanes: ({ type: 'track'; id: string; name: string; color: string } | { type: 'event'; event: TimelineEvent; color: string })[] = t.tracks.flatMap(track => [{ type: 'track' as const, id: track.id, name: track.name, color: stageColors[track.color] }, ...t.events.filter(e => e.trackId === track.id).map(event => ({ type: 'event' as const, event, color: stageColors[track.color] }))]);
  const orphan = t.events.filter(e => !t.tracks.some(x => x.id === e.trackId)); if (orphan.length) lanes.push({ type: 'track', id: 'missing', name: '轨道已失效', color: '#df8b89' }, ...orphan.map(event => ({ type: 'event' as const, event, color: '#df8b89' })));
  const height = Math.max(150, 58 + lanes.length * 37), x = (seconds: number) => left + seconds / domain * plot;
  return <div className="st-time-chart"><div className="st-chart-caption"><span>事件时间轴 · 秒</span><span>圆点＝触发 · 色条＝持续 / 重复跨度</span></div><div className="st-time-scroll"><svg role="group" aria-label="事件时间轴" viewBox={`0 0 ${width} ${height}`} style={{ minWidth: 740, width: '100%' }}>
    {Array.from({ length: 7 }, (_, i) => <g key={i}><line x1={x(domain * i / 6)} x2={x(domain * i / 6)} y1="32" y2={height} stroke="#45354f" strokeDasharray="3 5" /><text x={x(domain * i / 6)} y="23" textAnchor="middle" fill="#b6a2ca" fontSize="11">{Math.round(domain * i / 6 * 10) / 10}s</text></g>)}
    {lanes.map((lane, index) => { const y = 55 + index * 37; if (lane.type === 'track') return <g key={'t' + lane.id}><rect x="0" y={y - 19} width={width} height="30" fill={lane.color + '16'} /><text x="15" y={y} fontSize="12" fontWeight="600" fill={lane.color}>{lane.name || '未命名轨道'}</text></g>;
      const e = lane.event, active = e.id === selected, span = Math.max(4, x(eventEnd(e)) - x(e.start)); return <g key={'e' + e.id} role="button" tabIndex={0} aria-label={'查看时间事件：' + (e.name || '未命名事件')} className="st-time-event" onClick={() => onSelect(e.id)} onKeyDown={ev => { if (['Enter', ' '].includes(ev.key)) { ev.preventDefault(); onSelect(e.id); } }}>
        <title>{e.name}：{e.start}s，{e.repeat}次，间隔{e.interval}s，每次{e.quantity}，持续{e.duration}s</title><rect x="0" y={y - 18} width={width} height="34" fill={active ? '#49325f70' : 'transparent'} /><text x="15" y={y + 3} fontSize="11" fill={active ? '#e8d1ff' : '#beafcb'}>{e.name.length > 13 ? e.name.slice(0, 12) + '…' : e.name || '未命名事件'}</text>
        <rect x={x(e.start)} y={y - 7} width={span} height="14" rx="4" fill={lane.color + '38'} stroke={active ? lane.color : 'none'} />
        {Array.from({ length: Math.min(e.repeat, 40) }, (_, i) => <g key={i}>{e.duration > 0 && <rect x={x(e.start + i * e.interval)} y={y - 6} width={Math.max(2, e.duration / domain * plot)} height="12" rx="3" fill={lane.color + '55'} />}<circle cx={x(e.start + i * e.interval)} cy={y} r={active ? 4.5 : 3.5} fill={lane.color} /></g>)}
        {e.repeat > 40 && <text x={Math.min(width - 55, x(eventLastStart(e)))} y={y + 4} fill={lane.color} fontSize="10">×{e.repeat}</text>}
      </g>; })}
    <line x1={x(cursor)} x2={x(cursor)} y1="30" y2={height} stroke="#f3d7a1" strokeWidth="2" pointerEvents="none" />
    <rect x={left} y="0" width={plot} height="31" fill="transparent" role="slider" tabIndex={0} aria-label="时间轴刻度游标" aria-valuemin={0} aria-valuemax={t.duration} aria-valuenow={cursor} onClick={e => { const box = e.currentTarget.getBoundingClientRect(); onCursor(Math.max(0, Math.min(t.duration, Math.round((e.clientX - box.left) / box.width * domain * 10) / 10))); }} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); onCursor(Math.min(t.duration, Math.max(0, cursor + (e.key === 'ArrowRight' ? 1 : -1)))); } }} />
  </svg></div></div>;
}
export function GameplayTime({ design: d, designs, disabled, onChange, onNavigate, initialEventId }: Common & { initialEventId?: string }) {
  const t = d.timeline, owner = spaceOwner(d, designs); const [trackId, setTrackId] = useState(t.events.find(e => e.id === initialEventId)?.trackId ?? ''), [eventId, setEventId] = useState(initialEventId ?? ''), [error, setError] = useState(''), [cursor, setCursor] = useState(0), [playing, setPlaying] = useState(false), [speed, setSpeed] = useState(10);
  const track = t.tracks.find(x => x.id === trackId) ?? t.tracks[0], event = t.events.find(e => e.id === eventId), frame = useRef(0);
  useEffect(() => { if (!playing) return; let before = performance.now(); const step = (now: number) => { const elapsed = (now - before) / 1000 * speed; before = now; setCursor(v => Math.min(t.duration, v + elapsed)); frame.current = requestAnimationFrame(step); }; frame.current = requestAnimationFrame(step); return () => cancelAnimationFrame(frame.current); }, [playing, speed, t.duration]);
  useEffect(() => { if (cursor >= t.duration) { setPlaying(false); if (cursor > t.duration) setCursor(t.duration); } }, [cursor, t.duration]);
  const patch = (changes: Partial<GameplayTimeline>) => { setPlaying(false); setError(''); onChange({ timeline: { ...t, ...changes } }); };
  const patchEvent = (changes: Partial<TimelineEvent>) => { if (event) patch({ events: t.events.map(e => e.id === event.id ? { ...e, ...changes } : e) }); };
  const seek = (n: number) => { setPlaying(false); setCursor(n); };
  const stats = timelineStats(t, cursor), buckets = timelineBuckets(t, Math.max(1, Math.ceil(Math.max(t.duration, stats.last) / 18 / 5) * 5)), maxBucket = Math.max(1, ...buckets.map(b => b.quantity));
  const counts = new Map<string, number>(); for (const e of t.events) if (e.objectId) counts.set(e.objectId, (counts.get(e.objectId) ?? 0) + dueOccurrences(e, cursor) * e.quantity);
  const selectEvent = (id: string) => { const found = t.events.find(e => e.id === id); setEventId(id); if (found) setTrackId(found.trackId); };
  return <div className="gs-page st-page"><div className="gs-intro"><div><span className="gp-kicker">TIME & SEQUENCE</span><h3>时间轴</h3><p>把波次、资源、阶段和提示放在同一个时钟下，检查发生时间与空间位置。</p></div><button className="gp-secondary" disabled={disabled || t.tracks.length >= 30} onClick={() => { const next = createTrack(); next.name = '轨道 ' + (t.tracks.length + 1); patch({ tracks: [...t.tracks, next] }); setTrackId(next.id); }}><Plus size={14} />添加时间轨道</button></div>
    <fieldset className="gs-fieldset" disabled={disabled}><div className="st-time-settings"><NumberField label="计划时长（秒）" value={t.duration} min={1} max={86400} step={.1} onChange={duration => patch({ duration })} /><label className="gp-field">计时基准<input aria-label="计时基准" value={t.clock} onChange={e => patch({ clock: e.target.value })} /></label><label className="gp-field">时间轴空间来源<select aria-label="时间轴空间来源" value={t.spaceOwnerId} onChange={e => { const oldOwner = owner?.id, nextId = e.target.value || d.id; if (oldOwner !== nextId && t.events.some(e => e.objectId)) { setError('已有事件关联空间对象，请先清除或调整这些位置关联，再更换空间来源'); return; } patch({ spaceOwnerId: e.target.value }); }}><option value="">本玩法空间布局</option>{t.spaceOwnerId && !designs.some(x => x.id === t.spaceOwnerId) && <option value={t.spaceOwnerId}>已失效的玩法</option>}{designs.filter(x => x.id !== d.id || x.id === t.spaceOwnerId).map(x => <option key={x.id} value={x.id}>{x.title || '未命名'}{x.archived ? '（已归档）' : ''}</option>)}</select></label></div></fieldset>
    {error && <p className="field-error" role="alert">{error}</p>}<StageIssues issues={stageIssues(d, designs)} />
    <div className="st-time-summary"><div><small>事件条目</small><strong>{t.events.length}</strong></div><div><small>计划触发</small><strong>{stats.occurrences}<small> 次</small></strong></div><div><small>计划数量</small><strong>{stats.quantity}</strong></div><div><small>最后事件结束</small><strong>{stats.last}<small> 秒</small></strong></div></div>
    <TimelineBoard timeline={t} cursor={cursor} selected={eventId} onSelect={selectEvent} onCursor={seek} />
    {event && <div className="gs-edge-detail" aria-label="选中时间事件详情"><strong>{event.name || '未命名事件'}</strong><p>{event.start} 秒开始 · 持续 {event.duration} 秒 · {event.repeat} 次 × {event.quantity} · 最后触发 {eventLastStart(event)} 秒</p><p>位置：{event.objectId ? owner?.space.objects.find(o => o.id === event.objectId)?.name || '关联已失效' : '未指定'} · 条件：{event.condition || '无附加条件'}</p><div className="gp-actions"><a className="gs-text-link" href="#st-time-editors">前往事件属性 ↓</a><button className="gp-secondary" onClick={() => seek(Math.min(t.duration, event.start))}>预览事件开始</button></div></div>}
    <section className="gp-card st-preview"><div className="gp-card-heading"><div><h3>时间预览</h3><p className="gp-muted">按时间计算计划触发；条件按满足处理，不模拟移动、战斗或存活数量。</p></div><div className="gp-actions"><button className="gp-secondary" onClick={() => { if (cursor >= t.duration) setCursor(0); setPlaying(v => !v); }}>{playing ? <Pause size={14} /> : <Play size={14} />}{playing ? '暂停时间预览' : '播放时间预览'}</button><button className="gp-icon" aria-label="重置时间预览" onClick={() => seek(0)}><RotateCcw size={14} /></button></div></div>
      <div className="st-scrubber"><output aria-label="当前预览时间">{cursor.toFixed(1)} s</output><input type="range" aria-label="预览时间游标" min="0" max={t.duration} step=".1" value={cursor} onChange={e => seek(Number(e.target.value))} /><select aria-label="预览速度" value={speed} onChange={e => setSpeed(Number(e.target.value))}>{[1, 2, 5, 10].map(n => <option key={n} value={n}>{n}×</option>)}</select></div>
      <div className="st-preview-facts"><span>累计到点 <strong aria-label="累计计划数量">{stats.dueQuantity}</strong> 个计划量 / {stats.due} 次触发</span><span>当前持续事件 <strong>{stats.active}</strong> 个</span></div>
      <div className="st-track-totals">{t.tracks.map(tr => { const events = t.events.filter(e => e.trackId === tr.id); return <span key={tr.id} style={{ borderColor: stageColors[tr.color] }}>{tr.name || '未命名'}：{events.reduce((n, e) => n + dueOccurrences(e, cursor) * e.quantity, 0)} / {events.reduce((n, e) => n + e.repeat * e.quantity, 0)}</span>; })}</div>
      <div className="st-density" aria-label="计划数量分布">{buckets.map((b, i) => <button key={i} title={`${b.start}–${b.end}秒：${b.quantity} 个计划量`} aria-label={`${b.start}至${b.end}秒计划数量 ${b.quantity}`} onClick={() => seek(Math.min(t.duration, b.start))}><span style={{ height: Math.max(3, b.quantity / maxBucket * 60) }} /><small>{b.start}s</small></button>)}</div><p className="gp-muted">柱状分布累加每次事件的数量，不代表难度或同时存活数量。</p>
      {owner && <><div className="gp-card-heading"><h3>空间联动 · {owner.title || '未命名玩法'}</h3>{owner.id !== d.id && <button className="gs-text-link" onClick={() => onNavigate(owner.id)}>前往来源玩法 →</button>}</div><p className="gp-muted">位置徽标显示截至当前时间的累计计划数量。选择事件可高亮它关联的位置。</p><StageBoard onNavigate={onNavigate} label="时间轴空间预览" space={owner.space} counts={counts} selectedId={event?.objectId} onObject={id => { const match = t.events.find(e => e.objectId === id); if (match) selectEvent(match.id); }} /></>}
    </section>
    <div className="st-time-editors" id="st-time-editors"><section className="gp-card"><h3>轨道与事件</h3><fieldset className="gs-fieldset" disabled={disabled}><div><label className="gp-field">编辑轨道<select aria-label="编辑轨道" value={track?.id ?? ''} onChange={e => setTrackId(e.target.value)}><option value="">请选择轨道</option>{t.tracks.map(tr => <option key={tr.id} value={tr.id}>{tr.name || '未命名'}</option>)}</select></label>{track && <><label className="gp-field">轨道名称<input aria-label="轨道名称" value={track.name} onChange={e => patch({ tracks: t.tracks.map(x => x.id === track.id ? { ...x, name: e.target.value } : x) })} /></label><ColorField label="轨道颜色" value={track.color} onChange={color => patch({ tracks: t.tracks.map(x => x.id === track.id ? { ...x, color } : x) })} /></>}</div><div className="gp-actions"><button className="gp-secondary" disabled={!track || t.events.length >= 200} onClick={() => { if (!track) return; const next = createTimelineEvent(track.id); next.name = '事件 ' + (t.events.length + 1); patch({ events: [...t.events, next] }); setEventId(next.id); }}><Plus size={14} />添加时间事件</button><button className="gp-secondary gs-delete" disabled={!track} onClick={() => { if (!track) return; if (t.events.some(e => e.trackId === track.id)) { setError('轨道还有事件，请先移动或删除这些事件'); return; } patch({ tracks: t.tracks.filter(x => x.id !== track.id) }); setTrackId(''); }}><Trash2 size={14} />删除时间轨道</button></div></fieldset>
      <div className="st-event-list">{t.events.filter(e => e.trackId === track?.id).map(e => <button key={e.id} aria-label={'编辑时间事件：' + (e.name || '未命名')} className={e.id === eventId ? 'selected' : ''} onClick={() => selectEvent(e.id)}><strong>{e.name || '未命名'}</strong><small>{e.start}s · {e.repeat} 次 × {e.quantity} · 末次 {eventLastStart(e)}s</small></button>)}</div>
    </section><section className="gp-card"><h3>事件属性</h3>{!event ? <p className="gp-muted">添加事件或点击时间轴上的事件进行编辑。</p> : <fieldset className="gs-fieldset" disabled={disabled}><div><label className="gp-field">事件名称<input aria-label="事件名称" value={event.name} onChange={e => patchEvent({ name: e.target.value })} /></label><label className="gp-field">所属轨道<select aria-label="所属轨道" value={event.trackId} onChange={e => { patchEvent({ trackId: e.target.value }); setTrackId(e.target.value); }}>{!t.tracks.some(tr => tr.id === event.trackId) && <option value={event.trackId}>轨道已失效</option>}{t.tracks.map(tr => <option key={tr.id} value={tr.id}>{tr.name || '未命名'}</option>)}</select></label><div className="gp-two-fields">
      <NumberField label="开始时间（秒）" value={event.start} min={0} max={86400} step={.1} onChange={start => patchEvent({ start })} /><NumberField label="持续时间（秒）" value={event.duration} min={0} max={86400} step={.1} onChange={duration => patchEvent({ duration })} /><NumberField label="重复次数" value={event.repeat} min={1} max={100} onChange={repeat => patchEvent({ repeat })} /><NumberField label="重复间隔（秒）" value={event.interval} min={0} max={86400} step={.1} onChange={interval => patchEvent({ interval })} /><NumberField label="每次数量" value={event.quantity} min={1} max={10000} onChange={quantity => patchEvent({ quantity })} /></div><p className="gp-muted">0 秒持续表示瞬时事件；0 秒间隔表示同一时刻触发多次。所有时间以当前计时基准为准。</p>
      <label className="gp-field">关联空间对象<select aria-label="关联空间对象" value={event.objectId} onChange={e => patchEvent({ objectId: e.target.value })}><option value="">不指定位置</option>{event.objectId && !owner?.space.objects.some(x => x.id === event.objectId) && <option value={event.objectId}>对象已失效</option>}{owner?.space.objects.map(o => <option key={o.id} value={o.id}>{o.name || '未命名'} · {spatialObjectLocation(o, owner!.space)}</option>)}</select></label>
      <label className="gp-field">事件触发条件<textarea aria-label="事件触发条件" rows={2} value={event.condition} onChange={e => patchEvent({ condition: e.target.value })} placeholder="例如：游戏处于Running且本事件尚未执行" /></label><label className="gp-field">事件说明<textarea aria-label="事件说明" rows={3} value={event.notes} onChange={e => patchEvent({ notes: e.target.value })} placeholder="描述生成内容、提示或阶段行为。" /></label></div><div className="gp-actions"><button className="gp-secondary" disabled={t.events.length >= 200} onClick={() => { const copy = { ...event, id: crypto.randomUUID(), name: event.name + ' · 副本' }; patch({ events: [...t.events, copy] }); setEventId(copy.id); }}><Copy size={14} />复制时间事件</button><button className="gp-secondary gs-delete" onClick={() => { patch({ events: t.events.filter(e => e.id !== event.id) }); setEventId(''); }}><Trash2 size={14} />删除时间事件</button></div></fieldset>}</section></div>
  </div>;
}
