import { useEffect, useId, useRef, useState, type KeyboardEvent } from 'react';
import { Plus, Trash2, Copy, MousePointer2, Move, Play, Pause, RotateCcw } from 'lucide-react';
import type { GameplayDesign } from './gameplay';
import { stageKinds, stageColors, createStageObject, resizeSpace, removeStageObject, createTrack, createTimelineEvent, spaceOwner, stageColumn, stageIssues, eventEnd, eventLastStart, timelineStats, timelineBuckets, dueOccurrences, activeOccurrences, type StageLayout, type StageObject, type GameplayTimeline, type TimelineEvent } from './gameplay-stage';
import './gameplay-stage.css';
type Common = { design: GameplayDesign; designs: GameplayDesign[]; disabled: boolean; onChange: (changes: Partial<GameplayDesign>) => void; onNavigate: (id: string) => void };
function NumberField({ label, value, min, max, step = 1, disabled, onChange }: { label: string; value: number; min: number; max: number; step?: number; disabled?: boolean; onChange: (value: number) => void | boolean }) {
  const [draft, setDraft] = useState(String(value)), [error, setError] = useState('');
  useEffect(() => { setDraft(String(value)); setError(''); }, [value]);
  const commit = () => { const n = Number(draft); if (!draft.trim() || !Number.isFinite(n) || n < min || n > max || (step === 1 && !Number.isInteger(n))) { setError(`请输入 ${min}–${max} ${step === 1 ? '之间的整数' : '之间的数值'}`); return; } setError(''); if (n !== value && onChange(n) === false) setDraft(String(value)); };
  return <label className="gp-field">{label}<input type="number" aria-label={label} aria-invalid={!!error} value={draft} min={min} max={max} step={step} disabled={disabled} onChange={e => setDraft(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); commit(); } }} />{error && <small className="field-error" role="alert">{error}</small>}</label>;
}
function StageIssues({ issues }: { issues: string[] }) { return issues.length ? <div className="gs-issues" role="status"><strong>空间与时间检查</strong><ul>{issues.map(s => <li key={s}>{s}</li>)}</ul></div> : null; }
export function StageBoard({ space, selectedId, onCell, onObject, counts, label = '空间布局画布' }: { space: StageLayout; selectedId?: string; onCell?: (row: number, column: number) => void; onObject?: (id: string) => void; counts?: Map<string, number>; label?: string }) {
  const [zoom, setZoom] = useState(1); const prefix = useId().replace(/:/g, ''); const cell = 64, top = 36, width = (space.columns + 2) * cell + 28, height = space.rows * cell + top + 20;
  const object = space.objects.find(o => o.id === selectedId);
  const rect = (o: StageObject) => ({ x: stageColumn(o, space) * cell + 32, y: top + (o.row - 1) * cell + 4, width: (o.anchor === 'cell' ? o.width : 1) * cell - 8, height: (o.anchor === 'cell' ? o.height : 1) * cell - 8 });
  const coverage = () => { if (!object || object.rangeShape === 'none') return null; const b = rect(object), cx = b.x + b.width / 2, cy = b.y + b.height / 2, distance = object.range * cell, color = stageColors[object.color];
    if (object.rangeShape === 'radius') return <circle cx={cx} cy={cy} r={distance} fill={color + '25'} stroke={color} strokeDasharray="5 4" />;
    const x = object.direction === 'left' ? b.x - 4 - distance : object.direction === 'right' ? b.x + b.width + 4 : b.x - 4;
    const y = object.direction === 'up' ? b.y - 4 - distance : object.direction === 'down' ? b.y + b.height + 4 : b.y - 4;
    return <rect x={x} y={y} width={['left', 'right'].includes(object.direction) ? distance : b.width + 8} height={['up', 'down'].includes(object.direction) ? distance : b.height + 8} fill={color + '25'} stroke={color} strokeDasharray="5 4" />;
  };
  const interact = (action: () => void) => (e: KeyboardEvent) => { if (['Enter', ' '].includes(e.key)) { e.preventDefault(); action(); } };
  return <div className="st-board-shell"><div className="st-board-toolbar"><span>{space.rows} 行 × {space.columns} 列 · 每格 {space.cellSize} {space.unit || '单位'}</span><div className="gp-actions"><button className="gp-icon" aria-label="缩小布局" disabled={zoom <= .75} onClick={() => setZoom(z => z - .25)}>−</button><small>{Math.round(zoom * 100)}%</small><button className="gp-icon" aria-label="放大布局" disabled={zoom >= 2} onClick={() => setZoom(z => z + .25)}>+</button><button className="gp-icon" aria-label="重置布局缩放" onClick={() => setZoom(1)}><RotateCcw size={13} /></button></div></div>
    <div className="st-board-scroll"><svg role="group" aria-label={label} viewBox={`0 0 ${width} ${height}`} style={{ width: `${zoom * 100}%`, minWidth: 540 * zoom }}><defs><clipPath id={prefix + 'range'}><rect x={cell + 28} y={top} width={space.columns * cell} height={space.rows * cell} /></clipPath></defs>
      {Array.from({ length: space.columns }, (_, c) => <text key={c} className="st-grid-label" x={(c + 1.5) * cell + 28} y="23" textAnchor="middle">C{c + 1}</text>)}
      {Array.from({ length: space.rows }, (_, r) => <g key={r}><text className="st-grid-label" x="6" y={top + (r + .5) * cell + 4}>R{r + 1}</text>{Array.from({ length: space.columns }, (_, c) => <g role={onCell ? 'button' : undefined} tabIndex={onCell ? 0 : undefined} className="st-cell" key={c} aria-label={`格子 R${r + 1} C${c + 1}`} onClick={() => onCell?.(r + 1, c + 1)} onKeyDown={interact(() => onCell?.(r + 1, c + 1))}><rect x={(c + 1) * cell + 28} y={top + r * cell} width={cell} height={cell} fill={(r + c) % 2 ? '#24312c' : '#202b28'} stroke="#425249" strokeWidth=".7" /></g>)}</g>)}
      <g pointerEvents="none" clipPath={`url(#${prefix + 'range'})`}>{coverage()}</g>
      {space.objects.map(o => { const b = rect(o), color = stageColors[o.color], count = counts?.get(o.id) ?? 0; return <g key={o.id} role={onObject ? 'button' : undefined} tabIndex={onObject ? 0 : undefined} aria-label={'选择空间对象：' + (o.name || '未命名')} className={'st-object' + (selectedId === o.id ? ' selected' : '')} onClick={() => onObject?.(o.id)} onKeyDown={interact(() => onObject?.(o.id))}>
        <title>{o.name || '未命名'} · {stageKinds[o.kind]}{o.notes ? '\n' + o.notes : ''}{counts ? '\n累计到点数量：' + count : ''}</title><rect {...b} rx={o.kind === 'zone' ? 3 : 9} fill={color + (o.kind === 'zone' ? '20' : '38')} stroke={color} strokeWidth={selectedId === o.id || count ? 2.5 : 1} strokeDasharray={['zone', 'note'].includes(o.kind) ? '4 3' : undefined} />
        <text x={b.x + b.width / 2} y={b.y + 16} textAnchor="middle" fill={color} fontSize="9">{stageKinds[o.kind]} {o.rangeShape === 'none' ? '' : { left: '←', right: '→', up: '↑', down: '↓' }[o.direction]}</text><text x={b.x + b.width / 2} y={b.y + 34} textAnchor="middle" fill="#eee9f6" fontSize="10">{o.name.length > Math.max(5, o.width * 5) ? o.name.slice(0, Math.max(4, o.width * 5 - 1)) + '…' : o.name || '未命名'}</text>
        {!!count && <><circle cx={b.x + b.width - 11} cy={b.y + 1} r="11" fill="#d9b9ff" /><text x={b.x + b.width - 11} y={b.y + 5} fontSize={count > 999 ? 7 : 9} textAnchor="middle" fill="#251433">{count > 999 ? '999+' : count}</text></>}
      </g>; })}
    </svg></div></div>;
}
export function GameplaySpace({ design: d, designs, disabled, onChange, initialObjectId }: Common & { initialObjectId?: string }) {
  const s = d.space; const [selected, setSelected] = useState(initialObjectId ?? ''), [mode, setMode] = useState<'select' | 'place' | 'move'>('select'), [kind, setKind] = useState<StageObject['kind']>('actor'), [error, setError] = useState('');
  const o = s.objects.find(x => x.id === selected); const patch = (changes: Partial<StageLayout>) => { onChange({ space: { ...s, ...changes } }); setError(''); };
  const patchObject = (changes: Partial<StageObject>) => { if (o) patch({ objects: s.objects.map(x => x.id === o.id ? { ...x, ...changes } : x) }); };
  const cellClick = (row: number, column: number) => { if (disabled || mode === 'select') { const hit = [...s.objects].reverse().find(x => x.anchor === 'cell' && row >= x.row && row < x.row + x.height && column >= x.column && column < x.column + x.width); setSelected(hit?.id ?? ''); return; }
    if (mode === 'place') { if (s.objects.length >= 300) { setError('单个布局最多300个对象'); return; } const next = createStageObject(kind, row, column); next.name += ' ' + (s.objects.filter(x => x.kind === kind).length + 1); patch({ objects: [...s.objects, next] }); setSelected(next.id); }
    else if (o) { if (row + o.height - 1 > s.rows || column + o.width - 1 > s.columns) { setError('移动后超出格子边界，请选择可以容纳对象的位置'); return; } patchObject({ row, column, anchor: 'cell' }); setMode('select'); }
  };
  const selectObject = (id: string) => { const hit = s.objects.find(x => x.id === id); if (mode === 'place' && !disabled && hit?.anchor === 'cell') cellClick(hit.row, hit.column); else if (mode === 'move' && !disabled && hit?.anchor === 'cell') cellClick(hit.row, hit.column); else { setSelected(id); setMode('select'); } };
  const resize = (rows: number, columns: number) => { try { onChange({ space: resizeSpace(s, rows, columns) }); setError(''); return true; } catch (e) { setError((e as Error).message); return false; } };
  return <div className="gs-page st-page"><div className="gs-intro"><div><span className="gp-kicker">SPATIAL DESIGN</span><h3>空间布局</h3><p>摆放单位、障碍、入口与目标，查看占地、朝向和作用范围。</p></div><span className="st-summary">{s.objects.length} 个对象</span></div>
    <fieldset className="gs-fieldset" disabled={disabled}><div className="st-board-settings"><NumberField label="布局行数" value={s.rows} min={1} max={30} onChange={n => resize(n, s.columns)} /><NumberField label="布局列数" value={s.columns} min={1} max={40} onChange={n => resize(s.rows, n)} /><NumberField label="每格尺寸" value={s.cellSize} min={.001} max={10000} step={.1} onChange={n => patch({ cellSize: n })} /><label className="gp-field">长度单位<input aria-label="长度单位" value={s.unit} onChange={e => patch({ unit: e.target.value })} /></label></div></fieldset>
    <div className="st-tools"><button className="gp-secondary" aria-pressed={mode === 'select'} onClick={() => setMode('select')}><MousePointer2 size={14} />选择对象</button><select aria-label="放置对象类型" disabled={disabled} value={kind} onChange={e => { setKind(e.target.value as typeof kind); setMode('place'); }}>{Object.entries(stageKinds).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><button className="gp-secondary" aria-pressed={mode === 'place'} disabled={disabled} onClick={() => setMode('place')}><Plus size={14} />放置对象</button><button className="gp-secondary" aria-pressed={mode === 'move'} disabled={disabled || !o} onClick={() => setMode('move')}><Move size={14} />移动所选</button></div>
    <p className="st-help">{mode === 'place' ? '点击格子放置对象。允许多层标记；放置后可在属性中设置边界入口、名称和范围。' : mode === 'move' ? '点击目标格子移动所选对象，原位置会自动释放。' : '点击对象编辑属性，支持键盘 Enter / 空格选择。绿色格子仅表示布局，不代表已经制作完成。'}</p>
    {error && <p className="field-error" role="alert">{error}</p>}{s.description && <p className="st-layout-description">{s.description}</p>}<StageBoard space={s} selectedId={selected} onCell={cellClick} onObject={selectObject} />
    <StageIssues issues={stageIssues(d, designs).filter(x => x.includes('对象超出') || x.includes('空间对象尚未'))} />
    <div className="st-space-editors"><section className="gp-card"><div className="gp-card-heading"><h3>布局对象</h3><small>{s.objects.length} 个</small></div><div className="st-object-list">{s.objects.map(x => <button key={x.id} className={selected === x.id ? 'selected' : ''} aria-label={'编辑空间对象：' + (x.name || '未命名')} onClick={() => { setSelected(x.id); setMode('select'); }}><i style={{ background: stageColors[x.color] }} /><span>{x.name || '未命名'}</span><small>R{x.row} {x.anchor === 'cell' ? 'C' + x.column : x.anchor === 'left' ? '左边界' : '右边界'}</small></button>)}</div>{!s.objects.length && <p className="gp-muted">先选择一种对象，再点击画布格子放置。</p>}<fieldset disabled={disabled} className="gs-fieldset"><label className="gp-field">布局说明<textarea aria-label="布局说明" rows={4} value={s.description} onChange={e => patch({ description: e.target.value })} placeholder="说明坐标、通行、站位和边界约定。" /></label></fieldset></section>
      <section className="gp-card"><h3>对象属性</h3>{!o ? <p className="gp-muted">选择对象后设置名称、位置、占地和范围。</p> : <fieldset className="gs-fieldset" disabled={disabled}><div><label className="gp-field">对象名称<input aria-label="对象名称" value={o.name} onChange={e => patchObject({ name: e.target.value })} /></label><div className="gp-two-fields"><label className="gp-field">对象类型<select aria-label="对象类型" value={o.kind} onChange={e => patchObject({ kind: e.target.value as typeof o.kind })}>{Object.entries(stageKinds).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><ColorField label="对象颜色" value={o.color} onChange={color => patchObject({ color })} /></div>
      <label className="gp-field">对象锚点<select aria-label="对象锚点" value={o.anchor} onChange={e => patchObject({ anchor: e.target.value as typeof o.anchor, ...(e.target.value !== 'cell' ? { width: 1, height: 1 } : {}) })}><option value="cell">格子内部</option><option value="left">左侧边界外</option><option value="right">右侧边界外</option></select></label>
      <div className="gp-two-fields"><NumberField label="对象行" value={o.row} min={1} max={s.rows} onChange={row => patchObject({ row })} /><NumberField label="对象列" value={o.column} min={1} max={s.columns} disabled={o.anchor !== 'cell'} onChange={column => patchObject({ column })} /><NumberField label="占地宽度" value={o.width} min={1} max={s.columns} disabled={o.anchor !== 'cell'} onChange={width => patchObject({ width })} /><NumberField label="占地高度" value={o.height} min={1} max={s.rows} disabled={o.anchor !== 'cell'} onChange={height => patchObject({ height })} /></div>
      <div className="gp-two-fields"><label className="gp-field">对象朝向<select aria-label="对象朝向" value={o.direction} onChange={e => patchObject({ direction: e.target.value as typeof o.direction })}><option value="right">向右 →</option><option value="left">向左 ←</option><option value="up">向上 ↑</option><option value="down">向下 ↓</option></select></label><label className="gp-field">范围形状<select aria-label="范围形状" value={o.rangeShape} onChange={e => patchObject({ rangeShape: e.target.value as typeof o.rangeShape })}><option value="none">不显示范围</option><option value="line">直线范围</option><option value="radius">圆形半径</option></select></label></div><NumberField label="作用距离（格）" value={o.range} min={0} max={100} step={.1} disabled={o.rangeShape === 'none'} onChange={range => patchObject({ range })} />
      <label className="gp-field">对象说明<textarea aria-label="对象说明" rows={3} value={o.notes} onChange={e => patchObject({ notes: e.target.value })} /></label></div><div className="gp-actions"><button className="gp-secondary" disabled={s.objects.length >= 300} onClick={() => { const copy = { ...o, id: crypto.randomUUID(), name: o.name + ' · 副本' }; patch({ objects: [...s.objects, copy] }); setSelected(copy.id); setMode('move'); }}><Copy size={14} />复制空间对象</button><button className="gp-secondary gs-delete" onClick={() => { try { onChange({ space: removeStageObject(d, designs, o.id) }); setSelected(''); setError(''); } catch (e) { setError((e as Error).message); } }}><Trash2 size={14} />删除空间对象</button></div></fieldset>}</section></div>
  </div>;
}
function ColorField({ label, value, onChange }: { label: string; value: keyof typeof stageColors; onChange: (c: keyof typeof stageColors) => void }) { return <label className="gp-field">{label}<select aria-label={label} value={value} onChange={e => onChange(e.target.value as typeof value)}>{Object.keys(stageColors).map((c, i) => <option key={c} value={c}>{['绿色', '紫色', '蓝色', '黄色', '红色'][i]}</option>)}</select></label>; }
function TimelineBoard({ timeline: t, cursor, selected, onSelect, onCursor }: { timeline: GameplayTimeline; cursor: number; selected: string; onSelect: (id: string) => void; onCursor: (n: number) => void }) {
  const domain = Math.max(t.duration, timelineStats(t).last), plot = 800, left = 155, width = left + plot + 24;
  const lanes: ({ type: 'track'; id: string; name: string; color: string } | { type: 'event'; event: TimelineEvent; color: string })[] = t.tracks.flatMap(track => [{ type: 'track' as const, id: track.id, name: track.name, color: stageColors[track.color] }, ...t.events.filter(e => e.trackId === track.id).map(event => ({ type: 'event' as const, event, color: stageColors[track.color] }))]);
  const orphan = t.events.filter(e => !t.tracks.some(x => x.id === e.trackId)); if (orphan.length) lanes.push({ type: 'track', id: 'missing', name: '轨道已失效', color: '#df8b89' }, ...orphan.map(event => ({ type: 'event' as const, event, color: '#df8b89' })));
  const height = Math.max(150, 58 + lanes.length * 37), x = (seconds: number) => left + seconds / domain * plot;
  return <div className="st-time-chart"><div className="st-chart-caption"><span>事件时间轴 · 秒</span><span>圆点＝触发 · 色条＝持续 / 重复跨度</span></div><div className="st-time-scroll"><svg role="group" aria-label="事件时间轴" viewBox={`0 0 ${width} ${height}`} style={{ minWidth: 740, width: '100%' }}>
    {Array.from({ length: 7 }, (_, i) => <g key={i}><line x1={x(domain * i / 6)} x2={x(domain * i / 6)} y1="32" y2={height} stroke="#45354f" strokeDasharray="3 5" /><text x={x(domain * i / 6)} y="23" textAnchor="middle" fill="#b6a2ca" fontSize="11">{Math.round(domain * i / 6 * 10) / 10}s</text></g>)}
    {lanes.map((lane, index) => { const y = 55 + index * 37; if (lane.type === 'track') return <g key={'t' + lane.id}><rect x="0" y={y - 19} width={width} height="30" fill={lane.color + '16'} /><text x="15" y={y} fontSize="12" fontWeight="600" fill={lane.color}>{lane.name || '未命名轨道'}</text></g>;
      const e = lane.event, active = e.id === selected, span = Math.max(4, x(eventEnd(e)) - x(e.start)); return <g key={'e' + e.id} role="button" tabIndex={0} aria-label={'查看时间事件：' + (e.name || '未命名事件')} className="st-time-event" onClick={() => onSelect(e.id)} onKeyDown={ev => { if (['Enter', ' '].includes(ev.key)) { ev.preventDefault(); onSelect(e.id); } }}>
        <title>{e.name}：{e.start}s，{e.repeat}次，间隔{e.interval}s，每次{e.quantity}，持续{e.duration}s</title><rect x="0" y={y - 18} width={width} height="34" fill={active ? '#49325f70' : 'transparent'} /><text x="15" y={y + 3} fontSize="11" fill={active ? '#e8d1ff' : '#beafcb'}>{e.name.length > 13 ? e.name.slice(0, 12) + '…' : e.name || '未命名事件'}</text>
        <rect x={x(e.start)} y={y - 7} width={span} height="14" rx="4" fill={lane.color + '38'} stroke={active ? lane.color : 'none'} />
        {Array.from({ length: Math.min(e.repeat, 40) }, (_, i) => <g key={i}>{e.duration > 0 && <rect x={x(e.start + i * e.interval)} y={y - 6} width={Math.max(2, e.duration / domain * plot)} height="12" rx="3" fill={lane.color + '55'} />}<circle cx={x(e.start + i * e.interval)} cy={y} r={active ? 4.5 : 3.5} fill={lane.color} /></g>)}
        {e.repeat > 40 && <text x={Math.min(width - 55, x(eventLastStart(e)))} y={y + 4} fill={lane.color} fontSize="10">×{e.repeat}</text>}
      </g>; })}
    <line x1={x(cursor)} x2={x(cursor)} y1="30" y2={height} stroke="#f3d7a1" strokeWidth="2" pointerEvents="none" />
    <rect x={left} y="0" width={plot} height="31" fill="transparent" role="slider" tabIndex={0} aria-label="时间轴刻度游标" aria-valuemin={0} aria-valuemax={t.duration} aria-valuenow={cursor} onClick={e => { const box = e.currentTarget.getBoundingClientRect(); onCursor(Math.max(0, Math.min(t.duration, Math.round((e.clientX - box.left) / box.width * domain * 10) / 10))); }} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); onCursor(Math.min(t.duration, Math.max(0, cursor + (e.key === 'ArrowRight' ? 1 : -1)))); } }} />
  </svg></div></div>;
}
export function GameplayTime({ design: d, designs, disabled, onChange, onNavigate, initialEventId }: Common & { initialEventId?: string }) {
  const t = d.timeline, owner = spaceOwner(d, designs); const [trackId, setTrackId] = useState(t.events.find(e => e.id === initialEventId)?.trackId ?? ''), [eventId, setEventId] = useState(initialEventId ?? ''), [error, setError] = useState(''), [cursor, setCursor] = useState(0), [playing, setPlaying] = useState(false), [speed, setSpeed] = useState(10);
  const track = t.tracks.find(x => x.id === trackId) ?? t.tracks[0], event = t.events.find(e => e.id === eventId), frame = useRef(0);
  useEffect(() => { if (!playing) return; let before = performance.now(); const step = (now: number) => { const elapsed = (now - before) / 1000 * speed; before = now; setCursor(v => Math.min(t.duration, v + elapsed)); frame.current = requestAnimationFrame(step); }; frame.current = requestAnimationFrame(step); return () => cancelAnimationFrame(frame.current); }, [playing, speed, t.duration]);
  useEffect(() => { if (cursor >= t.duration) { setPlaying(false); if (cursor > t.duration) setCursor(t.duration); } }, [cursor, t.duration]);
  const patch = (changes: Partial<GameplayTimeline>) => { setPlaying(false); setError(''); onChange({ timeline: { ...t, ...changes } }); };
  const patchEvent = (changes: Partial<TimelineEvent>) => { if (event) patch({ events: t.events.map(e => e.id === event.id ? { ...e, ...changes } : e) }); };
  const seek = (n: number) => { setPlaying(false); setCursor(n); };
  const stats = timelineStats(t, cursor), buckets = timelineBuckets(t, Math.max(1, Math.ceil(Math.max(t.duration, stats.last) / 18 / 5) * 5)), maxBucket = Math.max(1, ...buckets.map(b => b.quantity));
  const counts = new Map<string, number>(); for (const e of t.events) if (e.objectId) counts.set(e.objectId, (counts.get(e.objectId) ?? 0) + dueOccurrences(e, cursor) * e.quantity);
  const selectEvent = (id: string) => { const found = t.events.find(e => e.id === id); setEventId(id); if (found) setTrackId(found.trackId); };
  return <div className="gs-page st-page"><div className="gs-intro"><div><span className="gp-kicker">TIME & SEQUENCE</span><h3>时间轴</h3><p>把波次、资源、阶段和提示放在同一个时钟下，检查发生时间与空间位置。</p></div><button className="gp-secondary" disabled={disabled || t.tracks.length >= 30} onClick={() => { const next = createTrack(); next.name = '轨道 ' + (t.tracks.length + 1); patch({ tracks: [...t.tracks, next] }); setTrackId(next.id); }}><Plus size={14} />添加时间轨道</button></div>
    <fieldset className="gs-fieldset" disabled={disabled}><div className="st-time-settings"><NumberField label="计划时长（秒）" value={t.duration} min={1} max={86400} step={.1} onChange={duration => patch({ duration })} /><label className="gp-field">计时基准<input aria-label="计时基准" value={t.clock} onChange={e => patch({ clock: e.target.value })} /></label><label className="gp-field">时间轴空间来源<select aria-label="时间轴空间来源" value={t.spaceOwnerId} onChange={e => { const oldOwner = owner?.id, nextId = e.target.value || d.id; if (oldOwner !== nextId && t.events.some(e => e.objectId)) { setError('已有事件关联空间对象，请先清除或调整这些位置关联，再更换空间来源'); return; } patch({ spaceOwnerId: e.target.value }); }}><option value="">本玩法空间布局</option>{t.spaceOwnerId && !designs.some(x => x.id === t.spaceOwnerId) && <option value={t.spaceOwnerId}>已失效的玩法</option>}{designs.filter(x => x.id !== d.id || x.id === t.spaceOwnerId).map(x => <option key={x.id} value={x.id}>{x.title || '未命名'}{x.archived ? '（已归档）' : ''}</option>)}</select></label></div></fieldset>
    {error && <p className="field-error" role="alert">{error}</p>}<StageIssues issues={stageIssues(d, designs)} />
    <div className="st-time-summary"><div><small>事件条目</small><strong>{t.events.length}</strong></div><div><small>计划触发</small><strong>{stats.occurrences}<small> 次</small></strong></div><div><small>计划数量</small><strong>{stats.quantity}</strong></div><div><small>最后事件结束</small><strong>{stats.last}<small> 秒</small></strong></div></div>
    <TimelineBoard timeline={t} cursor={cursor} selected={eventId} onSelect={selectEvent} onCursor={seek} />
    {event && <div className="gs-edge-detail" aria-label="选中时间事件详情"><strong>{event.name || '未命名事件'}</strong><p>{event.start} 秒开始 · 持续 {event.duration} 秒 · {event.repeat} 次 × {event.quantity} · 最后触发 {eventLastStart(event)} 秒</p><p>位置：{event.objectId ? owner?.space.objects.find(o => o.id === event.objectId)?.name || '关联已失效' : '未指定'} · 条件：{event.condition || '无附加条件'}</p><div className="gp-actions"><a className="gs-text-link" href="#st-time-editors">前往事件属性 ↓</a><button className="gp-secondary" onClick={() => seek(Math.min(t.duration, event.start))}>预览事件开始</button></div></div>}
    <section className="gp-card st-preview"><div className="gp-card-heading"><div><h3>时间预览</h3><p className="gp-muted">按时间计算计划触发；条件按满足处理，不模拟移动、战斗或存活数量。</p></div><div className="gp-actions"><button className="gp-secondary" onClick={() => { if (cursor >= t.duration) setCursor(0); setPlaying(v => !v); }}>{playing ? <Pause size={14} /> : <Play size={14} />}{playing ? '暂停时间预览' : '播放时间预览'}</button><button className="gp-icon" aria-label="重置时间预览" onClick={() => seek(0)}><RotateCcw size={14} /></button></div></div>
      <div className="st-scrubber"><output aria-label="当前预览时间">{cursor.toFixed(1)} s</output><input type="range" aria-label="预览时间游标" min="0" max={t.duration} step=".1" value={cursor} onChange={e => seek(Number(e.target.value))} /><select aria-label="预览速度" value={speed} onChange={e => setSpeed(Number(e.target.value))}>{[1, 2, 5, 10].map(n => <option key={n} value={n}>{n}×</option>)}</select></div>
      <div className="st-preview-facts"><span>累计到点 <strong aria-label="累计计划数量">{stats.dueQuantity}</strong> 个计划量 / {stats.due} 次触发</span><span>当前持续事件 <strong>{stats.active}</strong> 个</span></div>
      <div className="st-track-totals">{t.tracks.map(tr => { const events = t.events.filter(e => e.trackId === tr.id); return <span key={tr.id} style={{ borderColor: stageColors[tr.color] }}>{tr.name || '未命名'}：{events.reduce((n, e) => n + dueOccurrences(e, cursor) * e.quantity, 0)} / {events.reduce((n, e) => n + e.repeat * e.quantity, 0)}</span>; })}</div>
      <div className="st-density" aria-label="计划数量分布">{buckets.map((b, i) => <button key={i} title={`${b.start}–${b.end}秒：${b.quantity} 个计划量`} aria-label={`${b.start}至${b.end}秒计划数量 ${b.quantity}`} onClick={() => seek(Math.min(t.duration, b.start))}><span style={{ height: Math.max(3, b.quantity / maxBucket * 60) }} /><small>{b.start}s</small></button>)}</div><p className="gp-muted">柱状分布累加每次事件的数量，不代表难度或同时存活数量。</p>
      {owner && <><div className="gp-card-heading"><h3>空间联动 · {owner.title || '未命名玩法'}</h3>{owner.id !== d.id && <button className="gs-text-link" onClick={() => onNavigate(owner.id)}>前往来源玩法 →</button>}</div><p className="gp-muted">位置徽标显示截至当前时间的累计计划数量。选择事件可高亮它关联的位置。</p><StageBoard label="时间轴空间预览" space={owner.space} counts={counts} selectedId={event?.objectId} onObject={id => { const match = t.events.find(e => e.objectId === id); if (match) selectEvent(match.id); }} /></>}
    </section>
    <div className="st-time-editors" id="st-time-editors"><section className="gp-card"><h3>轨道与事件</h3><fieldset className="gs-fieldset" disabled={disabled}><div><label className="gp-field">编辑轨道<select aria-label="编辑轨道" value={track?.id ?? ''} onChange={e => setTrackId(e.target.value)}><option value="">请选择轨道</option>{t.tracks.map(tr => <option key={tr.id} value={tr.id}>{tr.name || '未命名'}</option>)}</select></label>{track && <><label className="gp-field">轨道名称<input aria-label="轨道名称" value={track.name} onChange={e => patch({ tracks: t.tracks.map(x => x.id === track.id ? { ...x, name: e.target.value } : x) })} /></label><ColorField label="轨道颜色" value={track.color} onChange={color => patch({ tracks: t.tracks.map(x => x.id === track.id ? { ...x, color } : x) })} /></>}</div><div className="gp-actions"><button className="gp-secondary" disabled={!track || t.events.length >= 200} onClick={() => { if (!track) return; const next = createTimelineEvent(track.id); next.name = '事件 ' + (t.events.length + 1); patch({ events: [...t.events, next] }); setEventId(next.id); }}><Plus size={14} />添加时间事件</button><button className="gp-secondary gs-delete" disabled={!track} onClick={() => { if (!track) return; if (t.events.some(e => e.trackId === track.id)) { setError('轨道还有事件，请先移动或删除这些事件'); return; } patch({ tracks: t.tracks.filter(x => x.id !== track.id) }); setTrackId(''); }}><Trash2 size={14} />删除时间轨道</button></div></fieldset>
      <div className="st-event-list">{t.events.filter(e => e.trackId === track?.id).map(e => <button key={e.id} aria-label={'编辑时间事件：' + (e.name || '未命名')} className={e.id === eventId ? 'selected' : ''} onClick={() => selectEvent(e.id)}><strong>{e.name || '未命名'}</strong><small>{e.start}s · {e.repeat} 次 × {e.quantity} · 末次 {eventLastStart(e)}s</small></button>)}</div>
    </section><section className="gp-card"><h3>事件属性</h3>{!event ? <p className="gp-muted">添加事件或点击时间轴上的事件进行编辑。</p> : <fieldset className="gs-fieldset" disabled={disabled}><div><label className="gp-field">事件名称<input aria-label="事件名称" value={event.name} onChange={e => patchEvent({ name: e.target.value })} /></label><label className="gp-field">所属轨道<select aria-label="所属轨道" value={event.trackId} onChange={e => { patchEvent({ trackId: e.target.value }); setTrackId(e.target.value); }}>{!t.tracks.some(tr => tr.id === event.trackId) && <option value={event.trackId}>轨道已失效</option>}{t.tracks.map(tr => <option key={tr.id} value={tr.id}>{tr.name || '未命名'}</option>)}</select></label><div className="gp-two-fields">
      <NumberField label="开始时间（秒）" value={event.start} min={0} max={86400} step={.1} onChange={start => patchEvent({ start })} /><NumberField label="持续时间（秒）" value={event.duration} min={0} max={86400} step={.1} onChange={duration => patchEvent({ duration })} /><NumberField label="重复次数" value={event.repeat} min={1} max={100} onChange={repeat => patchEvent({ repeat })} /><NumberField label="重复间隔（秒）" value={event.interval} min={0} max={86400} step={.1} onChange={interval => patchEvent({ interval })} /><NumberField label="每次数量" value={event.quantity} min={1} max={10000} onChange={quantity => patchEvent({ quantity })} /></div><p className="gp-muted">0 秒持续表示瞬时事件；0 秒间隔表示同一时刻触发多次。所有时间以当前计时基准为准。</p>
      <label className="gp-field">关联空间对象<select aria-label="关联空间对象" value={event.objectId} onChange={e => patchEvent({ objectId: e.target.value })}><option value="">不指定位置</option>{event.objectId && !owner?.space.objects.some(x => x.id === event.objectId) && <option value={event.objectId}>对象已失效</option>}{owner?.space.objects.map(o => <option key={o.id} value={o.id}>{o.name || '未命名'} · R{o.row} {o.anchor === 'cell' ? 'C' + o.column : o.anchor === 'left' ? '左边界' : '右边界'}</option>)}</select></label>
      <label className="gp-field">事件触发条件<textarea aria-label="事件触发条件" rows={2} value={event.condition} onChange={e => patchEvent({ condition: e.target.value })} placeholder="例如：游戏处于Running且本事件尚未执行" /></label><label className="gp-field">事件说明<textarea aria-label="事件说明" rows={3} value={event.notes} onChange={e => patchEvent({ notes: e.target.value })} placeholder="描述生成内容、提示或阶段行为。" /></label></div><div className="gp-actions"><button className="gp-secondary" disabled={t.events.length >= 200} onClick={() => { const copy = { ...event, id: crypto.randomUUID(), name: event.name + ' · 副本' }; patch({ events: [...t.events, copy] }); setEventId(copy.id); }}><Copy size={14} />复制时间事件</button><button className="gp-secondary gs-delete" onClick={() => { patch({ events: t.events.filter(e => e.id !== event.id) }); setEventId(''); }}><Trash2 size={14} />删除时间事件</button></div></fieldset>}</section></div>
  </div>;
}
