import { useRef, useState, type FormEvent } from 'react';
import { Folder, UserRound, Map, Swords, Compass, Gem, Settings2, BookOpen, ArrowUp, ArrowDown, Pencil, Trash2, X, Plus } from 'lucide-react';
import { categoryIcons, saveGameplayCategory, removeGameplayCategory, type GameplayCategory } from './gameplay-library';
import { moveGameplayItem } from './gameplay';
import type { GameplayController } from './useGameplayDesigns';
const icons = { folder: Folder, character: UserRound, map: Map, combat: Swords, exploration: Compass, growth: Gem, rules: Settings2, book: BookOpen };
export function CategoryIcon({ icon = 'folder', size = 24 }: { icon?: GameplayCategory['icon']; size?: number }) { const Icon = icons[icon]; return <Icon size={size} />; }
export function GameplayCategoryManager({ controller, onClose }: { controller: GameplayController; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement | null>(null), [id, setId] = useState(''), [name, setName] = useState(''), [description, setDescription] = useState(''), [icon, setIcon] = useState<GameplayCategory['icon']>('folder'), [error, setError] = useState('');
  const categories = controller.store.categories || [];
  const clear = () => { setId(''); setName(''); setDescription(''); setIcon('folder'); setError(''); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (controller.blocked) return; try { controller.update(s => saveGameplayCategory(s, { name, description, icon }, id || undefined)); clear(); } catch (e) { setError(String(e)); } };
  const remove = (category: GameplayCategory) => { if (!window.confirm('删除分类“' + category.name + '”？其中的文档将移入“未分类”，文档内容与关联都会保留。')) return; try { controller.update(s => removeGameplayCategory(s, category.id)); if (id === category.id) clear(); } catch (e) { setError(String(e)); } };
  return <dialog className="gp-dialog gl-category-dialog" aria-labelledby="gl-manager-title" ref={node => { dialog.current = node; if (node && !node.open) node.showModal(); }} onCancel={e => { e.preventDefault(); onClose(); }}>
    <div className="gp-card-heading"><div><span className="gp-kicker">DESIGN CATEGORIES</span><h2 id="gl-manager-title">管理玩法分类</h2></div><button type="button" className="gp-icon" aria-label="关闭分类管理" onClick={onClose}><X size={18} /></button></div>
    <p className="gp-muted">按找文档的习惯组织分类，可随时调整名称和顺序。</p>
    <div className="gl-category-manage-list">{categories.map((category, index) => <div key={category.id} className="gl-category-manage-row"><CategoryIcon icon={category.icon} size={17} /><strong>{category.name}</strong><small>{controller.store.designs.filter(d => d.categoryId === category.id).length} 篇</small><button className="gp-icon" aria-label={'上移分类：' + category.name} disabled={controller.blocked || index === 0} onClick={() => controller.update(s => ({ ...s, categories: moveGameplayItem(s.categories || [], index, -1) }))}><ArrowUp size={14} /></button><button className="gp-icon" aria-label={'下移分类：' + category.name} disabled={controller.blocked || index === categories.length - 1} onClick={() => controller.update(s => ({ ...s, categories: moveGameplayItem(s.categories || [], index, 1) }))}><ArrowDown size={14} /></button><button className="gp-icon" aria-label={'编辑分类：' + category.name} disabled={controller.blocked} onClick={() => { setId(category.id); setName(category.name); setDescription(category.description); setIcon(category.icon); setError(''); }}><Pencil size={14} /></button><button className="gp-icon" aria-label={'删除分类：' + category.name} disabled={controller.blocked} onClick={() => remove(category)}><Trash2 size={14} /></button></div>)}</div>
    <form onSubmit={submit}><fieldset disabled={controller.blocked}><h3>{id ? '编辑分类' : '新建分类'}</h3><label className="gp-field">分类名称<input required value={name} onChange={e => setName(e.target.value)} placeholder="例如：角色设计、地图探索" /></label><label className="gp-field">分类说明<textarea rows={2} value={description} onChange={e => setDescription(e.target.value)} placeholder="这里放哪些设计文档？" /></label><label className="gp-field">分类图标<select value={icon} onChange={e => setIcon(e.target.value as GameplayCategory['icon'])}>{Object.entries(categoryIcons).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{error && <p className="field-error" role="alert">{error}</p>}<div className="gp-dialog-actions">{id && <button className="gp-secondary" type="button" onClick={clear}>取消编辑</button>}<button className="primary" type="submit"><Plus size={15} />{id ? '保存分类' : '创建分类'}</button></div></fieldset></form>
  </dialog>;
}
export function GameplayTags({ tags, disabled, onChange }: { tags: string[]; disabled: boolean; onChange: (tags: string[]) => void }) {
  const [draft, setDraft] = useState(tags.join('，'));
  const save = () => { const next = [...new Set(draft.split(/[,，\n]/).map(t => t.trim()).filter(Boolean))]; if (JSON.stringify(next) !== JSON.stringify(tags)) onChange(next); setDraft(next.join('，')); };
  return <label className="gl-tags-field">标签<input aria-label="文档标签" disabled={disabled} value={draft} placeholder="用逗号分隔，如：战斗、成长" onChange={e => setDraft(e.target.value)} onBlur={save} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); save(); } }} /></label>;
}
