import {useSearchRequest} from './GlobalSearch';
import type { SpatialView } from './spatial-layout';
import { useEffect, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { Archive, ArrowDown, ArrowRight, ArrowUp, CheckCircle2, Copy, FileText, FlaskConical, Folder, Settings2, ChevronRight, Gamepad2, Link2, Plus, RotateCcw, Search, Trash2, X } from 'lucide-react';
import { createGameplay, duplicateGameplay, gameplayLinkName, gameplayResults, gameplayStatuses, moveGameplayItem, type GameplayDesign, type GameplayLink, type GameplaySources, type GameplayStatus } from './gameplay';
import type { GameplayController } from './useGameplayDesigns';
import './gameplay.css';
import './gameplay-library.css';
import { categoryOf, categoryName, gameplayMatches, moveGameplayDocuments } from './gameplay-library';
import { CategoryIcon, GameplayCategoryManager, GameplayTags } from './GameplayCategories';
import { GameplayDependencies, GameplayRules, GameplayStateFlow } from './GameplayStructure';
import { GameplaySpace, GameplayTime } from './GameplayStage';
type EditorTab = 'design' | 'relations' | 'rules' | 'flow' | 'space' | 'time';

type ImplementationProps = { readOnly?: boolean; team?: boolean; onRoomMove?: (designId:string,roomId:string,x:number,y:number)=>void; initialSpatialView?: SpatialView; objectReferences?: (designId: string, objectId: string) => string[]; renderImplementation?: (design: GameplayDesign) => ReactNode; initialSource?: { kind: string; id: string } };
const sourceTab = (kind?: string): EditorTab => kind === 'rule' ? 'rules' : kind === 'state' ? 'flow' : kind === 'event' ? 'time' : kind === 'object' ? 'space' : 'design';
type Props = ImplementationProps & { selectedId: string; onSelect: (id: string) => void; controller: GameplayController; sources: GameplaySources; onOpenLink: (link: GameplayLink) => void };
export function GameplayDesigns({ controller, selectedId, onSelect: setSelectedId, sources, onOpenLink, renderImplementation, initialSource, objectReferences, readOnly = false, team = false, onRoomMove }: Props) {
  const { store, blocked } = controller, editingBlocked = blocked || readOnly, update: GameplayController['update'] = operation => !editingBlocked && controller.update(operation), categories = store.categories || [];
  const selected = store.designs.find(d => d.id === selectedId);
  const [categoryId, setCategoryId] = useState<string | null>(() => selected ? categoryOf(selected, categories) : null);
  const [spatialNavigation, setSpatialNavigation] = useState<{ id: string; view?: SpatialView }>();
  const [editorTab, setEditorTab] = useState<EditorTab>(sourceTab(initialSource?.kind));
  const [query, setQuery] = useState(''), [scope, setScope] = useState('category'), [status, setStatus] = useState('all'), [archived, setArchived] = useState(!!selected?.archived);
  const [title, setTitle] = useState(''), [formError, setFormError] = useState(''), [managerOpen, setManagerOpen] = useState(false), [chosen, setChosen] = useState<string[]>([]), [moveTarget, setMoveTarget] = useState('');
  const dialog = useRef<HTMLDialogElement>(null), nameInput = useRef<HTMLInputElement>(null), newButton = useRef<HTMLButtonElement>(null), manageButton = useRef<HTMLButtonElement>(null);
  const currentCategory = categoryId === null ? null : categories.find(c => c.id === categoryId);
  const effectiveCategoryId = currentCategory?.id || '';
  const globalSearch = categoryId === null || (scope === 'all' && !!query.trim());
  const filtered = store.designs.filter(d => d.archived === archived && (status === 'all' || d.status === status) && gameplayMatches(d, query));
  const visible = filtered.filter(d => globalSearch || categoryOf(d, categories) === effectiveCategoryId);
  const overview = categoryId === null && !query.trim() && status === 'all' && !archived;
  const showEditor = !!selected && !globalSearch;
  const openDocument = (id: string, view?: SpatialView) => {
    const next = store.designs.find(d => d.id === id); if (!next) return;
    setSpatialNavigation(view ? { id, view } : undefined); setCategoryId(categoryOf(next, categories)); setArchived(next.archived); setStatus('all'); setQuery(''); setScope('category'); setChosen([]); setSelectedId(id); if (view) setEditorTab('space');
  };
  useEffect(() => {
    if (!selected) return;
    setCategoryId(categoryOf(selected, categories)); setArchived(selected.archived); setQuery(''); setStatus('all'); setChosen([]);
    if (initialSource) setEditorTab(sourceTab(initialSource.kind));
  }, [selectedId, initialSource, selected?.categoryId]);
  const searchRequest=useSearchRequest('玩法设计',t=>store.designs.some(d=>d.id===(t.parent||t.id)));
  useEffect(()=>{if(searchRequest){const id=searchRequest.parent||searchRequest.id;openDocument(id);setEditorTab(sourceTab(searchRequest.kind||'design'));}},[searchRequest]);
  const goHome = () => { setCategoryId(null); setSelectedId(''); setQuery(''); setStatus('all'); setArchived(false); setChosen([]); };
  const openCategory = (id: string) => { setCategoryId(id); setSelectedId(''); setQuery(''); setStatus('all'); setScope('category'); setChosen([]); };
  const addDesign = (design: GameplayDesign) => { if (!update(current => ({ ...current, designs: [...current.designs, design] }))) return; setCategoryId(categoryOf(design, categories)); setArchived(false); setStatus('all'); setQuery(''); setSelectedId(design.id); setEditorTab('design'); };
  const create = (event: FormEvent) => { event.preventDefault(); if (editingBlocked) return; try { addDesign({ ...createGameplay(title), categoryId: categoryId === null ? '' : effectiveCategoryId }); dialog.current?.close(); } catch (e) { setFormError(String(e)); } };
  const patch = (id: string, changes: Partial<GameplayDesign>) => update(current => ({ ...current, designs: current.designs.map(d => d.id === id ? { ...d, ...changes, updatedAt: new Date().toISOString() } : d) }));
  const openManager = () => { if (editingBlocked) return; setManagerOpen(true); setFormError(''); };
  const move = (ids: string[], target: string) => { try { update(s => moveGameplayDocuments(s, ids, target)); setChosen([]); setFormError(''); } catch (e) { setFormError(String(e)); } };
  const card = (id: string, name: string, description: string, icon: typeof categories[number]['icon'] = 'folder') => <button key={id} className="gl-category-card" aria-label={'进入分类：' + name} onClick={() => openCategory(id)}><span className="gl-category-top"><span className="gl-category-icon"><CategoryIcon icon={icon} /></span><small>{store.designs.filter(d => !d.archived && categoryOf(d, categories) === id).length} 篇文档</small></span><strong>{name}</strong><p>{description || '按主题整理详细玩法，集中查看相关文档。'}</p><span className="gl-category-enter">查看文档 <ArrowRight size={16} /></span></button>;
  return <section className="gp-workspace gl-workspace" aria-label="玩法设计工作区">
    <div className="gl-heading"><nav className="gl-breadcrumb" aria-label="玩法文档路径"><button onClick={goHome}><Folder size={16} />分类总览</button>{categoryId !== null && <><ChevronRight size={14} /><button onClick={() => openCategory(effectiveCategoryId)}>{currentCategory?.name || '未分类'}</button></>}{showEditor && <><ChevronRight size={14} /><span>{selected.title || '未命名玩法'}</span></>}</nav><div className="gp-actions"><button className="gp-secondary" ref={manageButton} disabled={editingBlocked} onClick={openManager}><Settings2 size={15} />管理分类</button><button className="primary" ref={newButton} aria-label="新建玩法" disabled={editingBlocked} onClick={() => { setTitle(''); setFormError(''); dialog.current?.showModal(); nameInput.current?.focus(); }}><Plus size={16} />新建文档</button></div></div>
    <div className="gl-toolbar"><label className="gp-search"><Search size={16} /><input type="search" aria-label="搜索玩法" value={query} onChange={e => { setQuery(e.target.value); setChosen([]); }} placeholder={categoryId === null || scope === 'all' ? '搜索全部文档、正文或标签…' : '搜索当前分类的文档…'} /></label>{categoryId !== null && <label>搜索范围<select aria-label="文档搜索范围" value={scope} onChange={e => setScope(e.target.value)}><option value="category">当前分类</option><option value="all">全部分类</option></select></label>}<label>设计状态<select aria-label="玩法状态筛选" value={status} onChange={e => { setStatus(e.target.value); setChosen([]); }}><option value="all">全部状态</option>{gameplayStatuses.map(s => <option key={s}>{s}</option>)}</select></label><label>显示范围<select aria-label="玩法范围" value={archived ? 'archived' : 'active'} onChange={e => { setArchived(e.target.value === 'archived'); setChosen([]); }}><option value="active">有效文档</option><option value="archived">已归档</option></select></label></div>
    {formError && !dialog.current?.open && <p className="gl-notice" role="alert">{formError}</p>}
    {blocked ? <div className="gp-empty" role="status"><FileText size={34} /><h2>玩法存档暂时无法读取</h2><p>请恢复存档后重新打开项目，现有内容未被覆盖。</p></div> : overview ? <>
      <div className="gl-intro"><div><span className="gp-kicker">GAMEPLAY LIBRARY</span><h2>按主题组织你的玩法设计</h2><p>从一个分类进入，找到体验目标、详细规则与设计文档。</p></div><span>{categories.length} 个分类 · {store.designs.filter(d => !d.archived).length} 篇文档</span></div>
      {(categories.length || store.designs.length) ? <div className="gl-category-grid">{categories.map(c => card(c.id, c.name, c.description, c.icon))}{store.designs.some(d => !categoryOf(d, categories)) && card('', '未分类', '尚未归类的文档保留在这里，可以随时移入合适的分类。')}<button disabled={editingBlocked} className="gl-add-category" onClick={openManager}><Plus size={25} /><strong>新建分类</strong><span>按照项目需要，自由划分设计主题</span></button></div> : <div className="gl-welcome"><span className="gl-category-icon"><FileText size={28} /></span><h2>设计你的第一个玩法</h2><p>先创建分类组织内容，也可以直接写下第一份设计文档。</p><div className="gp-actions"><button disabled={editingBlocked} className="primary" onClick={openManager}><Plus size={16} />新建分类</button><button disabled={editingBlocked} className="gp-secondary" onClick={() => newButton.current?.click()}>创建第一个玩法</button></div></div>}
    </> : <>
      {!showEditor && <div className="gl-section-heading"><div><h2>{globalSearch ? '全部文档' : currentCategory?.name || '未分类'}</h2><p>{globalSearch ? '搜索结果包含所属分类，可直接进入文档。' : currentCategory?.description || '在这里查看、创建和整理当前分类的文档。'}</p></div><span>{visible.length} 篇文档</span></div>}
      {showEditor ? <div className="gl-editor-layout"><div className="gp-library gl-document-nav"><div className="gp-library-heading"><h3>{currentCategory?.name || '未分类'}</h3><small>{visible.length}</small></div><div className="gp-list">{visible.map(d => <button key={d.id} className={'gp-list-card gl-document-link' + (selected.id === d.id ? ' selected' : '')} aria-label={'打开玩法：' + (d.title || '未命名玩法')} aria-pressed={selected.id === d.id} onClick={() => openDocument(d.id)}><strong>{d.title || '未命名玩法'}</strong><span>{d.status}</span></button>)}</div>{!visible.length && <p className="gp-muted">当前筛选下没有文档。</p>}<button className="gp-secondary" onClick={() => openCategory(effectiveCategoryId)}>查看分类全部文档</button></div><div className="gp-detail"><div className="gl-document-meta"><label>所属分类<select disabled={editingBlocked} aria-label="文档所属分类" value={categoryOf(selected, categories)} onChange={e => move([selected.id], e.target.value)}><option value="">未分类</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><GameplayTags key={selected.id} tags={selected.tags || []} disabled={selected.archived || editingBlocked} onChange={tags => patch(selected.id, { tags })} /></div><GameplayEditor readOnly={readOnly} team={team} onRoomMove={onRoomMove} initialSpatialView={spatialNavigation?.id === selected.id ? spatialNavigation.view : undefined} objectReferences={objectReferences} renderImplementation={renderImplementation} initialSource={initialSource} key={selected.id} design={selected} designs={store.designs} tab={editorTab} onTab={setEditorTab} onNavigate={openDocument} sources={sources} onChange={changes => patch(selected.id, changes)} onCopy={() => addDesign(duplicateGameplay(selected))} onArchive={() => { patch(selected.id, { archived: !selected.archived }); setArchived(!selected.archived); }} onOpenLink={onOpenLink} /></div></div> : <>
        {!!visible.length && <div className="gl-bulk-bar"><label><input type="checkbox" aria-label="选择当前结果全部文档" checked={visible.length > 0 && visible.every(d => chosen.includes(d.id))} onChange={e => setChosen(e.target.checked ? visible.map(d => d.id) : [])} />选择文档</label>{chosen.length > 0 && <><span>已选 {chosen.length} 篇</span><select aria-label="批量移动目标分类" value={moveTarget} onChange={e => setMoveTarget(e.target.value)}><option value="">未分类</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={editingBlocked} className="gp-secondary" onClick={() => move(chosen, moveTarget)}>移动所选文档</button></>}</div>}
        <div className="gl-document-grid">{visible.map(d => <article key={d.id} className="gl-document-card"><label className="gl-doc-check"><input type="checkbox" aria-label={'选择文档：' + d.title} checked={chosen.includes(d.id)} onChange={e => setChosen(ids => e.target.checked ? [...ids, d.id] : ids.filter(id => id !== d.id))} /></label><button className="gp-list-card" aria-label={'打开玩法：' + (d.title || '未命名玩法')} onClick={() => { openDocument(d.id); setEditorTab('design'); }}><span className="gl-document-path">{categoryName(d, categories)}</span><strong>{d.title || '未命名玩法'}</strong><p>{d.summary || '设计说明待补充'}</p><span className="gl-doc-bottom"><small className="gp-badge">{d.status}{d.archived ? ' · 已归档' : ''}</small>{d.tags?.length ? <small>{d.tags.join(' · ')}</small> : <FileText size={16} />}</span></button></article>)}</div>
        {!visible.length && <div className="gl-no-documents"><FileText size={30} /><h3>{query || status !== 'all' || archived ? '没有匹配的文档' : '这个分类还没有文档'}</h3><p>{query || status !== 'all' || archived ? '可以调整关键词或筛选条件。' : '新建一份文档，或把“未分类”中的文档移动到这里。'}</p><button disabled={editingBlocked} className="gp-secondary" onClick={() => newButton.current?.click()}><Plus size={15} />新建文档</button></div>}
      </>}
    </>}
    <dialog className="gp-dialog" ref={dialog} aria-labelledby="gp-new-title" onClose={() => newButton.current?.focus()}><form onSubmit={create}><div className="gp-card-heading"><div><span className="gp-kicker">NEW GAMEPLAY</span><h2 id="gp-new-title">新建玩法</h2></div><button type="button" className="gp-icon" aria-label="关闭新建玩法" onClick={() => dialog.current?.close()}><X size={19} /></button></div><p className="gp-muted">{categoryId === null ? '新文档会保存在“未分类”，之后可随时移动。' : '新文档将保存在当前分类。'}</p><label className="gp-field">玩法名称<input ref={nameInput} required value={title} onChange={e => { setTitle(e.target.value); setFormError(''); }} placeholder="例如：角色冲刺与空中控制" /></label>{formError && <p className="field-error" role="alert">{formError}</p>}<div className="gp-dialog-actions"><button type="button" className="gp-secondary" onClick={() => dialog.current?.close()}>取消</button><button className="primary" type="submit" disabled={editingBlocked}>创建玩法</button></div></form></dialog>
    {managerOpen && <GameplayCategoryManager controller={{...controller,blocked:editingBlocked}} onClose={() => { setManagerOpen(false); manageButton.current?.focus(); }} />}
  </section>;
}

function GameplayEditor({ design: d, designs, tab, onTab, onNavigate, sources, onChange, onCopy, onArchive, onOpenLink, renderImplementation, initialSource, objectReferences, initialSpatialView, readOnly = false, team = false, onRoomMove }: ImplementationProps & {
  design: GameplayDesign; designs: GameplayDesign[]; tab: EditorTab; onTab: (tab: EditorTab) => void; onNavigate: (id: string, view?: SpatialView) => void; sources: GameplaySources; onChange: (changes: Partial<GameplayDesign>) => void; onCopy: () => void; onArchive: () => void; onOpenLink: (link: GameplayLink) => void;
}) {
  const [linkKind, setLinkKind] = useState<GameplayLink['kind']>('story');
  const [targetId, setTargetId] = useState('');
  const choices = (linkKind === 'story' ? sources.stories.filter(s=>!s.sourceOnly).map(s => ({ id: s.id, name: s.title })) : sources.datasets.map(t => ({ id: t.key, name: t.label })))
    .filter(choice => !d.links.some(link => link.kind === linkKind && link.targetId === choice.id));
  const completed = d.prototype.filter(i => i.done).length;
  const passed = d.checks.filter(c => c.result === '通过').length;
  const progress = d.prototype.length ? Math.round(completed / d.prototype.length * 100) : 0;
  return <>
    <div className="gp-editor-heading"><div><span className="gp-kicker">GAMEPLAY DESIGN</span><h2>{d.title || '未命名玩法'}</h2><p className="gp-muted">最后编辑：{new Date(d.updatedAt).toLocaleString()}</p></div>
      <div className="gp-actions"><button disabled={readOnly} className="gp-secondary" onClick={onCopy}><Copy size={15} />复制玩法</button><button disabled={readOnly} className="gp-secondary" onClick={onArchive}>{d.archived ? <RotateCcw size={15} /> : <Archive size={15} />}{d.archived ? '恢复玩法' : '归档玩法'}</button></div></div>
    {d.archived && <p className="gp-archive-notice" role="status">此玩法已归档。恢复后可以继续编辑，也可以复制成新的方案。</p>}
    <div className="gp-structure-tabs" role="tablist" aria-label="玩法设计分页">{([['design', '设计说明', null], ['relations', '玩法关联', d.dependencies.length], ['rules', '条件规则', d.conditionRules.length], ['flow', '状态流程', d.stateFlow.states.length], ['space', '空间布局', d.space.objects.length], ['time', '时间轴', d.timeline.events.length]] as const).map(([id, name, count]) => <button role="tab" key={id} id={'gp-tab-' + id} aria-controls={'gp-panel-' + id} aria-selected={tab === id} tabIndex={tab === id ? 0 : -1} onKeyDown={e => { const ids: EditorTab[] = ['design', 'relations', 'rules', 'flow', 'space', 'time']; const index = ids.indexOf(tab); const next = e.key === 'ArrowRight' ? ids[(index + 1) % ids.length] : e.key === 'ArrowLeft' ? ids[(index + ids.length - 1) % ids.length] : e.key === 'Home' ? ids[0] : e.key === 'End' ? ids[ids.length - 1] : null; if (next) { e.preventDefault(); onTab(next); document.getElementById('gp-tab-' + next)?.focus(); } }} onClick={() => onTab(id)}>{name}{count !== null && <small>{count}</small>}</button>)}</div>
    <div className="gs-panel" role="tabpanel" id={'gp-panel-' + tab} aria-labelledby={'gp-tab-' + tab}>
    {tab === 'relations' && <GameplayDependencies design={d} designs={designs} disabled={d.archived || readOnly} onChange={onChange} onNavigate={onNavigate} />}
    {tab === 'rules' && <GameplayRules initialRuleId={initialSource?.kind === 'rule' ? initialSource.id : undefined} design={d} disabled={d.archived || readOnly} onChange={onChange} />}
    {tab === 'flow' && <GameplayStateFlow initialStateId={initialSource?.kind === 'state' ? initialSource.id : undefined} design={d} disabled={d.archived || readOnly} onChange={onChange} />}
    {tab === 'space' && <GameplaySpace personalView={team} onRoomMove={onRoomMove ? (id,x,y)=>onRoomMove(d.id,id,x,y) : undefined} initialView={initialSpatialView} objectReferences={objectReferences} initialObjectId={initialSource?.kind === 'object' ? initialSource.id : undefined} design={d} designs={designs} disabled={d.archived || readOnly} onChange={onChange} onNavigate={(id, view) => { onNavigate(id, view); onTab('space'); }} />}
    {tab === 'time' && <GameplayTime initialEventId={initialSource?.kind === 'event' ? initialSource.id : undefined} design={d} designs={designs} disabled={d.archived || readOnly} onChange={onChange} onNavigate={(id, view) => { onNavigate(id, view); onTab('space'); }} />}
    {tab === 'design' && <><div className="gp-stats"><div><span>原型制作</span><strong>{completed}<small> / {d.prototype.length}</small></strong><div className="gp-progress" aria-label={'制作完成 ' + progress + '%'}><span style={{ width: progress + '%' }} /></div></div>
      <div><span>试玩验证</span><strong>{passed}<small> / {d.checks.length} 通过</small></strong><p>制作完成后，仍需实际试玩验证。</p></div></div>
    {renderImplementation?.(d)}
    <fieldset className="gp-editor-fields" disabled={d.archived || readOnly}>
      <section className="gp-card"><div className="gp-card-heading"><h3>基本信息</h3><span className="gp-muted">可以逐步补充</span></div><div className="gp-two-fields">
        <label className="gp-field">玩法名称<input value={d.title} onChange={e => onChange({ title: e.target.value })} placeholder="为这个玩法起个名字" /></label>
        <label className="gp-field">设计状态<select aria-label="设计状态" value={d.status} onChange={e => onChange({ status: e.target.value as GameplayStatus })}>{gameplayStatuses.map(s => <option key={s}>{s}</option>)}</select></label></div>
        <label className="gp-field">一句话说明<textarea aria-label="一句话说明" rows={2} value={d.summary} onChange={e => onChange({ summary: e.target.value })} placeholder="玩家要做什么？例如：利用有限资源布置防御，抵挡一波敌人。" /></label>
        <label className="gp-field">体验目标<textarea aria-label="体验目标" rows={3} value={d.experience} onChange={e => onChange({ experience: e.target.value })} placeholder="希望玩家感受到什么？有哪些有意义的选择？" /></label></section>
      <section className="gp-card"><div className="gp-card-heading"><div><h3>核心循环</h3><p className="gp-muted">用连续步骤描述玩家的行动、反馈和下一步。</p></div><button className="gp-secondary" onClick={() => onChange({ loop: [...d.loop, { id: crypto.randomUUID(), text: '' }] })}><Plus size={15} />添加步骤</button></div>
        <ol className="gp-loop">{d.loop.map((step, index) => <li key={step.id}><span className="gp-step-number">{index + 1}</span><input aria-label={'循环步骤 ' + (index + 1)} value={step.text} onChange={e => onChange({ loop: d.loop.map(s => s.id === step.id ? { ...s, text: e.target.value } : s) })} placeholder="例如：探索并收集资源" />
          <button className="gp-icon" aria-label={'上移步骤 ' + (index + 1)} disabled={index === 0} onClick={() => onChange({ loop: moveGameplayItem(d.loop, index, -1) })}><ArrowUp size={15} /></button>
          <button className="gp-icon" aria-label={'下移步骤 ' + (index + 1)} disabled={index === d.loop.length - 1} onClick={() => onChange({ loop: moveGameplayItem(d.loop, index, 1) })}><ArrowDown size={15} /></button>
          <button className="gp-icon" aria-label={'删除步骤 ' + (index + 1)} onClick={() => onChange({ loop: d.loop.filter(s => s.id !== step.id) })}><Trash2 size={15} /></button></li>)}</ol>
        {!d.loop.length && <p className="gp-placeholder">还没有步骤。可以从玩家的第一个行动开始。</p>}</section>
      <section className="gp-card"><h3>玩法规则</h3><label className="gp-field">操作、条件与反馈<textarea aria-label="操作、条件与反馈" rows={5} value={d.rules} onChange={e => onChange({ rules: e.target.value })} placeholder="描述操作方式、触发条件、资源限制、奖励与例外情况。" /></label>
        <div className="gp-two-fields"><label className="gp-field">胜利条件<textarea aria-label="胜利条件" rows={2} value={d.winCondition} onChange={e => onChange({ winCondition: e.target.value })} placeholder="按玩法需要填写" /></label>
          <label className="gp-field">失败条件<textarea aria-label="失败条件" rows={2} value={d.loseCondition} onChange={e => onChange({ loseCondition: e.target.value })} placeholder="按玩法需要填写" /></label></div></section>
      <section className="gp-card"><div className="gp-card-heading"><div><h3>原型范围</h3><p className="gp-muted">这次只需要做出哪些内容，就能开始试玩？</p></div><button className="gp-secondary" onClick={() => onChange({ prototype: [...d.prototype, { id: crypto.randomUUID(), text: '', done: false }] })}><Plus size={15} />添加制作项</button></div>
        <ul className="gp-prototype">{d.prototype.map((item, index) => <li key={item.id}><input type="checkbox" aria-label={'完成制作项 ' + (index + 1)} checked={item.done} onChange={e => onChange({ prototype: d.prototype.map(i => i.id === item.id ? { ...i, done: e.target.checked } : i) })} />
          <input aria-label={'制作项 ' + (index + 1)} value={item.text} onChange={e => onChange({ prototype: d.prototype.map(i => i.id === item.id ? { ...i, text: e.target.value } : i) })} placeholder="例如：一种敌人、一把武器、一个测试场地" />
          <button className="gp-icon" aria-label={'删除制作项 ' + (index + 1)} onClick={() => onChange({ prototype: d.prototype.filter(i => i.id !== item.id) })}><Trash2 size={15} /></button></li>)}</ul>
        {!d.prototype.length && <p className="gp-placeholder">暂无制作项，先列出最少需要实现的内容。</p>}
        <label className="gp-field">暂缓内容<textarea aria-label="暂缓内容" rows={2} value={d.deferred} onChange={e => onChange({ deferred: e.target.value })} placeholder="例如：多种敌人、正式美术、完整成长系统，留待后续验证。" /></label></section>
      <section className="gp-card"><div className="gp-card-heading"><div><h3>验证清单</h3><p className="gp-muted">记录实际试玩的结果，再决定是否验证通过。</p></div><button className="gp-secondary" onClick={() => onChange({ checks: [...d.checks, { id: crypto.randomUUID(), question: '', steps: '', expected: '', actual: '', result: '未测试' }] })}><Plus size={15} />添加验证项</button></div>
        {!d.checks.length && <div className="gp-placeholder"><FlaskConical size={19} />还没有验证项。最想通过第一次试玩确认什么？</div>}
        <div className="gp-checks">{d.checks.map((check, index) => <section className="gp-check" key={check.id} aria-label={'验证项 ' + (index + 1)}><div className="gp-card-heading"><span className="gp-check-number"><FlaskConical size={16} />验证 {index + 1}</span><div className="gp-actions"><select aria-label={'验证结论 ' + (index + 1)} value={check.result} onChange={e => onChange({ checks: d.checks.map(c => c.id === check.id ? { ...c, result: e.target.value as typeof check.result } : c) })}>{gameplayResults.map(r => <option key={r}>{r}</option>)}</select>
          <button className="gp-icon" aria-label={'删除验证项 ' + (index + 1)} onClick={() => onChange({ checks: d.checks.filter(c => c.id !== check.id) })}><Trash2 size={15} /></button></div></div>
          {([['question', '要验证的问题', '例如：玩家能否在第一波敌人到来前理解防守目标？'], ['steps', '试玩步骤', '写下测试场景、初始条件和操作步骤。'], ['expected', '预期结果', '什么表现说明这个设计成立？'], ['actual', '实际结果', '试玩后记录观察到的表现、问题和下一次调整。']] as const).map(([key, label, placeholder]) => <label className="gp-field" key={key}>{label}<textarea aria-label={label} rows={key === 'question' ? 2 : 3} value={check[key]} placeholder={placeholder} onChange={e => onChange({ checks: d.checks.map(c => c.id === check.id ? { ...c, [key]: e.target.value } : c) })} /></label>)}</section>)}</div></section>
      <section className="gp-card"><h3>关联内容</h3><p className="gp-muted">连接当前项目的故事文档或配置表，方便从设计跳到具体内容。</p>
        <div className="gp-link-controls"><label className="gp-field">内容类型<select aria-label="内容类型" value={linkKind} onChange={e => { setLinkKind(e.target.value as GameplayLink['kind']); setTargetId(''); }}><option value="story">故事文档</option><option value="dataset" disabled={team}>配置表{team ? '（尚未接入协作）' : ''}</option></select></label>
          <label className="gp-field">关联目标<select aria-label="关联目标" value={targetId} onChange={e => setTargetId(e.target.value)}><option value="">{choices.length ? '选择关联内容' : '暂无可关联内容'}</option>{choices.map(c => <option key={c.id} value={c.id}>{c.name || '未命名'}</option>)}</select></label>
          <button className="gp-secondary" disabled={!choices.some(c => c.id === targetId)} onClick={() => { if (choices.some(c => c.id === targetId)) { onChange({ links: [...d.links, { kind: linkKind, targetId }] }); setTargetId(''); } }}><Link2 size={15} />添加关联</button></div>
        <ul className="gp-links">{d.links.map(link => { const name = gameplayLinkName(link, sources); return <li key={link.kind + ':' + link.targetId} className={name === undefined ? 'missing' : ''}>
          <span>{link.kind === 'story' ? '故事' : '配置表'}</span><button className="gp-link-name" disabled={name === undefined || (team && (link.kind==='dataset'||sources.stories.find(s=>s.id===link.targetId)?.sourceOnly))} onClick={() => onOpenLink(link)}>{name === undefined ? '关联已失效：' + link.targetId : name || '未命名'}</button>
          <button className="gp-icon" aria-label={'解除关联 ' + (name ?? link.targetId)} onClick={() => onChange({ links: d.links.filter(l => l.kind !== link.kind || l.targetId !== link.targetId) })}><X size={16} /></button></li>; })}</ul>
      </section>
    </fieldset>
    <p className="gp-editor-foot"><CheckCircle2 size={15} />设计状态由你手动决定，清单完成度仅用于记录进展。</p></>}
    </div>
  </>;
}
