import {useSearchSelection} from './GlobalSearch';
import { useState } from 'react';
import { ArrowRight, Plus, Trash2, ArrowUp, ArrowDown, Play, RotateCcw } from 'lucide-react';
import { moveGameplayItem, type GameplayDesign } from './gameplay';
import { GameplayGraph } from './GameplayGraph';
import { dependencyKinds, dependencyIssues, conditionOperators, conditionText, createRule, ruleIssues, createState, createTransition, stateFlowIssues, removeFlowState, type GameplayDependency, type GameplayRule, type GameplayFlow } from './gameplay-structure';
import './gameplay-structure.css';
function Issues({ items }: { items: string[] }) { return items.length ? <div className="gs-issues" role="status"><strong>设计检查 · {items.length} 项</strong><ul>{items.map((item, i) => <li key={i}>{item}</li>)}</ul></div> : null; }
export function GameplayDependencies({ design, designs, disabled, onChange, onNavigate }: { design: GameplayDesign; designs: GameplayDesign[]; disabled: boolean; onChange: (changes: Partial<GameplayDesign>) => void; onNavigate: (id: string) => void }) {
  const [target, setTarget] = useState(''), [kind, setKind] = useState<GameplayDependency['kind']>('depends'), [note, setNote] = useState(''), [error, setError] = useState('');
  const [selectedEdge, setSelectedEdge] = useState('');
  const choices = designs.filter(d => d.id !== design.id && !d.archived && !design.dependencies.some(e => e.targetId === d.id && e.kind === kind));
  const incoming = designs.flatMap(d => d.dependencies.filter(e => e.targetId === design.id).map(edge => ({ source: d, edge })));
  const edges = designs.flatMap(d => d.dependencies.map(e => ({ id: d.id + '/' + e.id, from: d.id, to: e.targetId, label: dependencyKinds[e.kind], tone: e.kind })));
  const edgeOwner = designs.find(d => d.dependencies.some(e => d.id + '/' + e.id === selectedEdge));
  const edgeInfo = edgeOwner?.dependencies.find(e => edgeOwner.id + '/' + e.id === selectedEdge);
  return <div className="gs-page">
    <div className="gs-intro"><div><span className="gp-kicker">SYSTEM RELATIONS</span><h3>玩法依赖关联</h3><p>箭头从当前玩法指向它依赖、包含或协作的玩法。点击节点可直接切换。</p></div><div className="gs-legend"><span>依赖</span><span>包含</span><span>协作</span></div></div>
    <GameplayGraph label="玩法关联图" nodes={designs.map(d => ({ id: d.id, label: d.title || '未命名玩法', tag: d.archived ? '已归档' : d.status, tone: d.archived ? 'archived' : '' }))} edges={edges} selectedNode={design.id} selectedEdge={selectedEdge} onNode={onNavigate} onEdge={setSelectedEdge} />
    {edgeInfo && edgeOwner && <div className="gs-edge-detail"><span>{edgeOwner.title} <ArrowRight size={13} /> {dependencyKinds[edgeInfo.kind]} <ArrowRight size={13} /> {designs.find(d => d.id === edgeInfo.targetId)?.title || '关联已失效'}</span><p>{edgeInfo.note || '暂无关系说明'}</p>{edgeOwner.id !== design.id && <button className="gp-secondary" onClick={() => onNavigate(edgeOwner.id)}>前往关系所属玩法</button>}</div>}
    <Issues items={dependencyIssues(design, designs)} />
    <section className="gp-card"><h3>当前玩法的关系</h3><fieldset disabled={disabled} className="gs-fieldset"><div className="gs-dependency-add">
      <label className="gp-field">关系类型<select aria-label="关系类型" value={kind} onChange={e => { setKind(e.target.value as typeof kind); setTarget(''); }}>{Object.entries(dependencyKinds).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>
      <label className="gp-field">目标玩法<select aria-label="目标玩法" value={target} onChange={e => setTarget(e.target.value)}><option value="">选择当前项目的其他玩法</option>{choices.map(d => <option key={d.id} value={d.id}>{d.title || '未命名玩法'}</option>)}</select></label>
      <label className="gp-field">关系说明<input aria-label="关系说明" value={note} onChange={e => setNote(e.target.value)} placeholder="例如：战斗需要种植模块提供植物实体" /></label>
      <button className="gp-secondary" disabled={!choices.some(d => d.id === target)} onClick={() => { if (!choices.some(d => d.id === target)) return; onChange({ dependencies: [...design.dependencies, { id: crypto.randomUUID(), targetId: target, kind, note }] }); setTarget(''); setNote(''); setError(''); }}><Plus size={15} />添加玩法关系</button></div>
      {error && <p className="field-error" role="alert">{error}</p>}
      <div className="gs-dependencies">{design.dependencies.map(edge => { const dest = designs.find(d => d.id === edge.targetId); return <div key={edge.id} className="gs-dependency" aria-label={'关系：' + (dest?.title || edge.targetId)}>
        <select aria-label={'关系类型 ' + (dest?.title || edge.targetId)} value={edge.kind} onChange={e => { const next = e.target.value as typeof edge.kind; if (design.dependencies.some(x => x.id !== edge.id && x.targetId === edge.targetId && x.kind === next)) { setError('已存在相同类型的关系'); return; } setError(''); onChange({ dependencies: design.dependencies.map(x => x.id === edge.id ? { ...x, kind: next } : x) }); }}>{Object.entries(dependencyKinds).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select>
        <button className="gs-text-link" disabled={!dest} onClick={() => dest && onNavigate(dest.id)}>{dest?.title || '关联已失效：' + edge.targetId}{dest?.archived ? '（已归档）' : ''}</button>
        <input aria-label={'关系说明 ' + (dest?.title || edge.targetId)} value={edge.note} onChange={e => onChange({ dependencies: design.dependencies.map(x => x.id === edge.id ? { ...x, note: e.target.value } : x) })} placeholder="说明两个玩法如何配合" />
        <button className="gp-icon" aria-label={'移除关系 ' + (dest?.title || edge.targetId)} onClick={() => onChange({ dependencies: design.dependencies.filter(x => x.id !== edge.id) })}><Trash2 size={15} /></button></div>; })}</div></fieldset>
      {!design.dependencies.length && <p className="gp-placeholder">暂无关系。先选择一个相关玩法，并说明它们的联系。</p>}</section>
    <section className="gp-card"><h3>哪些玩法引用了它</h3><div className="gs-incoming">{incoming.map(({ source, edge }) => <button className="gp-secondary" key={source.id + edge.id} onClick={() => onNavigate(source.id)}>{source.title || '未命名玩法'} <ArrowRight size={13} /> {dependencyKinds[edge.kind]}当前玩法{source.archived ? '（已归档）' : ''}</button>)}</div>{!incoming.length && <p className="gp-muted">暂无反向引用。</p>}</section>
  </div>;
}
export function GameplayRules({ design, disabled, onChange, initialRuleId }: { initialRuleId?: string; design: GameplayDesign; disabled: boolean; onChange: (changes: Partial<GameplayDesign>) => void }) {
  const [selectedId, locateSelected] = useState(initialRuleId ?? '');
  const setSelectedId=useSearchSelection('玩法设计',selectedId,locateSelected); const rule = design.conditionRules.find(r => r.id === selectedId) ?? design.conditionRules[0];
  const patch = (changes: Partial<GameplayRule>) => { if (rule) onChange({ conditionRules: design.conditionRules.map(r => r.id === rule.id ? { ...r, ...changes } : r) }); };
  return <div className="gs-page"><div className="gs-intro"><div><span className="gp-kicker">CONDITIONAL RULES</span><h3>条件规则</h3><p>将规则拆成触发事件、判断条件和两条结果分支。这里只描述设计，不运行游戏代码。</p></div><button className="gp-secondary" disabled={disabled} onClick={() => { const next = createRule(); onChange({ conditionRules: [...design.conditionRules, next] }); setSelectedId(next.id); }}><Plus size={15} />新建条件规则</button></div>
    <div className="gs-rule-list">{design.conditionRules.map((r, i) => <button key={r.id} className={'gs-rule-tab' + (r.id === rule?.id ? ' selected' : '')} aria-label={'打开规则：' + (r.name || '未命名规则 ' + (i + 1))} aria-pressed={r.id === rule?.id} onClick={() => setSelectedId(r.id)}><small>规则 {i + 1}</small><strong>{r.name || '未命名规则'}</strong><span>{r.conditions.length} 条条件 · {r.actions.length} 个满足动作</span></button>)}</div>
    {!rule ? <p className="gp-placeholder">例如：点击种植格时，检查游戏状态、阳光余额和格子占用，再决定扣费种植或提示原因。</p> : <>
      <div className="gs-rule-preview" aria-label="规则分支预览"><div className="gs-trigger"><small>当事件发生</small><strong>{rule.trigger || '待填写触发事件'}</strong></div><div className="gs-condition-preview"><small>{rule.mode === 'all' ? '全部条件满足 · AND' : '任一条件满足 · OR'}</small>{rule.conditions.length ? rule.conditions.map(c => <span key={c.id}>{conditionText(c)}</span>) : <span>{rule.mode === 'all' ? '无附加条件，直接进入满足分支' : '请添加至少一个条件'}</span>}</div><div className="gs-branches"><div className="yes"><small>满足 → 执行动作</small>{rule.actions.length ? rule.actions.map((a, i) => <span key={a.id}>{i + 1}. {a.text || '待填动作'}</span>) : <span>待填写</span>}</div><div className="no"><small>不满足 → 执行动作</small>{rule.otherwise.length ? rule.otherwise.map((a, i) => <span key={a.id}>{i + 1}. {a.text || '待填动作'}</span>) : <span>不执行动作</span>}</div></div></div>
      <Issues items={ruleIssues(rule)} />
      <fieldset className="gs-fieldset" disabled={disabled}><section className="gp-card"><div className="gp-card-heading"><h3>编辑规则</h3><div className="gp-actions">
        <button className="gp-icon" aria-label="上移当前规则" disabled={design.conditionRules.indexOf(rule) === 0} onClick={() => onChange({ conditionRules: moveGameplayItem(design.conditionRules, design.conditionRules.indexOf(rule), -1) })}><ArrowUp size={15} /></button>
        <button className="gp-icon" aria-label="下移当前规则" disabled={design.conditionRules.indexOf(rule) === design.conditionRules.length - 1} onClick={() => onChange({ conditionRules: moveGameplayItem(design.conditionRules, design.conditionRules.indexOf(rule), 1) })}><ArrowDown size={15} /></button>
        <button className="gp-secondary" onClick={() => onChange({ conditionRules: design.conditionRules.filter(r => r.id !== rule.id) })}><Trash2 size={15} />删除当前规则</button></div></div>
        <label className="gp-field">规则名称<input aria-label="规则名称" value={rule.name} onChange={e => patch({ name: e.target.value })} placeholder="例如：检查并完成种植" /></label>
        <label className="gp-field">触发事件<input aria-label="触发事件" value={rule.trigger} onChange={e => patch({ trigger: e.target.value })} placeholder="例如：玩家左键点击棋盘格" /></label>
        <div className="gs-condition-heading"><label className="gp-field">条件组合<select aria-label="条件组合" value={rule.mode} onChange={e => patch({ mode: e.target.value as typeof rule.mode })}><option value="all">全部满足（AND）</option><option value="any">任一满足（OR）</option></select></label><button className="gp-secondary" onClick={() => patch({ conditions: [...rule.conditions, { id: crypto.randomUUID(), subject: '', operator: 'eq', value: '' }] })}><Plus size={15} />添加判断条件</button></div>
        <div className="gs-conditions">{rule.conditions.map((c, i) => <div key={c.id}><span>{i + 1}</span><input aria-label={'条件对象 ' + (i + 1)} value={c.subject} onChange={e => patch({ conditions: rule.conditions.map(x => x.id === c.id ? { ...x, subject: e.target.value } : x) })} placeholder="例如：阳光余额" />
          <select aria-label={'条件运算 ' + (i + 1)} value={c.operator} onChange={e => patch({ conditions: rule.conditions.map(x => x.id === c.id ? { ...x, operator: e.target.value as typeof c.operator } : x) })}>{Object.entries(conditionOperators).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select>
          <input aria-label={'条件比较值 ' + (i + 1)} disabled={['exists', 'missing'].includes(c.operator)} value={c.value} onChange={e => patch({ conditions: rule.conditions.map(x => x.id === c.id ? { ...x, value: e.target.value } : x) })} placeholder={['exists', 'missing'].includes(c.operator) ? '无需比较值' : '例如：植物成本'} /><button className="gp-icon" aria-label={'删除判断条件 ' + (i + 1)} onClick={() => patch({ conditions: rule.conditions.filter(x => x.id !== c.id) })}><Trash2 size={15} /></button></div>)}</div>
        <p className="gp-muted">对象和比较值可以使用设计概念或参数名称。动作按列表顺序描述；零个“全部满足”条件表示无附加条件。</p>
      </section><div className="gs-action-columns">{(['actions', 'otherwise'] as const).map(key => <section className={'gp-card ' + (key === 'actions' ? 'gs-yes-card' : 'gs-no-card')} key={key} aria-label={key === 'actions' ? '满足条件的动作' : '不满足条件的动作'}><div className="gp-card-heading"><h3>{key === 'actions' ? '满足时' : '不满足时'}</h3><button className="gp-secondary" onClick={() => patch({ [key]: [...rule[key], { id: crypto.randomUUID(), text: '' }] })}><Plus size={15} />{key === 'actions' ? '添加满足动作' : '添加否则动作'}</button></div>
        <div className="gs-action-list">{rule[key].map((a, i) => <div key={a.id}><label className="gp-field">动作 {i + 1}<textarea rows={2} aria-label={(key === 'actions' ? '满足动作 ' : '否则动作 ') + (i + 1)} value={a.text} onChange={e => patch({ [key]: rule[key].map(x => x.id === a.id ? { ...x, text: e.target.value } : x) })} /></label><div className="gp-actions"><button className="gp-icon" aria-label={(key === 'actions' ? '上移满足动作 ' : '上移否则动作 ') + (i + 1)} disabled={!i} onClick={() => patch({ [key]: moveGameplayItem(rule[key], i, -1) })}><ArrowUp size={14} /></button><button className="gp-icon" aria-label={(key === 'actions' ? '删除满足动作 ' : '删除否则动作 ') + (i + 1)} onClick={() => patch({ [key]: rule[key].filter(x => x.id !== a.id) })}><Trash2 size={14} /></button></div></div>)}</div>
        {!rule[key].length && <p className="gp-muted">{key === 'actions' ? '添加需要执行的动作。' : '没有动作时保持原状。'}</p>}</section>)}</div></fieldset>
    </>}
  </div>;
}
export function GameplayStateFlow({ design, disabled, onChange, initialStateId }: { initialStateId?: string; design: GameplayDesign; disabled: boolean; onChange: (changes: Partial<GameplayDesign>) => void }) {
  const flow = design.stateFlow;
  const [nodeId, locateNode] = useState(initialStateId ?? ''), [edgeId, locateEdge] = useState(''), [error, setError] = useState('');
  const setNodeId=useSearchSelection('玩法设计',nodeId,locateNode),setEdgeId=useSearchSelection('玩法设计',edgeId,locateEdge);
  const [preview, setPreview] = useState(false), [currentId, setCurrentId] = useState(''), [trace, setTrace] = useState<string[]>([]);
  const node = flow.states.find(s => s.id === nodeId) ?? flow.states[0], edge = flow.transitions.find(t => t.id === edgeId) ?? flow.transitions[0];
  const patch = (changes: Partial<GameplayFlow>) => { onChange({ stateFlow: { ...flow, ...changes } }); setError(''); setPreview(false); };
  const current = flow.states.find(s => s.id === currentId); const name = (id: string) => flow.states.find(s => s.id === id)?.name || '未选择/已失效';
  const options = (id: string) => <><option value="">请选择状态</option>{id && !flow.states.some(s => s.id === id) && <option value={id}>已失效：{id}</option>}{flow.states.map(s => <option key={s.id} value={s.id}>{s.name || '未命名状态'}</option>)}</>;
  return <div className="gs-page"><div className="gs-intro"><div><span className="gp-kicker">STATE FLOW</span><h3>状态流程</h3><p>用状态节点和带条件的转移描述流程。结算状态也可以通过“重开”回到起点。</p></div><div className="gp-actions"><button className="gp-secondary" disabled={disabled} onClick={() => { const next = createState(); patch({ states: [...flow.states, next], initialStateId: flow.states.length ? flow.initialStateId : next.id }); setNodeId(next.id); }}><Plus size={15} />添加状态</button><button className="gp-secondary" disabled={disabled || !flow.states.length} onClick={() => { const next = { ...createTransition(), fromId: node?.id ?? '' }; patch({ transitions: [...flow.transitions, next] }); setEdgeId(next.id); }}><Plus size={15} />添加转移</button></div></div>
    <GameplayGraph label="状态流程图" nodes={flow.states.map(s => ({ id: s.id, label: s.name || '未命名状态', tag: s.id === flow.initialStateId ? '起始状态' : s.kind === 'outcome' ? '结算状态' : '状态', tone: s.kind, description: s.description }))} edges={flow.transitions.map(t => ({ id: t.id, from: t.fromId, to: t.toId, label: t.event, tone: 'flow' }))} rootId={flow.initialStateId} selectedNode={preview ? currentId : node?.id} selectedEdge={preview ? trace[trace.length - 1] : edgeId} onNode={id => { setNodeId(id); setEdgeId(''); }} onEdge={setEdgeId} />
    {edgeId && edge && <div className="gs-edge-detail" aria-label="选中转移详情"><span><strong>{name(edge.fromId)} → {name(edge.toId)}</strong> · {edge.event || '未命名事件'} · 优先级 {edge.priority}</span><p>条件：{edge.condition || '无附加条件'}</p><p>动作：{edge.action || '无附加动作'}</p><a className="gs-text-link" href="#gs-transition-editor">前往编辑这条转移 ↓</a></div>}
    <Issues items={stateFlowIssues(flow)} />
    <section className="gp-card gs-preview"><div className="gp-card-heading"><div><h3>手动路径预览</h3><p className="gp-muted">由你选择满足条件的转移，仅检查设计路径，不执行条件、动作或游戏逻辑。</p></div><button className="gp-secondary" disabled={!flow.states.some(s => s.id === flow.initialStateId)} onClick={() => { setPreview(true); setCurrentId(flow.initialStateId); setTrace([]); }}><Play size={15} />{preview ? '重新预览' : '开始路径预览'}</button></div>
      {preview && current && <><p className="gs-preview-current">当前状态：<strong>{current.name || '未命名状态'}</strong></p><div className="gs-preview-path">{[flow.initialStateId, ...trace.map(id => flow.transitions.find(t => t.id === id)?.toId ?? '')].map((id, i) => <span key={i}>{i > 0 && <ArrowRight size={13} />}{name(id)}</span>)}</div>
        <div className="gs-preview-choices">{flow.transitions.filter(t => t.fromId === current.id && flow.states.some(s => s.id === t.toId)).sort((a, b) => a.priority - b.priority).map(t => <button key={t.id} className="gp-secondary" aria-label={'预览转移：' + (t.event || '未命名事件') + ' → ' + name(t.toId)} onClick={() => { setCurrentId(t.toId); setTrace(old => [...old, t.id]); }}><strong>{t.event || '未命名事件'} → {name(t.toId)}</strong><small>条件：{t.condition || '无附加条件'} · 优先级 {t.priority}</small><small>动作：{t.action || '无附加动作'}</small></button>)}</div>
        {!flow.transitions.some(t => t.fromId === current.id && flow.states.some(s => s.id === t.toId)) && <p className="gp-muted">此状态没有有效的后续转移。</p>}
        {!!trace.length && <button className="gs-text-link" onClick={() => { const next = trace.slice(0, -1); setTrace(next); setCurrentId(next.length ? flow.transitions.find(t => t.id === next[next.length - 1])!.toId : flow.initialStateId); }}><RotateCcw size={14} />返回上一步</button>}</>}
    </section>
    <fieldset className="gs-fieldset" disabled={disabled}><div className="gs-flow-editors"><section className="gp-card"><div className="gp-card-heading"><h3>状态节点</h3><small>{flow.states.length} 个</small></div><label className="gp-field">起始状态<select aria-label="起始状态" value={flow.initialStateId} onChange={e => patch({ initialStateId: e.target.value })}>{options(flow.initialStateId)}</select></label>
      <label className="gp-field">编辑状态<select aria-label="编辑状态" value={node?.id ?? ''} onChange={e => setNodeId(e.target.value)}>{options(node?.id ?? '')}</select></label>
      {node && <><label className="gp-field">状态名称<input aria-label="状态名称" value={node.name} onChange={e => patch({ states: flow.states.map(s => s.id === node.id ? { ...s, name: e.target.value } : s) })} placeholder="例如：Running / 战斗中" /></label>
        <label className="gp-field">状态类型<select aria-label="状态类型" value={node.kind} onChange={e => patch({ states: flow.states.map(s => s.id === node.id ? { ...s, kind: e.target.value as typeof s.kind } : s) })}><option value="normal">普通状态</option><option value="outcome">结算状态</option></select></label>
        <label className="gp-field">状态说明<textarea aria-label="状态说明" rows={3} value={node.description} onChange={e => patch({ states: flow.states.map(s => s.id === node.id ? { ...s, description: e.target.value } : s) })} placeholder="说明这个状态允许的操作、进入/离开行为。" /></label>
        <button className="gp-secondary gs-delete" onClick={() => { try { onChange({ stateFlow: removeFlowState(flow, node.id) }); setError(''); setPreview(false); } catch (e) { setError(String(e)); } }}><Trash2 size={14} />删除当前状态</button></>}
      {error && <p className="field-error" role="alert">{error}</p>}</section>
      <section className="gp-card" id="gs-transition-editor"><div className="gp-card-heading"><h3>状态转移</h3><small>{flow.transitions.length} 条</small></div><label className="gp-field">编辑转移<select aria-label="编辑转移" value={edge?.id ?? ''} onChange={e => setEdgeId(e.target.value)}><option value="">请选择转移</option>{flow.transitions.map((t, i) => <option key={t.id} value={t.id}>{i + 1}. {name(t.fromId)} → {name(t.toId)} · {t.event || '未命名事件'}</option>)}</select></label>
        {edge && <>{(['fromId', 'toId'] as const).map((key, i) => <label className="gp-field" key={key}>{i ? '目标状态' : '来源状态'}<select aria-label={i ? '目标状态' : '来源状态'} value={edge[key]} onChange={e => patch({ transitions: flow.transitions.map(t => t.id === edge.id ? { ...t, [key]: e.target.value } : t) })}>{options(edge[key])}</select></label>)}
          {([['event', '转移事件'], ['condition', '转移条件'], ['action', '转移动作']] as const).map(([key, label]) => <label className="gp-field" key={key}>{label}<textarea aria-label={label} rows={2} value={edge[key]} onChange={e => patch({ transitions: flow.transitions.map(t => t.id === edge.id ? { ...t, [key]: e.target.value } : t) })} placeholder={key === 'event' ? '例如：按下 Esc' : key === 'condition' ? '留空表示无附加条件' : '例如：冻结所有战斗计时器'} /></label>)}
          <label className="gp-field">判断优先级<input type="number" min="0" step="1" aria-label="判断优先级" value={edge.priority} onChange={e => { const n = Number(e.target.value); if (Number.isInteger(n) && n >= 0) patch({ transitions: flow.transitions.map(t => t.id === edge.id ? { ...t, priority: n } : t) }); }} /><small>数值越小越先判断，相同时按转移列表顺序。</small></label>
          <button className="gp-secondary gs-delete" onClick={() => patch({ transitions: flow.transitions.filter(t => t.id !== edge.id) })}><Trash2 size={14} />删除当前转移</button></>}
      </section></div></fieldset>
  </div>;
}
