import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Copy,Plug,RefreshCw} from 'lucide-react';
import './mcp-connections.css';
type Connection={id:string;name:string;projectId:string;memberId:string;credentialId:string;enabled:boolean;projectName?:string;projectDirectory?:string;engineDirectory?:string;memberName?:string;roles?:string[];permissions?:string[];status:string;error:string};
type Session={id:string;name:string;code:string;connectionIds:string[];revoked:boolean;online:boolean;lastSeen:string|null;createdAt:string};
type Status={enabled:boolean;version:string;endpoint:string;inFlight:number;config:{json:string;toml:string};projects:{id:string;name:string;folderPath:string;engineDirectory:string;members:{id:string;name:string;credentialId:string;available:boolean;error:string}[];error:string}[];connections:Connection[];sessions:Session[];events:{id:string;at:string;clientName:string;connectionName:string;tool:string;status:string;error?:string}[]};
export type McpConnectionsAPI=(operation:string,input?:Record<string,unknown>)=>Promise<Status>;
const stateLabel:Record<string,string>={available:'可用',disabled:'已停用',unavailable:'不可用',running:'执行中',succeeded:'成功',failed:'失败'};
function SessionCard({session,connections,busy,run}:{session:Session;connections:Connection[];busy:boolean;run:(operation:string,input:Record<string,unknown>)=>Promise<boolean>}){
 const [selected,setSelected]=useState(session.connectionIds),[editing,setEditing]=useState(false);
 useEffect(()=>{if(!editing)setSelected(session.connectionIds);},[session.connectionIds.join(','),editing]);
 return <article className="mcp-card"><div className="mcp-row"><h3>{session.name}</h3><span>{session.revoked?'已撤销':session.online?'会话在线':'会话离线'}</span></div><p>接入码 <strong className="mcp-code">{session.code}</strong></p><p className="mcp-muted">在助手返回的 gc_connections 结果中核对接入码，再选择本会话可用的身份。</p>
 <fieldset disabled={busy||session.revoked}><legend>授权连接（可多选）</legend>{connections.length?connections.map(c=><label key={c.id} className="mcp-check"><input type="checkbox" checked={selected.includes(c.id)} disabled={!c.enabled||c.status!=='available'} onChange={e=>{setEditing(true);setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id));}}/>{c.name} · {c.memberName||'身份不可用'}</label>):<p>先添加项目与身份连接。</p>}</fieldset>
 <p className="mcp-muted">已授权 {session.connectionIds.length} 个连接 · 最近活动：{session.lastSeen?new Date(session.lastSeen).toLocaleString():'本次启动尚无活动'}</p>
 <div className="mcp-actions">{!session.revoked&&<><button disabled={busy} onClick={()=>void run('session',{id:session.id,connectionIds:selected}).then(ok=>{if(ok)setEditing(false);})}>保存会话授权</button><button disabled={busy} onClick={()=>void run('session',{id:session.id,revoke:true})}>撤销会话</button></>}{session.revoked&&<button disabled={busy} onClick={()=>void run('remove-session',{id:session.id})}>删除记录</button>}</div></article>;
}
export function McpConnections({onBack}:{onBack:()=>void}){
 const api=window.desktopClient?.mcpConnections,[status,setStatus]=useState<Status>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [tab,setTab]=useState('连接管理'),[projectId,setProjectId]=useState(''),[credentialId,setCredentialId]=useState(''),[name,setName]=useState(''),[format,setFormat]=useState<'toml'|'json'>('toml');
 const mounted=useRef(true),inFlight=useRef(false),sequence=useRef(0);
 useEffect(()=>{mounted.current=true;let timer:number;const refresh=async()=>{if(api&&!inFlight.current){const revision=++sequence.current;try{const next=await api('status');if(mounted.current&&sequence.current===revision)setStatus(next);}catch(e){if(mounted.current)setError((e as Error).message);}}if(mounted.current)timer=window.setTimeout(refresh,3000);};void refresh();return()=>{mounted.current=false;window.clearTimeout(timer);};},[api]);
 async function run(operation:string,input:Record<string,unknown>={}){if(!api||inFlight.current)return false;inFlight.current=true;++sequence.current;setBusy(true);setError('');setNotice('');try{const next=await api(operation,input);if(mounted.current){setStatus(next);setNotice(operation==='status'?'状态已刷新':'设置已保存');}return true;}catch(e){if(mounted.current)setError((e as Error).message);return false;}finally{inFlight.current=false;if(mounted.current)setBusy(false);}}
 const project=status?.projects.find(p=>p.id===projectId),member=project?.members.find(m=>m.credentialId===credentialId);
 return <main className="mcp-page" aria-label="MCP 连接"><header className="mcp-row"><div><div className="crumb">本机管理 / AI 工作流</div><h1>MCP 连接</h1></div><button onClick={onBack}><ArrowLeft size={16}/>返回工作区</button></header><p>统一接入 GameCreator，为每个助手会话授权项目与开发者身份。切换当前项目不会改变工具的操作目标。</p>
 {!api?<p role="alert">请使用桌面客户端管理 MCP 连接。</p>:<><section className="mcp-card"><div className="mcp-row"><h2><Plug size={22}/>软件级 MCP 服务</h2><strong className={status?.enabled?'mcp-online':''}>{status?status.enabled?'服务运行中':'服务已停止':'正在检查…'}</strong></div><p>适配器 {status?.version||'—'} · {status?.connections.length||0} 个连接 · {status?.sessions.filter(s=>s.online&&!s.revoked).length||0} 个在线会话</p><div className="mcp-actions"><button disabled={busy||!status} onClick={()=>void run('enabled',{enabled:!status?.enabled})}>{status?.enabled?'停止接入':'启动接入'}</button><button disabled={busy} onClick={()=>void run('status')}><RefreshCw size={16}/>刷新状态</button></div><p className="mcp-muted">停止接入会拒绝新操作，已开始的写入可能继续收尾。旧版逐项目 MCP 独立运行。当前执行中：{status?.inFlight||0}</p><details><summary>连接诊断</summary><code>{status?.endpoint}</code><p>适配器自动发现本机端点，无需填写动态端口。服务运行不代表助手已接入或已获授权。</p></details></section>
 {error&&<p role="alert" className="mcp-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <nav className="mcp-tabs" aria-label="MCP 管理页签">{['连接管理','客户端接入','会话授权','调用记录'].map(t=><button aria-current={tab===t?'page':undefined} key={t} onClick={()=>setTab(t)}>{t}{t==='会话授权'&&status?` · ${status.sessions.filter(s=>!s.revoked&&!s.connectionIds.length).length}`:''}</button>)}</nav>
 {status&&tab==='连接管理'&&<><form className="mcp-card" onSubmit={e=>{e.preventDefault();if(member)void run('add',{name:name.trim()||`${project?.name} · ${member.name}`,projectId,memberId:member.id,credentialId}).then(ok=>{if(ok){setName('');setCredentialId('');}});}}><h2>添加项目与身份连接</h2><div className="mcp-grid"><label>GameCreator 项目<select aria-label="GameCreator 项目" value={projectId} onChange={e=>{setProjectId(e.target.value);setCredentialId('');}}><option value="">选择已登记项目</option>{status.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>开发者身份<select aria-label="开发者身份" value={credentialId} onChange={e=>setCredentialId(e.target.value)}><option value="">选择有效长期令牌</option>{project?.members.map(m=><option key={m.credentialId} value={m.credentialId} disabled={!m.available}>{m.name}{!m.available?' · 凭证不可用':''}</option>)}</select></label></div><label>连接名称<input aria-label="连接名称" placeholder="默认使用项目名与开发者名称" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label>{project&&<p className="mcp-muted">管理项目：{project.folderPath||'尚未保存'}<br/>引擎工程：{project.engineDirectory||'尚未连接'}</p>}{project?.error&&<p className="mcp-error">{project.error}</p>}<p className="mcp-muted">凭证由软件的本地凭证库签名。缺少凭证时，在人员分配中导入已保存凭证或更换令牌。添加连接后还需为会话授权。</p><button disabled={busy||!member?.available}>添加连接</button></form><div className="mcp-grid">{status.connections.map(c=><article key={c.id} className="mcp-card"><div className="mcp-row"><h3>{c.name}</h3><span>{stateLabel[c.status]}</span></div><p>{c.projectName||c.projectId} · {c.memberName||c.memberId}</p><p>{c.roles?.join('、')}</p><p className="mcp-muted">{c.permissions?.join(' / ')}</p><code>{c.id}</code>{c.error&&<p className="mcp-error">{c.error}</p>}<div className="mcp-actions"><button disabled={busy} onClick={()=>void run('connection',{id:c.id,enabled:!c.enabled})}>{c.enabled?'停用连接':'启用连接'}</button><button disabled={busy} onClick={()=>void run('connection',{id:c.id,remove:true})}>删除连接</button></div></article>)}</div></>}
 {status&&tab==='客户端接入'&&<section className="mcp-card"><h2>一次注册，按会话授权</h2><ol><li>将下面配置加入 AI 客户端的 MCP 配置，运行环境需要 Node.js 20 或更新版本。</li><li>客户端加载工具后，调用 gc_connections。到“会话授权”核对接入码，选择该会话可以使用的连接。</li><li>助手再次读取连接列表，每次操作指定 connectionId。新增项目无需修改客户端配置。</li></ol><label>配置格式<select aria-label="配置格式" value={format} onChange={e=>setFormat(e.target.value as 'toml'|'json')}><option value="toml">TOML</option><option value="json">JSON</option></select></label><pre>{status.config[format]}</pre><button onClick={()=>void navigator.clipboard.writeText(status.config[format]).then(()=>setNotice('连接配置已复制')).catch(()=>setError('复制失败，请手动复制配置。'))}><Copy size={16}/>复制连接配置</button><p>软件重启后自动重新发现端点；同一适配器进程可恢复原授权。新适配器进程会产生新接入码，需要重新授权。</p><p className="mcp-muted">会话表示 MCP 适配器进程，不等于聊天。若客户端在多个聊天间共享进程，这些聊天共享该会话授权。不同岗位需要独立进程或独立客户端实例，并分别授权。不要把所有岗位都授给同一个会话。</p></section>}
 {status&&tab==='会话授权'&&<><p>核对接入码后授权。会话只能列出获准的连接；开发者停用、撤销或权限变更按最新项目状态校验。</p>{!status.sessions.length&&<section className="mcp-card">暂无会话。先复制接入配置，在助手中调用 gc_connections。</section>}<div className="mcp-grid">{status.sessions.map(s=><SessionCard key={s.id} session={s} connections={status.connections} busy={busy} run={run}/>)}</div></>}
 {status&&tab==='调用记录'&&<section className="mcp-card"><h2>最近调用</h2><p className="mcp-muted">显示本次软件运行期间最近 100 次已授权操作。正式提交与同步记录仍保存在各项目中。</p>{!status.events.length?<p>暂无调用。</p>:status.events.map(e=><article className="mcp-event" key={e.id}><strong>{e.connectionName} · {e.tool}</strong><span>{stateLabel[e.status]}</span><p>{e.clientName} · {new Date(e.at).toLocaleString()}</p>{e.error&&<p className="mcp-error">{e.error}</p>}</article>)}</section>}
 </>}</main>;
}
