import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Copy,Plug,RefreshCw} from 'lucide-react';
import './mcp-connections.css';
type Connection={id:string;name:string;projectId:string;memberId:string;credentialId:string;enabled:boolean;projectName?:string;projectDirectory?:string;engineDirectory?:string;memberName?:string;roles?:string[];permissions?:string[];status:string;error:string};
type Session={id:string;name:string;code:string;connectionIds:string[];boundConnectionIds:string[];revoked:boolean;online:boolean;lastSeen:string|null;createdAt:string};
type Status={policy:'credential'|'approval';enabled:boolean;version:string;endpoint:string;inFlight:number;config:{json:string;toml:string};projects:{id:string;name:string;folderPath:string;engineDirectory:string;members:{id:string;name:string;credentialId:string;available:boolean;error:string}[];error:string}[];connections:Connection[];sessions:Session[];events:{id:string;at:string;clientName:string;connectionName:string;tool:string;status:string;error?:string}[]};
export type McpConnectionsAPI=(operation:string,input?:Record<string,unknown>)=>Promise<Status>;
const stateLabel:Record<string,string>={available:'可用',disabled:'已停用',unavailable:'不可用',running:'执行中',succeeded:'成功',failed:'失败'};
function SessionCard({session,connections,busy,run,approval}:{approval:boolean;session:Session;connections:Connection[];busy:boolean;run:(operation:string,input:Record<string,unknown>)=>Promise<boolean>}){
 const [selected,setSelected]=useState(session.connectionIds),[editing,setEditing]=useState(false);
 useEffect(()=>{if(!editing)setSelected(session.connectionIds);},[session.connectionIds.join(','),editing]);
 return <article className="mcp-card"><div className="mcp-row"><h3>{session.name}</h3><span>{session.revoked?'已撤销':session.online?'会话在线':'会话离线'}</span></div><p>接入码 <strong className="mcp-code">{session.code}</strong></p><p className="mcp-muted">{approval?'附加审批已开启：核对接入码，再批准所需连接。每次调用仍须提供身份凭证。':'当前为凭证自助接入，无需批准接入码。每次调用独立验证身份。'}</p>
 {approval&&<fieldset disabled={busy||session.revoked}><legend>授权连接（可多选）</legend>{connections.length?connections.map(c=><label key={c.id} className="mcp-check"><input type="checkbox" checked={selected.includes(c.id)} disabled={!c.enabled||c.status!=='available'} onChange={e=>{setEditing(true);setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id));}}/>{c.name} · {c.memberName||'身份不可用'}</label>):<p>先添加项目与身份连接。</p>}</fieldset>}
 <p className="mcp-muted">凭证已绑定 {session.boundConnectionIds.length} 个连接 · 附加批准 {session.connectionIds.length} 个 · 最近活动：{session.lastSeen?new Date(session.lastSeen).toLocaleString():'本次启动尚无活动'}</p>
 <div className="mcp-actions">{!session.revoked&&<>{approval&&<button disabled={busy} onClick={()=>void run('session',{id:session.id,connectionIds:selected}).then(ok=>{if(ok)setEditing(false);})}>保存附加审批</button>}<button disabled={busy} onClick={()=>void run('session',{id:session.id,revoke:true})}>撤销会话</button></>}{session.revoked&&<button disabled={busy} onClick={()=>void run('remove-session',{id:session.id})}>删除记录</button>}</div></article>;
}
export function McpConnections({onBack}:{onBack:()=>void}){
 const api=window.desktopClient?.mcpConnections,[status,setStatus]=useState<Status>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [tab,setTab]=useState('身份连接'),[projectId,setProjectId]=useState(''),[credentialId,setCredentialId]=useState(''),[name,setName]=useState(''),[format,setFormat]=useState<'toml'|'json'>('toml');
 const mounted=useRef(true),inFlight=useRef(false),sequence=useRef(0);
 useEffect(()=>{mounted.current=true;let timer:number;const refresh=async()=>{if(api&&!inFlight.current){const revision=++sequence.current;try{const next=await api('status');if(mounted.current&&sequence.current===revision)setStatus(next);}catch(e){if(mounted.current)setError((e as Error).message);}}if(mounted.current)timer=window.setTimeout(refresh,3000);};void refresh();return()=>{mounted.current=false;window.clearTimeout(timer);};},[api]);
 async function run(operation:string,input:Record<string,unknown>={}){if(!api||inFlight.current)return false;inFlight.current=true;++sequence.current;setBusy(true);setError('');setNotice('');try{const next=await api(operation,input);if(mounted.current){setStatus(next);setNotice(operation==='status'?'状态已刷新':'设置已保存');}return true;}catch(e){if(mounted.current)setError((e as Error).message);return false;}finally{inFlight.current=false;if(mounted.current)setBusy(false);}}
 const project=status?.projects.find(p=>p.id===projectId),member=project?.members.find(m=>m.credentialId===credentialId);
 return <main className="mcp-page" aria-label="MCP 连接"><header className="mcp-row"><div><div className="crumb">本机管理 / AI 工作流</div><h1>MCP 连接</h1></div><button onClick={onBack}><ArrowLeft size={16}/>返回工作区</button></header><p>统一接入 GameCreator，助手凭用户交付的长期身份令牌自助接入。切换当前项目不会改变工具的操作目标。</p>
 {!api?<p role="alert">请使用桌面客户端管理 MCP 连接。</p>:<><section className="mcp-card"><div className="mcp-row"><h2><Plug size={22}/>软件级 MCP 服务</h2><strong className={status?.enabled?'mcp-online':''}>{status?status.enabled?'服务运行中':'服务已停止':'正在检查…'}</strong></div><p>适配器 {status?.version||'—'} · {status?.connections.length||0} 个连接 · {status?.sessions.filter(s=>s.online&&!s.revoked).length||0} 个在线会话</p><div className="mcp-actions"><button disabled={busy||!status} onClick={()=>void run('enabled',{enabled:!status?.enabled})}>{status?.enabled?'停止接入':'启动接入'}</button><button disabled={busy} onClick={()=>void run('status')}><RefreshCw size={16}/>刷新状态</button></div><p className="mcp-muted">停止接入会拒绝新操作，已开始的写入可能继续收尾。旧版逐项目 MCP 独立运行。当前执行中：{status?.inFlight||0}</p><details><summary>连接诊断</summary><code>{status?.endpoint}</code><p>适配器自动发现本机端点，无需填写动态端口。服务运行不代表助手已接入或已获授权。</p></details></section>
 {error&&<p role="alert" className="mcp-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <nav className="mcp-tabs" aria-label="MCP 管理页签">{['身份连接','客户端接入','接入策略','会话与审批','调用记录'].map(t=><button aria-current={tab===t?'page':undefined} key={t} onClick={()=>setTab(t)}>{t}{t==='会话与审批'&&status?.policy==='approval'?` · ${status.sessions.filter(s=>!s.revoked&&s.boundConnectionIds.some(id=>!s.connectionIds.includes(id))).length}`:''}</button>)}</nav>
 {status&&tab==='身份连接'&&<><p>助手调用 gc_connect_credential 验证令牌后，身份连接会自动出现在这里，无需预先添加。</p><details><summary>手动预建连接（可选）</summary><form className="mcp-card" onSubmit={e=>{e.preventDefault();if(member)void run('add',{name:name.trim()||`${project?.name} · ${member.name}`,projectId,memberId:member.id,credentialId}).then(ok=>{if(ok){setName('');setCredentialId('');}});}}><h2>添加项目与身份连接</h2><div className="mcp-grid"><label>GameCreator 项目<select aria-label="GameCreator 项目" value={projectId} onChange={e=>{setProjectId(e.target.value);setCredentialId('');}}><option value="">选择已登记项目</option>{status.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>开发者身份<select aria-label="开发者身份" value={credentialId} onChange={e=>setCredentialId(e.target.value)}><option value="">选择有效长期令牌</option>{project?.members.map(m=><option key={m.credentialId} value={m.credentialId} disabled={!m.available}>{m.name}{!m.available?' · 凭证不可用':''}</option>)}</select></label></div><label>连接名称<input aria-label="连接名称" placeholder="默认使用项目名与开发者名称" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label>{project&&<p className="mcp-muted">管理项目：{project.folderPath||'尚未保存'}<br/>引擎工程：{project.engineDirectory||'尚未连接'}</p>}{project?.error&&<p className="mcp-error">{project.error}</p>}<p className="mcp-muted">此处仅登记项目与身份，不提供凭证，也不授权助手代用该身份。助手仍需持有自己的凭证文件并逐次签名。</p><button disabled={busy||!member?.available}>添加连接</button></form></details><div className="mcp-grid">{status.connections.map(c=><article key={c.id} className="mcp-card"><div className="mcp-row"><h3>{c.name}</h3><span>{stateLabel[c.status]}</span></div><p>{c.projectName||c.projectId} · {c.memberName||c.memberId}</p><p>{c.roles?.join('、')}</p><p className="mcp-muted">{c.permissions?.join(' / ')}</p><code>{c.id}</code>{c.error&&<p className="mcp-error">{c.error}</p>}<div className="mcp-actions"><button disabled={busy} onClick={()=>void run('connection',{id:c.id,enabled:!c.enabled})}>{c.enabled?'停用连接':'启用连接'}</button><button disabled={busy} onClick={()=>void run('connection',{id:c.id,remove:true})}>删除连接</button></div></article>)}</div></>}
 {status&&tab==='客户端接入'&&<section className="mcp-card"><h2>一次注册，凭令牌自助接入</h2><ol><li>将下面配置加入 AI 客户端，运行环境需要 Node.js 20 或更新版本。</li><li>将属于该助手的凭证文件路径交付给它，调用 gc_connect_credential。默认无需人工审批或预建连接。</li><li>每次读取或写入都传入 connectionId 和 credentialFile；适配器重新读取凭证并签名，不沿用其他调用的身份。</li></ol><label>配置格式<select aria-label="配置格式" value={format} onChange={e=>setFormat(e.target.value as 'toml'|'json')}><option value="toml">TOML</option><option value="json">JSON</option></select></label><pre>{status.config[format]}</pre><button onClick={()=>void navigator.clipboard.writeText(status.config[format]).then(()=>setNotice('连接配置已复制')).catch(()=>setError('复制失败，请手动复制配置。'))}><Copy size={16}/>复制连接配置</button><pre>{'gc_connect_credential({credentialFile: "凭证文件绝对路径"})\n\ngc_project_read({connectionId: "绑定返回的编号", credentialFile: "同一凭证文件绝对路径"})'}</pre><p>软件重启后自动发现端点。新适配器进程重新证明持有令牌即可接入；旧版 2.0 全局适配器须重启加载 3.0，原逐项目配置仍然可用。</p><p className="mcp-muted">连接编号不提供授权。共享 MCP 进程无法识别聊天身份；若它能读取其他成员的凭证，同样可能签署该身份。不同岗位须通过受限凭证目录或独立运行环境隔离。适配器不会扫描凭证目录，也不从软件凭证库选择身份。</p></section>}
{status&&tab==='接入策略'&&<section className="mcp-card"><h2>身份接入策略</h2><label>接入方式<select aria-label="接入方式" value={status.policy} disabled={busy} onChange={e=>void run('policy',{policy:e.target.value})}><option value="credential">凭证自助接入（默认）</option><option value="approval">凭证验证后附加人工审批</option></select></label><p>凭证模式下，用户交付有效令牌就是身份授权，无需再次批准接入码。附加审批模式要求凭证验证通过后，再由管理者批准本会话的连接。</p><p className="mcp-muted">策略立即用于后续与排队中的操作；停止接入、撤销会话或停用连接仍然有效。附加审批不替代每次调用的凭证签名。删除连接记录不会撤销身份令牌；永久撤销请到人员分配操作。</p></section>}
{status&&tab==='会话与审批'&&<><p>{status.policy==='credential'?'当前为凭证自助接入，不需要批准会话。下方显示已验证的身份连接及最近活动。':'附加审批已开启：核对接入码后批准连接；助手每次仍须提供对应凭证。'}</p>{!status.sessions.length&&<section className="mcp-card">暂无会话。配置客户端后，让助手使用自己的凭证调用 gc_connect_credential。</section>}<div className="mcp-grid">{status.sessions.map(s=><SessionCard key={s.id} session={s} connections={status.connections.filter(c=>s.boundConnectionIds.includes(c.id))} approval={status.policy==='approval'} busy={busy} run={run}/>)}</div></>}
 {status&&tab==='调用记录'&&<section className="mcp-card"><h2>最近调用</h2><p className="mcp-muted">显示本次软件运行期间最近 100 次已授权操作。正式提交与同步记录仍保存在各项目中。</p>{!status.events.length?<p>暂无调用。</p>:status.events.map(e=><article className="mcp-event" key={e.id}><strong>{e.connectionName} · {e.tool}</strong><span>{stateLabel[e.status]}</span><p>{e.clientName} · {new Date(e.at).toLocaleString()}</p>{e.error&&<p className="mcp-error">{e.error}</p>}</article>)}</section>}
 </>}</main>;
}
