import {AiTaskAssignment} from './AiTaskAssignment';
import type {AiMember} from '../shared/ai-personnel.mjs';
import './ai-personnel.css';
import {MilestoneCards,MilestoneReview} from './ScheduleMilestoneReview';
import {milestoneAcceptance,acceptProductionMilestone} from './schedule-acceptance';
import { ScheduleProgress } from './ScheduleProgress';
import { setProgressTaskStatus } from './schedule-progress';
import {useSearchRequest,useLeaveSearch} from './GlobalSearch';
import { cloneElement, isValidElement, useEffect, useId, useRef, useState, type ReactElement, type ReactNode } from 'react';
import { CalendarDays, Plus, Flag, CheckCircle2, Clock3, AlertTriangle, X, ExternalLink, Trash2, ChevronLeft, ChevronRight, Search, List, GanttChart, Route } from 'lucide-react';
import { ScheduleTimeline } from './ScheduleTimeline';
import { createProductionTask, createProductionMilestone, productionKinds, productionStatuses, productionPriorities, scheduleReferenceLabels, scheduleReference, projectScheduleIssues, removeProductionTask, removeProductionMilestone, scheduleToday, shiftScheduleDate, type ProductionTask, type ProductionMilestone, type ScheduleReference, type ScheduleSources, type ScheduleIssue } from './project-schedule';
import type { ProjectScheduleController } from './useProjectSchedule';
import './project-schedule.css';

type Selection = { kind: 'task' | 'milestone'; id: string };
type Props = { controller: ProjectScheduleController; sources: ScheduleSources; onOpenReference: (ref: ScheduleReference) => void; requested?: Selection; statusLabel?: string };
export function ProjectSchedule({ controller: c, sources, onOpenReference, requested, statusLabel }: Props) {
  const searchRequest=useSearchRequest('项目排期',t=>(t.kind==='milestone'?c.store.milestones:c.store.tasks).some(x=>x.id===t.id));
  useEffect(()=>{if(searchRequest){setSelection({kind:searchRequest.kind==='milestone'?'milestone':'task',id:searchRequest.id});setQuery('');setStatus('all');setTab(searchRequest.kind==='milestone'?'milestones':'tasks');}},[searchRequest]);
  const [tab, setTab] = useState('timeline'), [query, setQuery] = useState(''), [status, setStatus] = useState('all'), [groupBy, setGroupBy] = useState('milestone');
  const [selection, setSelection] = useState<Selection | null>(null), [creating, setCreating] = useState<Selection['kind'] | null>(null), [newName, setNewName] = useState('');
  const [today, setToday] = useState(scheduleToday), [start, setStart] = useState(() => shiftScheduleDate(scheduleToday(), -3)), [days, setDays] = useState(42);
  useEffect(() => { const timer = window.setInterval(() => setToday(scheduleToday()), 60000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!requested) return; if (requested.id) setSelection(requested); else { setNewName(''); setCreating(requested.kind); } }, [requested]);
  const [reviewId,setReviewId]=useState(''),[reviewMessage,setReviewMessage]=useState('');
  const store = c.store, issues = projectScheduleIssues(store, today, sources), completed = store.tasks.filter(t => t.status === '已完成').length;
  const readyMilestones=store.milestones.filter(m=>m.status!=='已验收'&&milestoneAcceptance(store,m.id).ready),reviewing=store.milestones.find(m=>m.id===reviewId);
  const beginReview=(id:string)=>{setSelection(null);setReviewMessage('');setReviewId(id);};
  const reopenMilestone=(id:string)=>c.update(s=>({...s,milestones:s.milestones.map(m=>m.id===id?{...m,status:'进行中'}:m)}));
  const filtered = store.tasks.filter(t => (status === 'all' || t.status === status) && (t.title + t.description + t.owner + t.kind).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const task = selection?.kind === 'task' ? store.tasks.find(t => t.id === selection.id) : undefined, milestone = selection?.kind === 'milestone' ? store.milestones.find(m => m.id === selection.id) : undefined;
  const leaveSearch=useLeaveSearch('项目排期');
  const openTask = (id: string) => { if(selection?.kind!=='task'||selection.id!==id)leaveSearch(); setSelection({ kind: 'task', id }); }, openMilestone = (id: string) => { if(selection?.kind!=='milestone'||selection.id!==id)leaveSearch(); setSelection({ kind: 'milestone', id }); };
  const create = (kind: Selection['kind']) => { setNewName(''); setCreating(kind); };
  const patchTask = (fields: Partial<ProductionTask>) => { if (task) c.update(s => ({ ...s, tasks: s.tasks.map(t => t.id === task.id ? { ...t, ...fields } : t) })); };
  const patchMilestone = (fields: Partial<ProductionMilestone>) => { if (milestone) c.update(s => ({ ...s, milestones: s.milestones.map(m => m.id === milestone.id ? { ...m, ...fields } : m) })); };
  const move = (next: ProductionTask, original: ProductionTask) => {
    c.update(s => { const current = s.tasks.find(t => t.id === original.id); if (!current || current.start !== original.start || current.end !== original.end) throw new Error('任务日期已变化，请重新拖动'); return { ...s, tasks: s.tasks.map(t => t.id === next.id ? { ...t, start: next.start, end: next.end } : t) }; });
  };
  const selectedIssues = issues.filter(i => task ? i.taskId === task.id : milestone ? i.milestoneId === milestone.id : false);
  const jump = (ref: ScheduleReference) => { setSelection(null); onOpenReference(ref); };
  return <section className="sch-workspace" aria-label="项目排期工作区">
    <div className="sch-heading"><div><span className="sch-kicker">PRODUCTION SCHEDULE</span><h2>让制作计划有清晰的下一步。</h2><p>安排任务、串起依赖，用里程碑确认阶段成果。</p></div><div className="sch-actions"><button disabled={c.blocked} onClick={() => create('milestone')}><Flag size={16}/>新建里程碑</button><button className="primary" disabled={c.blocked} onClick={() => create('task')}><Plus size={16}/>新建制作任务</button></div></div>
    <ScheduleRecovery controller={c}/>
    {reviewMessage&&<p className="sch-review-notice" role="status">{reviewMessage}</p>}
    {!!readyMilestones.length&&<div className="sch-review-notice" role="status"><span>{readyMilestones.length} 个里程碑的任务已全部完成，等待确认验收。</span><button onClick={()=>setTab('milestones')}>查看待验收里程碑</button></div>}
    <div className="sch-stats"><Stat icon={<List/>} value={store.tasks.length} label="制作任务"/><Stat icon={<CheckCircle2/>} value={store.tasks.length ? Math.round(completed / store.tasks.length * 100) + '%' : '—'} label={'任务完成 · ' + completed + '/' + store.tasks.length}/><Stat icon={<Clock3/>} value={store.tasks.filter(t => !t.start || !t.end).length} label="待安排日期"/><Stat icon={<Flag/>} value={store.milestones.filter(m => m.status === '已验收').length + '/' + store.milestones.length} label="里程碑已验收"/></div>
    <div className="sch-board"><div className="sch-tabs" role="tablist" aria-label="排期视图">{[['timeline', '时间轴', GanttChart], ['tasks', '任务列表', List], ['progress', '任务进度', Route], ['milestones', '里程碑', Flag]].map(([id, name, Icon]) => <button role="tab" aria-selected={tab === id} key={String(id)} onClick={() => setTab(String(id))}>{typeof Icon !== 'string' && <Icon size={16}/>}<span>{String(name)}</span></button>)}</div>
      {tab !== 'milestones' && !!(store.tasks.length || store.milestones.length) && <div className="sch-toolbar"><label className="sch-search"><Search size={15}/><input aria-label="搜索制作任务" placeholder="搜索任务、负责人或说明…" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="制作状态筛选" value={status} onChange={e => setStatus(e.target.value)}><option value="all">全部状态</option>{productionStatuses.map(v => <option key={v}>{v}</option>)}</select>{tab === 'timeline' && <><select aria-label="时间轴分组" value={groupBy} onChange={e => setGroupBy(e.target.value)}><option value="milestone">按里程碑分组</option><option value="kind">按制作方向分组</option><option value="owner">按负责人分组</option></select><span className="sch-toolbar-spacer"/><button aria-label="上一个排期时段" onClick={() => setStart(shiftScheduleDate(start, -days))}><ChevronLeft size={16}/></button><input type="date" aria-label="时间轴开始日期" value={start} onChange={e => { if (e.target.value) setStart(e.target.value); }}/><button aria-label="下一个排期时段" onClick={() => setStart(shiftScheduleDate(start, days))}><ChevronRight size={16}/></button><select aria-label="时间轴显示天数" value={days} onChange={e => setDays(Number(e.target.value))}><option value="42">6 周</option><option value="84">12 周</option><option value="168">24 周</option></select><button onClick={() => setStart(shiftScheduleDate(today, -3))}>今天</button><button onClick={() => { const dates = [...store.tasks.flatMap(t => [t.start, t.end]), ...store.milestones.map(m => m.due)].filter(Boolean).sort(); if (dates.length) setStart(shiftScheduleDate(dates[0], -2)); }}>定位首项</button></>}</div>}
      {!store.tasks.length && !store.milestones.length ? <div className="sch-empty"><div className="sch-empty-icon"><CalendarDays size={35}/></div><h3>从一个可以交付的目标开始</h3><p>把设计、程序、美术和验证工作拆成制作任务，<br/>安排日期后，它们会出现在这里。</p><div className="sch-actions"><button className="primary" disabled={c.blocked} onClick={() => create('task')}><Plus size={16}/>创建第一个制作任务</button><button disabled={c.blocked} onClick={() => create('milestone')}><Flag size={16}/>先设定里程碑</button></div></div> : <>
      {tab === 'timeline' && <><ScheduleTimeline store={store} tasks={filtered} groupBy={groupBy} start={start} days={days} today={today} disabled={c.blocked} onOpen={openTask} onMilestone={openMilestone} onMove={move}/><div className="sch-hint">{start} — {shiftScheduleDate(start, days - 1)} · 拖动时间条调整日期，拖动两端调整时长。方向键移动一天，Esc 取消拖动。</div></>}
      {tab === 'progress' && <ScheduleProgress store={store} tasks={filtered} issues={issues} disabled={c.blocked} saveLabel={statusLabel ?? (c.pending ? '草稿未保存，请重试' : '修改自动保存')} onOpen={openTask} onStatus={(item, next) => { leaveSearch(); c.update(current => setProgressTaskStatus(current, item.id, item.status, next)); }}/>}
      {tab === 'tasks' && <div className="sch-table-scroll"><table className="sch-table"><thead><tr>{['制作任务', '方向', '负责人', '计划日期', '状态', '优先级', '里程碑', '提醒'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(t => <tr key={t.id}><td><button onClick={() => openTask(t.id)}>{t.title || '未命名任务'}</button></td><td>{t.kind}</td><td>{t.owner || '未分配'}</td><td>{t.start || '未定'} → {t.end || '未定'}</td><td><span className={'sch-status sch-status-' + t.status}>{t.status}</span></td><td>{t.priority}</td><td>{store.milestones.find(m => m.id === t.milestoneId)?.title || '未分组'}</td><td>{issues.some(i => i.taskId === t.id) && <button aria-label={'查看任务提醒：' + t.title} onClick={() => openTask(t.id)}><AlertTriangle size={15}/></button>}</td></tr>)}</tbody></table>{!filtered.length && <p className="sch-no-results">没有匹配的制作任务。</p>}</div>}
      {tab === 'milestones' && <><MilestoneCards store={store} disabled={c.blocked||c.pending} onOpen={openMilestone} onReview={beginReview} onReopen={reopenMilestone}/>{!store.milestones.length&&<div className="sch-no-results">还没有里程碑，请先新建一个阶段目标。</div>}</>}
      </>}
    </div>
    {!!issues.length && <details className="sch-issues"><summary><AlertTriangle size={16}/>排期待处理 · {issues.length} 条提醒</summary><div>{issues.map((i, n) => <button key={n} onClick={() => i.taskId ? openTask(i.taskId) : openMilestone(i.milestoneId!)}><span>{store.tasks.find(t => t.id === i.taskId)?.title || store.milestones.find(m => m.id === i.milestoneId)?.title}</span>{i.message}</button>)}</div></details>}
    <p className="sch-footnote">工具的关联任务全部完成后同步为可使用；里程碑在任务全部完成后，由管理者确认阶段验收。</p>
    {reviewing&&<ScheduleDialog title="确认里程碑验收" onClose={()=>setReviewId('')}><ScheduleRecovery controller={c}/><MilestoneReview key={reviewing.id} store={store} milestone={reviewing} disabled={c.blocked||c.pending} onConfirm={note=>{if(c.update(s=>acceptProductionMilestone(s,reviewing.id,note,today))){setReviewMessage(reviewing.title+(statusLabel?' 验收已记入本机草稿，请保存到团队。':' 已验收，记录已保存。'));setReviewId('');}}}/></ScheduleDialog>}
    {creating && <ScheduleDialog title={creating === 'task' ? '新建制作任务' : '新建里程碑'} onClose={() => setCreating(null)}><form onSubmit={e => { e.preventDefault(); const value = creating === 'task' ? createProductionTask(newName) : createProductionMilestone(newName); c.update(s => creating === 'task' ? { ...s, tasks: [...s.tasks, value as ProductionTask] } : { ...s, milestones: [...s.milestones, value as ProductionMilestone] }); setSelection({ kind: creating, id: value.id }); setCreating(null); }}><Field title={creating === 'task' ? '制作任务名称' : '里程碑名称'}><input autoFocus required maxLength={150} value={newName} onChange={e => setNewName(e.target.value)} placeholder={creating === 'task' ? '例如：完成植物种植与阳光消耗' : '例如：最小对局闭环可玩'}/></Field><p className="sch-muted">创建后可以安排日期、关联设计内容并补充验收条件。</p><div className="sch-dialog-actions"><button type="button" onClick={() => setCreating(null)}>取消</button><button className="primary" disabled={c.blocked || !newName.trim()}>创建</button></div></form></ScheduleDialog>}
    {(task || milestone) && <ScheduleDialog title={task ? '制作任务详情' : '里程碑详情'} onClose={() => setSelection(null)}><ScheduleRecovery controller={c}/>{!!selectedIssues.length && <IssueList issues={selectedIssues}/>}
      {task && <TaskEditor members={store.personnel?.members} task={task} disabled={c.blocked} sources={sources} tasks={store.tasks} milestones={store.milestones} onChange={patchTask} onOpenReference={jump} onOpenTask={openTask}/>}
      {milestone && <><div className="sch-form-grid"><Field title="里程碑名称"><input disabled={c.blocked} value={milestone.title} onChange={e => patchMilestone({ title: e.target.value })}/></Field><Field title="里程碑负责人"><input disabled={c.blocked} value={milestone.owner} onChange={e => patchMilestone({ owner: e.target.value })}/></Field><Field title="里程碑目标日期"><input disabled={c.blocked} type="date" value={milestone.due} onChange={e => patchMilestone({ due: e.target.value })}/></Field><Field title="里程碑状态"><select disabled={c.blocked} value={milestone.status} onChange={e => patchMilestone({ status: e.target.value as ProductionMilestone['status'] })}>{['计划中', '进行中', ...(milestone.status==='已验收'?['已验收']:[])].map(v => <option key={v}>{v}</option>)}</select></Field></div><Field title="阶段交付目标"><textarea disabled={c.blocked} value={milestone.description} onChange={e => patchMilestone({ description: e.target.value })}/></Field><Field title="里程碑验收条件"><textarea disabled={c.blocked} value={milestone.acceptance} placeholder="例如：从主界面进入一局，完成种植、战斗、胜负结算并能重开。" onChange={e => patchMilestone({ acceptance: e.target.value })}/></Field><Field title="里程碑验收记录"><textarea disabled={c.blocked} value={milestone.review} placeholder="记录验证日期、结果与遗留问题。" onChange={e => patchMilestone({ review: e.target.value })}/></Field><div className="sch-review-notice"><span>{milestoneAcceptance(store,milestone.id).ready?'任务已全部完成':'完成全部关联任务后可验收'}</span>{milestone.status==='已验收'?<button disabled={c.blocked||c.pending} onClick={()=>reopenMilestone(milestone.id)}>重新打开验收</button>:<button className="primary" disabled={c.blocked||c.pending||!milestoneAcceptance(store,milestone.id).ready} onClick={()=>beginReview(milestone.id)}>确认阶段验收</button>}</div><h4>关联制作任务</h4><div className="sch-linked-tasks">{store.tasks.filter(t => t.milestoneId === milestone.id).map(t => <button key={t.id} onClick={() => openTask(t.id)}>{t.title}<span>{t.status}</span></button>)}{!store.tasks.some(t => t.milestoneId === milestone.id) && <p className="sch-muted">在制作任务中选择此里程碑即可加入。</p>}</div></>}
      <div className="sch-dialog-actions"><button className="sch-danger" disabled={c.blocked} onClick={() => { if (task && window.confirm('删除此制作任务，并移除其他任务对它的前置依赖？关联的设计内容会保留。')) { c.update(s => removeProductionTask(s, task.id)); setSelection(null); } else if (milestone && window.confirm('删除此里程碑？关联制作任务会保留并移入未分组。')) { c.update(s => removeProductionMilestone(s, milestone.id)); setSelection(null); } }}><Trash2 size={15}/>{task ? '删除制作任务' : '删除里程碑'}</button><span className="sch-muted">{statusLabel ?? (c.pending ? '草稿未保存，请重试' : '修改自动保存')}</span><button onClick={() => setSelection(null)}>关闭</button></div>
    </ScheduleDialog>}
  </section>;
}
function Stat({ icon, value, label }: { icon: ReactNode; value: ReactNode; label: string }) { return <div className="sch-stat">{icon}<div><strong>{value}</strong><span>{label}</span></div></div>; }
function Field({ title, children }: { title: string; children: ReactNode }) { const id = useId(); return <div className="sch-field"><label htmlFor={id}>{title}</label>{isValidElement(children) ? cloneElement(children as ReactElement<{ id: string }>, { id }) : children}</div>; }
function IssueList({ issues }: { issues: ScheduleIssue[] }) { return <ul className="sch-inline-issues">{issues.map((i, n) => <li key={n}>{i.message}</li>)}</ul>; }
function ScheduleDialog({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { ref.current?.showModal(); }, []); return <dialog className="sch-dialog" ref={ref} aria-label={title} onCancel={onClose}><div className="sch-dialog-heading"><h3>{title}</h3><button aria-label={'关闭' + title} onClick={onClose}><X size={18}/></button></div>{children}</dialog>; }
export function ScheduleRecovery({ controller: c }: { controller: ProjectScheduleController }) { return c.error ? <div className="sch-recovery" role="alert"><p>{c.error}</p><div className="sch-actions"><button onClick={() => { const url = URL.createObjectURL(new Blob([JSON.stringify(c.store, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'project-schedule-draft.json'; link.click(); URL.revokeObjectURL(url); }}>导出排期草稿</button>{c.pending && <button onClick={c.retry}>重试保存排期</button>}<button onClick={() => { if (!c.pending || window.confirm('重新读取会放弃当前未保存的排期草稿，请先导出备份。继续？')) c.reload(); }}>重新读取排期</button></div></div> : null; }
function TaskEditor({ members, task: t, disabled, sources, tasks, milestones, onChange, onOpenReference, onOpenTask }: { members?:AiMember[]; task: ProductionTask; disabled: boolean; sources: ScheduleSources; tasks: ProductionTask[]; milestones: ProductionMilestone[]; onChange: (fields: Partial<ProductionTask>) => void; onOpenReference: (r: ScheduleReference) => void; onOpenTask: (id: string) => void }) {
  const [refKind, setRefKind] = useState<ScheduleReference['kind']>('gameplay');
  const select = (title: string, value: string, options: readonly string[], field: string) => <Field title={title}><select disabled={disabled} value={value} onChange={e => onChange({ [field]: e.target.value })}>{options.map(v => <option key={v}>{v}</option>)}</select></Field>;
  return <>{members&&<AiTaskAssignment task={t} members={members} disabled={disabled} onChange={onChange}/>}<Field title="制作任务名称"><input disabled={disabled} value={t.title} onChange={e => onChange({ title: e.target.value })}/></Field><div className="sch-form-grid">{select('制作方向', t.kind, productionKinds, 'kind')}{select('制作状态', t.status, productionStatuses, 'status')}{!members&&<Field title="任务负责人"><input disabled={disabled} value={t.owner} placeholder="填写负责人的姓名" onChange={e => onChange({ owner: e.target.value })}/></Field>}{select('任务优先级', t.priority, productionPriorities, 'priority')}<Field title="所属里程碑"><select disabled={disabled} value={t.milestoneId} onChange={e => onChange({ milestoneId: e.target.value })}><option value="">未分组</option>{milestones.map(m => <option key={m.id} value={m.id}>{m.title}</option>)}{t.milestoneId && !milestones.some(m => m.id === t.milestoneId) && <option value={t.milestoneId}>里程碑已失效</option>}</select></Field><span/></div><div className="sch-form-grid">{[['start', '计划开始日期'], ['end', '计划结束日期'], ['actualStart', '实际开始日期'], ['actualEnd', '实际完成日期']].map(([key, label]) => <Field key={key} title={label}><input disabled={disabled} type="date" value={t[key as 'start']} onChange={e => onChange({ [key]: e.target.value })}/></Field>)}</div><Field title="制作任务说明"><textarea disabled={disabled} value={t.description} onChange={e => onChange({ description: e.target.value })}/></Field><Field title="任务验收条件"><textarea disabled={disabled} value={t.acceptance} onChange={e => onChange({ acceptance: e.target.value })} placeholder="明确做到什么程度、怎样验证。"/></Field>{!!t.proposals?.length&&<details><summary>AI 排期与分配建议 · {t.proposals.length}</summary>{t.proposals.map(p=><article key={p.id}><small>{members?.find(m=>m.id===p.memberId)?.name||p.memberId} · {new Date(p.at).toLocaleString()}</small><p style={{whiteSpace:'pre-wrap'}}>{p.text}</p></article>)}</details>}<Field title="任务验收结果"><textarea disabled={disabled} value={t.result} onChange={e => onChange({ result: e.target.value })} placeholder="记录实际完成情况与验证证据。"/></Field>
    <div className="sch-editor-section"><h4>前置任务</h4><p className="sch-muted">全部前置任务完成后再开始。按日排期，开始日期应晚于前置任务的结束日期。</p><select disabled={disabled} aria-label="添加前置任务" value="" onChange={e => { if (e.target.value) onChange({ dependencyIds: [...t.dependencyIds, e.target.value] }); }}><option value="">选择前置制作任务…</option>{tasks.filter(d => d.id !== t.id && !t.dependencyIds.includes(d.id)).map(d => <option key={d.id} value={d.id}>{d.title} · {d.status}</option>)}</select><div className="sch-link-list">{t.dependencyIds.map(id => { const dep = tasks.find(d => d.id === id); return <div key={id}><button disabled={!dep} onClick={() => onOpenTask(id)}>{dep?.title || '前置任务已失效'}<small>{dep?.status}</small></button><button disabled={disabled} aria-label={'移除前置任务：' + (dep?.title || id)} onClick={() => onChange({ dependencyIds: t.dependencyIds.filter(d => d !== id) })}><X size={15}/></button></div>; })}</div></div>
    <div className="sch-editor-section"><h4>关联设计内容</h4><p className="sch-muted">查看需求来源及其当前状态。工具关联任务全部完成后同步工具验收；其他设计内容保留独立状态。</p><div className="sch-form-grid"><select aria-label="排期来源类型" value={refKind} onChange={e => setRefKind(e.target.value as ScheduleReference['kind'])}>{Object.entries(scheduleReferenceLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><select disabled={disabled} aria-label="添加排期来源" value="" onChange={e => { if (e.target.value) onChange({ references: [...t.references, { kind: refKind, targetId: e.target.value }] }); }}><option value="">选择关联内容…</option>{sources[refKind].filter(r => !r.unavailable && !t.references.some(ref => ref.kind === refKind && ref.targetId === r.id)).map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div className="sch-link-list">{t.references.map(ref => { const r = scheduleReference(ref, sources); return <div key={ref.kind + ref.targetId}><button disabled={!r.available} onClick={() => onOpenReference(ref)}><span>{scheduleReferenceLabels[ref.kind]} / {r.label}<small>{r.status}</small></span><ExternalLink size={15}/></button><button disabled={disabled} aria-label={'移除排期来源：' + r.label} onClick={() => onChange({ references: t.references.filter(v => v.kind !== ref.kind || v.targetId !== ref.targetId) })}><X size={15}/></button></div>; })}</div></div>
  </>;
}
