import {useState} from 'react';
import {Plus,BookImage,X} from 'lucide-react';
import {ArtKnowledge,ReferenceImage} from './ArtKnowledge';
import {artLibrary} from './art-library';
import {applyReferenceBoard} from './reference-boards';
import type {ArtController} from './useArtAssets';
import type {ReferenceSnapshot,ReferenceBoard,KnowledgeImage} from '../shared/art-knowledge.mjs';
export async function addKnowledgeReference(controller:ArtController,image:KnowledgeImage,boardId?:string){
 if(controller.blocked||controller.pending||!controller.workspaceId.startsWith('project:'))throw new Error('请在可保存的正式项目添加参考');
 const existing=(controller.store.referenceBoards||[]).find(b=>boardId?b.id===boardId:b.name==='整体参考'&&!b.categoryId);if(existing?.references.some(r=>r.active&&r.referenceId===image.id&&r.revision===image.revision))throw new Error('参考板已包含此版本的图片');
 const api=window.desktopClient?.artKnowledge;if(!api)throw new Error('请使用桌面客户端');const snapshot=await api.snapshot(image.id,controller.workspaceId);
 if(!controller.update(s=>{const boards=s.referenceBoards||[],b=boards.find(b=>boardId?b.id===boardId:b.name==='整体参考'&&!b.categoryId);if(boardId&&!b)throw new Error('参考板已移除');if(b)return {...s,referenceBoards:boards.map(v=>v.id===b.id?{...v,references:[...v.references,snapshot]}:v)};return {...s,referenceBoards:[...boards,{id:crypto.randomUUID(),name:'整体参考',categoryId:'',references:[snapshot]}]};}))throw new Error('参考图未保存，请处理素材存档提示');
}
export function ReferenceBoards({controller:c}:{controller:ArtController}){
 const [picker,setPicker]=useState<string>(),[notice,setNotice]=useState('');const boards=c.store.referenceBoards||[],categories=artLibrary(c.store).categories,disabled=c.blocked||c.pending||!c.workspaceId.startsWith('project:');
 const update=(id:string,fn:(b:ReferenceBoard)=>ReferenceBoard)=>c.update(s=>({...s,referenceBoards:(s.referenceBoards||[]).map(b=>b.id===id?fn(b):b)}));
 const patch=(id:string,rid:string,changes:Partial<ReferenceSnapshot>)=>update(id,b=>({...b,references:b.references.map(r=>r.id===rid?{...r,...changes}:r)}));
 const apply=(b:ReferenceBoard)=>{if(c.update(s=>applyReferenceBoard(s,b.id)))setNotice('参考说明已加入风格草稿；确认风格基准后进入对应素材提示词与制作标准。');};
 return <section className="reference-boards gp-card" aria-label="项目参考板"><div className="gp-card-heading"><div><h3>项目参考板</h3><p className="gp-muted">参考图及来源保存在项目内。明确借鉴点后应用到风格草稿，确认基准后用于制作。</p></div><button className="gp-secondary" disabled={disabled||boards.length>=50} onClick={()=>c.update(s=>({...s,referenceBoards:[...(s.referenceBoards||[]),{id:crypto.randomUUID(),name:'新参考板',categoryId:'',references:[]}]}))}><Plus size={16}/>新建参考板</button></div>{notice&&<p className="ak-notice" role="status">{notice}</p>}{c.error&&<p role="alert">{c.error}</p>}
 {!boards.length&&<div className="ak-empty"><BookImage size={32}/><h3>把视觉依据放到项目里</h3><p>为整体方向、角色、场景或 UI 建立参考板，记录采用特点和避免表现。</p></div>}
 {boards.map(b=><article className="rb-board" key={b.id}><div className="ak-two"><label className="gp-field">参考板名称<input aria-label="参考板名称" disabled={disabled} maxLength={200} value={b.name} onChange={e=>update(b.id,x=>({...x,name:e.target.value}))}/></label><label className="gp-field">适用范围<select aria-label="参考板适用范围" disabled={disabled} value={b.categoryId} onChange={e=>update(b.id,x=>({...x,categoryId:e.target.value}))}><option value="">整体项目</option>{categories.map(cat=><option key={cat.id} value={cat.id}>{cat.name}</option>)}</select></label></div><div className="ak-toolbar"><button disabled={disabled} onClick={()=>setPicker(b.id)}>从知识库添加参考</button><button disabled={disabled||!b.references.length} onClick={()=>apply(b)}>应用参考说明到风格草稿</button></div><div className="rb-references">{b.references.filter(r=>r.active).map(r=><article className="rb-reference" key={r.id}><ReferenceImage workspaceId={c.workspaceId} storagePath={r.image.storagePath}/><div><h4>{r.metadata.name}</h4><small>资料快照 V{r.revision} · {r.metadata.creator||'作者未登记'} · {r.metadata.work||'作品未登记'}</small><p className="gp-muted">{r.metadata.source||'来源未登记'}</p><fieldset disabled={disabled}>{(['use','take','avoid'] as const).map(key=><label className="gp-field" key={key}>{{use:'参考用途',take:'借鉴内容',avoid:'排除内容'}[key]}<textarea aria-label={'参考板：'+key} rows={key==='use'?1:2} maxLength={key==='use'?200:1500} value={r[key]} onChange={e=>patch(b.id,r.id,{[key]:e.target.value})}/></label>)}<label className="gp-field">约束强度<select value={r.strength} onChange={e=>patch(b.id,r.id,{strength:e.target.value as ReferenceSnapshot['strength']})}><option value="inspiration">仅供启发</option><option value="required">必须遵守</option></select></label><label><input type="checkbox" checked={r.deliverImage} onChange={e=>patch(b.id,r.id,{deliverImage:e.target.checked})}/>将参考图片作为开发文档附件同步到引擎</label><p className="gp-muted">仅随项目保存在本地；同步图片前请核对来源与使用范围。参考图不会成为已采用游戏素材。</p></fieldset><button disabled={disabled} onClick={()=>patch(b.id,r.id,{active:false})}>移出参考板（保留项目快照）</button></div></article>)}</div>{b.references.some(r=>!r.active)&&<details><summary>已移出的项目快照</summary>{b.references.filter(r=>!r.active).map(r=><p key={r.id}>{r.metadata.name} · V{r.revision} <button disabled={disabled} onClick={()=>patch(b.id,r.id,{active:true})}>重新加入</button></p>)}</details>}{!b.references.some(r=>r.active)&&<p className="gp-muted">暂无采用参考。点击上方按钮，从共享知识库选择图片。</p>}</article>)}
 {picker&&<dialog className="gp-dialog ak-picker" aria-label="选择知识库参考" ref={el=>{if(el&&!el.open)el.showModal();}} onCancel={()=>setPicker(undefined)}><button className="ak-close" aria-label="关闭知识库选择" onClick={()=>setPicker(undefined)}><X/></button><ArtKnowledge onUse={image=>addKnowledgeReference(c,image,picker)}/></dialog>}
 </section>;
}
