import { useEffect, useState } from 'react';
import { ArrowLeft, Copy, Link2, PanelLeftClose, PanelRightClose, Plus, Trash2 } from 'lucide-react';
import type { GameplayDesign } from './gameplay';
import { createStageObject, removeStageObject, resizeSpace, stageKinds, stageColors, stageIssues, type StageLayout, type StageObject } from './gameplay-stage';
import { createSpatialRoom, spatialObjectReferences, moveSpatialObject, objectGeometry, removeSpatialRoom, roomObjects, spatialLayout, spatialObjectLocation, spatialViews, type SpatialGeometry, type SpatialView, type SpatialRoom, type SpatialConnection } from './spatial-layout';
import { SpatialCanvas } from './SpatialCanvas';
import './spatial-layout.css';

type Props = { design: GameplayDesign; designs: GameplayDesign[]; disabled: boolean; onChange: (changes: Partial<GameplayDesign>) => void; onNavigate: (id: string, view?: SpatialView) => void; initialView?: SpatialView; initialObjectId?: string; objectReferences?: (designId: string, objectId: string) => string[] };
function NumberInput({ label, value, min = -1e6, max = 1e6, step = .1, disabled, onChange }: { label: string; value: number; min?: number; max?: number; step?: number; disabled?: boolean; onChange: (n: number) => void | boolean }) {
  const [draft, setDraft] = useState(String(value)), [error, setError] = useState('');
  useEffect(() => { setDraft(String(value)); setError(''); }, [value]);
  const commit = () => { const n = Number(draft); if (!draft.trim() || !Number.isFinite(n) || n < min || n > max || step === 1 && !Number.isInteger(n)) { setError(`请输入 ${min} 至 ${max}${step === 1 ? ' 之间的整数' : ''}`); return; } setError(''); if (n !== value && onChange(n) === false) setDraft(String(value)); };
  return <label className="gp-field">{label}<input type="number" aria-label={label} value={draft} min={min} max={max} step={step} disabled={disabled} onChange={e => setDraft(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); commit(); } }} />{error && <small role="alert">{error}</small>}</label>;
}
export function GameplaySpace({ design: d, designs, disabled, onChange, onNavigate, initialObjectId, objectReferences, initialView }: Props) {
  const s = d.space, a = spatialLayout(s), initialObject = s.objects.find(o => o.id === initialObjectId);
  const [roomId, setRoomId] = useState(initialObject?.roomId || ''), [selected, setSelected] = useState(initialObjectId || '');
  const [view, setView] = useState<SpatialView>(initialObject ? a.rooms.find(r => r.id === initialObject.roomId)?.view || (a.view === 'rooms' ? 'free' : a.view) : initialView || a.view);
  const [selectedRoom, setSelectedRoom] = useState(''), [selectedConnection, setSelectedConnection] = useState('');
  const [leftOpen, setLeftOpen] = useState(true), [rightOpen, setRightOpen] = useState(true), [query, setQuery] = useState('');
  const [snap, setSnap] = useState(true), [ranges, setRanges] = useState(true), [mode, setMode] = useState<'select' | 'place' | 'move'>('select'), [kind, setKind] = useState<StageObject['kind']>('actor');
  const [error, setError] = useState(''), [focusToken, setFocusToken] = useState(0);
  const o = s.objects.find(x => x.id === selected), room = a.rooms.find(r => r.id === roomId), r = a.rooms.find(r => r.id === selectedRoom), c = a.connections.find(x => x.id === selectedConnection);
  const patch = (changes: Partial<StageLayout>) => { if (disabled) return; onChange({ space: { ...s, ...changes } }); setError(''); };
  const attempt = (action: () => void) => { try { action(); setError(''); return true; } catch (e) { setError((e as Error).message); return false; } };
  const patchObject = (changes: Partial<StageObject>) => { if (o) patch({ objects: s.objects.map(x => x.id === o.id ? { ...x, ...changes } : x) }); };
  const geometry = o ? objectGeometry(o, s) : undefined;
  const patchGeometry = (changes: Partial<SpatialGeometry>) => { if (o && geometry) patchObject({ geometry: { ...geometry, ...changes } }); };
  const patchRoom = (changes: Partial<SpatialRoom>) => { if (r) patch({ spatial: { ...a, rooms: a.rooms.map(x => x.id === r.id ? { ...x, ...changes } : x) } }); };
  const patchConnection = (changes: Partial<SpatialConnection>) => { if (c) patch({ spatial: { ...a, connections: a.connections.map(x => x.id === c.id ? { ...x, ...changes } : x) } }); };
  const switchView = (next: SpatialView) => { setView(next); setMode('select'); if (next === 'rooms') setRoomId(''); if (!disabled) patch({ spatial: { ...a, ...(room && next !== 'rooms' ? { rooms: a.rooms.map(x => x.id === room.id ? { ...x, view: next } : x) } : { view: next }) } }); };
  const enter = (id: string) => { const next = a.rooms.find(x => x.id === id); if (!next) return; if (next.sourceDesignId) { if (!designs.some(x => x.id === next.sourceDesignId)) { setError('房间来源玩法已失效，请重新关联'); return; } onNavigate(next.sourceDesignId, next.view); return; } setRoomId(id); setSelected(''); setSelectedRoom(id); setSelectedConnection(''); setView(next.view); setMode('select'); };
  const select = (id: string, reveal = false) => { const item = s.objects.find(x => x.id === id); if (!item) return; setSelected(id); setSelectedConnection(''); setSelectedRoom(''); if (reveal) setRightOpen(true); setRoomId(item.roomId || ''); if (view === 'rooms' || (item.roomId || '') !== roomId) setView(a.rooms.find(x => x.id === item.roomId)?.view || 'free'); setMode('select'); };
  useEffect(() => { if (initialObjectId) { select(initialObjectId, true); setFocusToken(x => x + 1); } }, [initialObjectId]);
  const move = (id: string, x: number, y: number) => { if (disabled) return; attempt(() => { const item = s.objects.find(x => x.id === id); if (!item) return; const next = moveSpatialObject(item, s, x, y, view === 'grid' && snap); patch({ objects: s.objects.map(o => o.id === id ? next : o) }); setMode('select'); }); };
  const place = (x: number, y: number) => { if (disabled) return;
    if (mode === 'move' && o) { move(o.id, x, y); return; }
    if (mode !== 'place') { const hit = [...s.objects].reverse().find(o => { const g = objectGeometry(o, s); return (o.roomId || '') === roomId && x >= g.x && y >= g.y && x < g.x + g.width && y < g.y + g.height; }); if (hit) select(hit.id); else setSelected(''); return; }
    if (s.objects.length >= 300) { setError('单个布局最多300个对象'); return; }
    attempt(() => { let item = createStageObject(kind, 1, 1); item.name += ' ' + (s.objects.filter(x => x.kind === kind).length + 1); item.roomId = roomId;
      if (view === 'free') item.geometry = objectGeometry(item, s);
      item = moveSpatialObject(item, s, x, y, view === 'grid' && snap); patch({ objects: [...s.objects, item] }); setSelected(item.id); setSelectedRoom(''); setSelectedConnection(''); setRightOpen(true); });
  };
  const addRoom = () => { const next = createSpatialRoom(a.rooms.length); patch({ spatial: { ...a, view: 'rooms', rooms: [...a.rooms, next] } }); setView('rooms'); setRoomId(''); setSelectedRoom(next.id); setSelectedConnection(''); setRightOpen(true); setFocusToken(x => x + 1); };
  const addConnection = () => { const from = selectedRoom || a.rooms[0]?.id, to = a.rooms.find(x => x.id !== from)?.id; if (!from || !to) return;
    const next: SpatialConnection = { id: crypto.randomUUID(), name: '通路', from, to, fromObjectId: '', toObjectId: '', direction: 'both', condition: '', ruleId: '' };
    patch({ spatial: { ...a, connections: [...a.connections, next] } }); setSelectedConnection(next.id); setSelectedRoom(''); setRightOpen(true);
  };
  const issues = stageIssues(d, designs).filter(x => !x.includes('事件') && !x.includes('轨道') && !x.includes('计时'));
  return <div className="gs-page st-page sp-page"><div className="gs-intro"><div><span className="gp-kicker">SPATIAL DESIGN</span><h3>空间布局</h3><p>同一组对象，在格子、二维空间与房间关系中展开。</p></div><span className="st-summary">{s.objects.length} 个对象 · {a.rooms.length} 个房间</span></div>
    <div className="sp-header"><div className="sp-views" role="tablist" aria-label="空间视图">{Object.entries(spatialViews).map(([v, name]) => <button key={v} role="tab" aria-selected={view === v} onClick={() => switchView(v as SpatialView)}>{name}</button>)}</div><div className="gp-actions"><button className="gp-icon" aria-label={leftOpen ? '隐藏空间列表' : '显示空间列表'} onClick={() => setLeftOpen(x => !x)}><PanelLeftClose size={17} /></button><button className="gp-icon" aria-label={rightOpen ? '隐藏空间属性' : '显示空间属性'} onClick={() => setRightOpen(x => !x)}><PanelRightClose size={17} /></button></div></div>
    {room && <div className="sp-breadcrumb"><button className="gs-text-link" onClick={() => { setRoomId(''); setView('rooms'); }}><ArrowLeft size={14} />房间连接</button><span>/</span><strong>{room.name}</strong></div>}
    {error && <p className="field-error" role="alert">{error}</p>}
    <div className={'sp-workspace' + (!leftOpen ? ' no-left' : '') + (!rightOpen ? ' no-right' : '')}>
      {leftOpen && <aside className="sp-list"><label className="gp-field">查找空间内容<input type="search" aria-label="查找空间内容" placeholder="对象或房间名称…" value={query} onChange={e => setQuery(e.target.value)} /></label><h4>房间 <small>{a.rooms.length}</small></h4><div className="st-object-list">{a.rooms.filter(x => x.name.toLowerCase().includes(query.toLowerCase())).map(x => <button key={x.id} className={selectedRoom === x.id || roomId === x.id ? 'selected' : ''} aria-label={'编辑房间：' + x.name} onClick={() => { setSelectedRoom(x.id); setSelectedConnection(''); setRightOpen(true); }} onDoubleClick={() => enter(x.id)}><span>{x.name || '未命名房间'}</span><small>{x.sourceDesignId ? '关联' : s.objects.filter(o => o.roomId === x.id).length}</small></button>)}</div>
        <h4>布局对象 <small>{s.objects.length}</small></h4><div className="st-object-list">{s.objects.filter(x => x.name.toLowerCase().includes(query.toLowerCase())).map(x => <button key={x.id} className={selected === x.id ? 'selected' : ''} aria-label={'编辑空间对象：' + x.name} onClick={() => { select(x.id, true); setFocusToken(x => x + 1); }}><i style={{ background: stageColors[x.color] }} /><span>{x.name || '未命名'}<small>{spatialObjectLocation(x, s)}</small></span></button>)}</div>{!s.objects.length && <p className="gp-muted">添加对象后，在三种视图中共享名称与关联。</p>}
      </aside>}
      <div className="sp-center"><div className="sp-tools">{view === 'rooms' ? <><button className="gp-secondary" disabled={disabled || a.rooms.length >= 100} onClick={addRoom}><Plus size={14} />添加房间</button><button className="gp-secondary" disabled={disabled || a.rooms.length < 2 || a.connections.length >= 500} onClick={addConnection}><Link2 size={14} />添加房间连接</button></> : <><select aria-label="放置对象类型" value={kind} disabled={disabled} onChange={e => { setKind(e.target.value as StageObject['kind']); setMode('place'); }}>{Object.entries(stageKinds).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><button className="gp-secondary" aria-pressed={mode === 'place'} disabled={disabled} onClick={() => setMode(mode === 'place' ? 'select' : 'place')}><Plus size={14} />放置对象</button><button className="gp-secondary" aria-pressed={mode === 'move'} disabled={disabled || !o} onClick={() => setMode('move')}>移动所选</button><button className="gp-secondary" aria-pressed={mode === 'select'} onClick={() => setMode('select')}>选择对象</button>{view === 'grid' && <label><input type="checkbox" checked={snap} onChange={e => setSnap(e.target.checked)} />按格吸附</label>}<label><input type="checkbox" checked={ranges} onChange={e => setRanges(e.target.checked)} />显示范围</label></>}</div>
        <p className="sp-help">{view === 'rooms' ? '双击房间进入内部布局 · 点击连线编辑方向与通行条件' : mode === 'place' ? '点击画布放置对象；切回“选择对象”结束放置。' : mode === 'move' ? '点击目标位置移动所选对象。' : '拖动对象调整位置；切换视图保留精确坐标。'}</p>
        <SpatialCanvas focusToken={focusToken} space={s} view={view} roomId={roomId} selected={selected} selectedRoom={selectedRoom} selectedConnection={selectedConnection} disabled={disabled} showRanges={ranges} onObject={id => { const item = s.objects.find(x => x.id === id); if (mode !== 'select' && item) { const g = objectGeometry(item, s); place(g.x, g.y); } else select(id); }} onMove={mode === 'select' ? move : undefined} onPlace={view === 'rooms' ? undefined : place} onRoom={id => { setSelectedRoom(id); setSelectedConnection(''); }} onMoveRoom={(id, x, y) => { if (!disabled) patch({ spatial: { ...a, rooms: a.rooms.map(r => r.id === id ? { ...r, x, y } : r) } }); }} onEnterRoom={enter} onConnection={id => { setSelectedConnection(id); setSelectedRoom(''); setRightOpen(true); }} />
        {!!issues.length && <details className="sp-issues"><summary>空间检查 · {issues.length} 项待处理</summary><ul>{issues.map(x => <li key={x}>{x}</li>)}</ul></details>}
      </div>
      {rightOpen && <aside className="sp-properties"><fieldset className="gs-fieldset" disabled={disabled}>{c ? <><h3>连接属性</h3><label className="gp-field">连接名称<input aria-label="连接名称" value={c.name} onChange={e => patchConnection({ name: e.target.value })} /></label>{(['from', 'to'] as const).map(side => { const endpoint = a.rooms.find(r => r.id === c[side]), objects = endpoint ? roomObjects(endpoint, d, designs) : [], key = side === 'from' ? 'fromObjectId' : 'toObjectId'; return <div key={side}><label className="gp-field">{side === 'from' ? '起点房间' : '终点房间'}<select aria-label={side === 'from' ? '起点房间' : '终点房间'} value={c[side]} onChange={e => patchConnection({ [side]: e.target.value, [key]: '' })}><option value="">选择房间</option>{a.rooms.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="gp-field">{side === 'from' ? '出口对象' : '入口对象'}<select aria-label={side === 'from' ? '出口对象' : '入口对象'} value={c[key]} onChange={e => patchConnection({ [key]: e.target.value })}><option value="">不指定出入口</option>{c[key] && !objects.some(o => o.id === c[key]) && <option value={c[key]}>已失效的出入口</option>}{objects.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label></div>; })}<label className="gp-field">通行方向<select aria-label="通行方向" value={c.direction} onChange={e => patchConnection({ direction: e.target.value as 'one' | 'both' })}><option value="both">双向通行 ↔</option><option value="one">起点到终点 →</option></select></label><label className="gp-field">通行条件<textarea aria-label="通行条件" rows={3} value={c.condition} onChange={e => patchConnection({ condition: e.target.value })} /></label><label className="gp-field">关联条件规则<select aria-label="关联条件规则" value={c.ruleId} onChange={e => patchConnection({ ruleId: e.target.value })}><option value="">无关联规则</option>{c.ruleId && !d.conditionRules.some(r => r.id === c.ruleId) && <option value={c.ruleId}>规则已失效</option>}{d.conditionRules.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="gp-secondary gs-delete" onClick={() => { patch({ spatial: { ...a, connections: a.connections.filter(x => x.id !== c.id) } }); setSelectedConnection(''); }}><Trash2 size={14} />删除房间连接</button></>
      : r ? <><h3>房间属性</h3><label className="gp-field">房间名称<input aria-label="房间名称" value={r.name} onChange={e => patchRoom({ name: e.target.value })} /></label><label className="gp-field">内部布局视图<select aria-label="内部布局视图" value={r.view} onChange={e => patchRoom({ view: e.target.value as 'grid' | 'free' })}><option value="grid">网格布局</option><option value="free">自由二维</option></select></label><label className="gp-field">房间空间来源<select aria-label="房间空间来源" value={r.sourceDesignId} onChange={e => { if (s.objects.some(o => o.roomId === r.id) || a.connections.some(c => (c.from === r.id && c.fromObjectId) || (c.to === r.id && c.toObjectId))) { setError('房间已有对象或出入口引用，请先调整后再切换来源'); return; } patchRoom({ sourceDesignId: e.target.value }); }}><option value="">本地房间布局</option>{r.sourceDesignId && !designs.some(d => d.id === r.sourceDesignId) && <option value={r.sourceDesignId}>来源已失效</option>}{designs.filter(x => x.id !== d.id).map(x => <option key={x.id} value={x.id}>{x.title}{x.archived ? '（已归档）' : ''}</option>)}</select></label><label className="gp-field">房间说明<textarea aria-label="房间说明" rows={4} value={r.notes} onChange={e => patchRoom({ notes: e.target.value })} /></label><button className="gp-secondary gs-delete" onClick={() => attempt(() => { patch(removeSpatialRoom(s, r.id)); setSelectedRoom(''); if (roomId === r.id) { setRoomId(''); setView('rooms'); } })}><Trash2 size={14} />删除房间</button></>
      : o && geometry ? <><h3>对象属性</h3><label className="gp-field">对象名称<input aria-label="对象名称" value={o.name} onChange={e => patchObject({ name: e.target.value })} /></label><div className="gp-two-fields"><label className="gp-field">对象类型<select aria-label="对象类型" value={o.kind} onChange={e => patchObject({ kind: e.target.value as StageObject['kind'] })}>{Object.entries(stageKinds).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="gp-field">对象颜色<select aria-label="对象颜色" value={o.color} onChange={e => patchObject({ color: e.target.value as StageObject['color'] })}>{Object.keys(stageColors).map((c, i) => <option key={c} value={c}>{['绿色', '紫色', '蓝色', '黄色', '红色'][i]}</option>)}</select></label></div>
        <label className="gp-field">所属房间<select aria-label="所属房间" value={o.roomId || ''} onChange={e => { const refs = spatialObjectReferences(d, designs, o.id); if (refs.length) { setError('对象已作为出入口：' + refs.join('、') + '。请先调整连接。'); return; } patchObject({ roomId: e.target.value }); setRoomId(e.target.value); }}><option value="">全局空间</option>{a.rooms.filter(r => !r.sourceDesignId).map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
        {view === 'grid' && !o.geometry ? <><label className="gp-field">对象锚点<select aria-label="对象锚点" value={o.anchor} onChange={e => patchObject({ anchor: e.target.value as StageObject['anchor'], ...(e.target.value === 'cell' ? {} : { width: 1, height: 1 }) })}><option value="cell">格子内部</option><option value="left">左侧边界外</option><option value="right">右侧边界外</option></select></label><div className="gp-two-fields"><NumberInput label="对象行" value={o.row} min={1} max={s.rows} step={1} onChange={row => patchObject({ row })} /><NumberInput label="对象列" value={o.column} min={1} max={s.columns} step={1} disabled={o.anchor !== 'cell'} onChange={column => patchObject({ column })} /><NumberInput label="占地宽度" value={o.width} min={1} max={s.columns} step={1} disabled={o.anchor !== 'cell'} onChange={width => patchObject({ width })} /><NumberInput label="占地高度" value={o.height} min={1} max={s.rows} step={1} disabled={o.anchor !== 'cell'} onChange={height => patchObject({ height })} /></div></> : <><p className="gp-muted">位置与尺寸单位：{s.unit || '单位'}</p><div className="gp-two-fields"><NumberInput label="对象 X" value={geometry.x} onChange={x => patchGeometry({ x })} /><NumberInput label="对象 Y" value={geometry.y} onChange={y => patchGeometry({ y })} /><NumberInput label="对象宽度" min={.001} value={geometry.width} onChange={width => patchGeometry({ width })} /><NumberInput label="对象高度" min={.001} value={geometry.height} onChange={height => patchGeometry({ height })} /><NumberInput label="方向角度" min={-360} max={360} value={geometry.rotation} onChange={rotation => patchGeometry({ rotation })} /><label className="gp-field">对象形状<select aria-label="对象形状" value={geometry.shape} onChange={e => patchGeometry({ shape: e.target.value as 'rect' | 'circle' })}><option value="rect">矩形</option><option value="circle">圆形 / 椭圆</option></select></label></div></>}
        {!o.geometry && <label className="gp-field">对象朝向<select aria-label="对象朝向" value={o.direction} onChange={e => patchObject({ direction: e.target.value as StageObject['direction'] })}>{Object.entries({ right: '向右', left: '向左', up: '向上', down: '向下' }).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>}
        <label className="gp-field">范围形状<select aria-label="范围形状" value={o.rangeShape} onChange={e => patchObject({ rangeShape: e.target.value as StageObject['rangeShape'], ...(['ring', 'sector'].includes(e.target.value) && !o.geometry ? { geometry } : {}) })}>{Object.entries({ none: '不显示范围', line: '直线范围', radius: '圆形半径', ring: '环形范围', sector: '扇形范围' }).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>
        {o.geometry ? <NumberInput label="作用距离" min={0} value={geometry.range} onChange={range => patchGeometry({ range, innerRange: Math.min(range, geometry.innerRange) })} /> : <NumberInput label="作用距离（格）" min={0} max={100} value={o.range} onChange={range => patchObject({ range })} />}
        {o.rangeShape === 'ring' && <NumberInput label="环形内半径" min={0} max={geometry.range} value={geometry.innerRange} onChange={innerRange => patchGeometry({ innerRange })} />}{o.rangeShape === 'sector' && <NumberInput label="扇形夹角" min={1} max={360} value={geometry.arc} onChange={arc => patchGeometry({ arc })} />}
        <label className="gp-field">对象说明<textarea aria-label="对象说明" rows={3} value={o.notes} onChange={e => patchObject({ notes: e.target.value })} /></label><div className="gp-actions"><button className="gp-secondary" disabled={s.objects.length >= 300} onClick={() => { const copy = { ...structuredClone(o), id: crypto.randomUUID(), name: o.name + ' · 副本' }; patch({ objects: [...s.objects, copy] }); setSelected(copy.id); setMode('move'); }}><Copy size={14} />复制空间对象</button><button className="gp-secondary gs-delete" onClick={() => attempt(() => { const refs = objectReferences?.(d.id, o.id) || []; if (refs.length) throw new Error('对象被引用：' + refs.join('、') + '。请先调整关联。'); patch(removeStageObject(d, designs, o.id)); setSelected(''); })}><Trash2 size={14} />删除空间对象</button></div></>
      : <><h3>布局属性</h3><p className="gp-muted">选择对象、房间或连线编辑属性。</p></>}
      <details className="sp-layout-settings" open><summary>布局设置</summary><div className="gp-two-fields"><NumberInput label="布局行数" value={s.rows} min={1} max={30} step={1} onChange={n => attempt(() => patch(resizeSpace(s, n, s.columns)))} /><NumberInput label="布局列数" value={s.columns} min={1} max={40} step={1} onChange={n => attempt(() => patch(resizeSpace(s, s.rows, n)))} /><NumberInput label="每格尺寸" value={s.cellSize} min={.001} max={10000} onChange={cellSize => patch({ cellSize })} /><label className="gp-field">长度单位<input aria-label="长度单位" value={s.unit} onChange={e => patch({ unit: e.target.value })} /></label></div><label className="gp-field">布局说明<textarea aria-label="布局说明" value={s.description} rows={3} onChange={e => patch({ description: e.target.value })} /></label></details>
      </fieldset>{r && <button className="gp-secondary" onClick={() => enter(r.id)}>进入房间布局 →</button>}</aside>}
    </div>
  </div>;
}
export function StageBoard({ space, selectedId, onObject, counts, label = '空间布局画布', onNavigate }: { space: StageLayout; selectedId?: string; onObject?: (id: string) => void; counts?: Map<string, number>; label?: string; onNavigate?: (id: string, view?: SpatialView) => void }) {
  const a = spatialLayout(space), o = space.objects.find(x => x.id === selectedId), room = a.rooms.find(r => r.id === o?.roomId);
  const [view, setView] = useState<SpatialView>(a.view), [roomId, setRoomId] = useState('');
  useEffect(() => { if (selectedId && o) { setRoomId(o.roomId || ''); setView(room?.view || (a.view === 'rooms' ? 'free' : a.view)); } }, [selectedId, o?.roomId, room?.view, a.view]);
  return <div><div className="sp-preview-views">{Object.entries(spatialViews).map(([k, v]) => <button className="gp-secondary" key={k} aria-pressed={view === k} onClick={() => { setView(k as SpatialView); if (k === 'rooms') setRoomId(''); }}>{v}</button>)}{roomId && <button className="gs-text-link" onClick={() => { setRoomId(''); setView('rooms'); }}>← 返回房间连接</button>}</div><SpatialCanvas space={space} view={view} roomId={roomId} selected={selectedId} onObject={onObject} counts={counts} showRanges label={label} disabled onEnterRoom={id => { const r = a.rooms.find(x => x.id === id); if (r?.sourceDesignId) onNavigate?.(r.sourceDesignId, r.view); else if (r) { setRoomId(id); setView(r.view); } }} /></div>;
}
