import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import type { Narrative, StoryVariable } from './story-orchestration';
import { isStoryFlag, storyValueText, type StoryCharacter } from './story-characters';
import { Text, Select, NumberField, StoryValueField } from './StoryFields';
export function StoryStates({story,characters,disabled,onChange,selectedId}:{story:Narrative;characters:StoryCharacter[];disabled:boolean;onChange:(p:Partial<Narrative>)=>void;selectedId:string}) {
  const [error,setError]=useState(''),[group,setGroup]=useState(''),[query,setQuery]=useState(''),[open,setOpen]=useState('');
  useEffect(()=>{if(selectedId){setGroup('');setQuery('');setOpen(selectedId);}},[selectedId]);
  const change=(id:string,p:Partial<StoryVariable>)=>onChange({variables:story.variables.map(v=>v.id===id?{...v,...p}:v)});
  const groups=[...new Set(story.variables.map(v=>v.category||'未分类'))];
  return <section className="ns-state-editor" aria-label="故事状态工作区"><div className="nc-heading"><div><span className="gp-kicker">STORY STATE</span><h3>让故事记住选择</h3><p>定义剧情需要记住的事实与数值，供选项条件和后果引用。分类可以按项目自由命名。</p></div><button className="primary" disabled={disabled} onClick={()=>{const v:StoryVariable={id:crypto.randomUUID(),name:'新状态',category:'剧情',initial:0,minimum:0,maximum:1,kind:'flag',trueLabel:'是',falseLabel:'否'};onChange({variables:[...story.variables,v]});setGroup('');setQuery('');setOpen(v.id);}}><Plus size={16}/>添加故事状态</button></div>
    <div className="nc-toolbar"><input aria-label="搜索故事状态" placeholder="搜索状态名称或分类" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="ns-state-groups"><button aria-pressed={!group} onClick={()=>setGroup('')}>全部 · {story.variables.length}</button>{groups.map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g} · {story.variables.filter(v=>(v.category||'未分类')===g).length}</button>)}</div>
    {error&&<p role="alert" className="ns-warning">{error}</p>}{!story.variables.length&&<div className="nc-empty"><h4>只有需要被记住的选择，才需要状态</h4><p>例如“是否拿到钥匙”“伙伴好感”“剩余行动点”。纯对白故事可以不添加。</p></div>}
    <fieldset disabled={disabled} className="ns-fields">{story.variables.filter(v=>(!group||(v.category||'未分类')===group)&&(v.name+v.category).includes(query)).map(v=><details className="ns-entry" key={v.id} open={open===v.id}><summary onClick={e=>{e.preventDefault();setOpen(open===v.id?'':v.id);}}><span>{v.name} <small>{v.category} · {isStoryFlag(v)?'是／否':'数值'}</small></span><b>初始：{storyValueText(v,v.initial)}</b></summary>
      <div className="ns-grid"><Text label="状态名称" value={v.name} onChange={name=>change(v.id,{name})}/><Text label="状态分类" value={v.category} onChange={category=>change(v.id,{category})}/><Select label="状态类型" value={isStoryFlag(v)?'flag':'number'} options={[{id:'flag',name:'是／否'},{id:'number',name:'数值'}]} onChange={kind=>{if(kind==='flag'){if(v.initial!==0&&v.initial!==1){setError('当前初值不是是／否，请先调整到 0 或 1。');return;}change(v.id,{kind,minimum:0,maximum:1});}else if(kind==='number')change(v.id,{kind});setError('');}}/>
      <StoryValueField label="状态初值" variable={v} value={v.initial} onChange={initial=>{if(v.minimum!==null&&initial<v.minimum||v.maximum!==null&&initial>v.maximum){setError('初值超出状态范围');return;}setError('');change(v.id,{initial});}}/></div>
      {isStoryFlag(v)?<div className="ns-grid"><Text label="肯定标签" value={v.trueLabel||'是'} onChange={trueLabel=>change(v.id,{trueLabel})}/><Text label="否定标签" value={v.falseLabel||'否'} onChange={falseLabel=>change(v.id,{falseLabel})}/></div>:<div className="ns-grid">{(['minimum','maximum'] as const).map(k=><label className="gp-field" key={k}>{k==='minimum'?'最小值':'最大值'}（留空不限）<input type="number" aria-label={k==='minimum'?'状态最小值':'状态最大值'} value={v[k]??''} onChange={e=>{const n=e.target.value===''?null:Number(e.target.value);if(n!==null&&(!Number.isFinite(n)||(k==='minimum'?n>v.initial:n<v.initial))){setError('范围需要包含当前初值');return;}setError('');change(v.id,{[k]:n});}}/></label>)}</div>}
      <Select label="关联人物" value={v.characterId||''} blank="全局状态 / 不关联人物" options={characters.map(c=>({id:c.id,name:c.name}))} onChange={characterId=>change(v.id,{characterId})}/><p className="ns-state-help">初值是试玩开始时的状态。选择之后的变化由选项后果定义。</p><details><summary>引用与高级信息</summary><p className="gp-muted">标识：{v.id}</p><p className="gp-muted">{story.choices.filter(c=>c.condition.groups.some(g=>g.some(t=>t.variableId===v.id))||c.effects.some(e=>e.variableId===v.id)).length} 个选项引用 · {story.checks.filter(c=>c.variableId===v.id||c.retryVariableIds.includes(v.id)).length} 个检定引用</p><button className="gp-secondary" onClick={()=>{if(window.confirm('删除状态后，相关条件和后果需要修复。继续？'))onChange({variables:story.variables.filter(x=>x.id!==v.id)});}}>删除故事状态</button></details>
    </details>)}</fieldset>
  </section>;
}
