import { useEffect, useId, useRef, useState } from 'react';
import { Users, Network, Plus, UserRound, MessageCircle, ArrowRight, LayoutGrid } from 'lucide-react';
import type { ArtStore } from './art-assets';
import type { Narrative, StoryActor } from './story-orchestration';
import type { StoryOrchestrationController } from './useStoryOrchestration';
import { addCharacterToStory, createStoryCharacter, removeStoryCharacter, storyValueText, type StoryCharacter } from './story-characters';
import { Text, Select } from './StoryFields';
import './story-people.css';

function usePortrait(character: StoryCharacter, art: ArtStore, workspaceId: string) {
  const [url,setUrl]=useState('');
  const p=character.portrait, file=art.assets.find(a=>a.id===p?.assetId)?.versions.find(v=>v.id===p?.versionId)?.files.find(f=>f.id===p?.fileId);
  useEffect(()=>{let active=true;setUrl('');if(file && /^image\/(png|jpeg|webp|gif|bmp|avif)$/i.test(file.mime))window.desktopClient?.artFiles?.readPreview(workspaceId,file.storagePath).then(r=>{if(active&&/^data:image\/(png|jpeg|webp|gif|bmp|avif);base64,[a-z0-9+/=]+$/i.test(r?.dataUrl||''))setUrl(r!.dataUrl);}).catch(()=>{});return()=>{active=false;};},[workspaceId,file?.storagePath,file?.mime]);
  return url;
}
function Portrait({character,art,workspaceId}:{character:StoryCharacter;art:ArtStore;workspaceId:string}) {
  const url=usePortrait(character,art,workspaceId);
  return <span className="nc-portrait" style={{background:character.color+'25',color:character.color}}>{url?<img src={url} alt={character.name+'肖像'}/>:<span>{character.name.trim().slice(0,1)||<UserRound size={30}/>}</span>}</span>;
}
type Props={controller:StoryOrchestrationController;story:Narrative;art:ArtStore;workspaceId:string;disabled:boolean;onOpenNode:(id:string)=>void;onOpenStory:(id:string)=>void;onOpenState:(id:string)=>void};
export function StoryPeople({controller,story,art,workspaceId,disabled,onOpenNode,onOpenStory,onOpenState}:Props) {
  const {store,update}=controller,characters=store.characters||[],relations=store.relationships||[];
  const [view,setView]=useState('cards'),[scope,setScope]=useState('cast'),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[selectedRelation,setRelation]=useState(''),[name,setName]=useState(''),[error,setError]=useState('');
  const dialog=useRef<HTMLDialogElement>(null);
  const cast=new Set(story.actors.map(a=>a.characterId).filter(Boolean)),current=characters.find(c=>c.id===selected);
  const visible=characters.filter(c=>(scope==='all'||cast.has(c.id))&&(c.name+c.role+c.faction+c.description).toLowerCase().includes(query.toLowerCase()));
  const shown=relations.filter(r=>visible.some(c=>c.id===r.fromId)&&visible.some(c=>c.id===r.toId));
  const relation=relations.find(r=>r.id===selectedRelation);
  const edit=(patch:Partial<StoryCharacter>)=>{if(current&&!disabled)update(s=>({...s,characters:s.characters?.map(c=>c.id===current.id?{...c,...patch}:c)}));};
  const choose=(id:string)=>{setSelected(id);setRelation('');setError('');};
  const relatedStates=current?story.variables.filter(v=>v.characterId===current.id):[];
  const appearances=current?store.stories.flatMap(s=>{const ids=s.actors.filter(a=>a.characterId===current.id).map(a=>a.id);return ids.length?[{story:s,nodes:s.nodes.filter(n=>ids.includes(n.speakerId))}]:[];}):[];
  const actor=current?story.actors.find(a=>a.characterId===current.id):undefined;
  const removeFromStory=()=>{if(!actor)return;if(story.nodes.some(n=>n.speakerId===actor.id)){setError('人物仍有对白，请先调整说话人。');return;}update(s=>({...s,stories:s.stories.map(x=>x.id===story.id?{...x,actors:x.actors.filter(a=>a.id!==actor.id)}:x)}));};
  return <section className="nc-studio" aria-label="人物工作区">
    <div className="nc-heading"><div><span className="gp-kicker">CHARACTERS</span><h3>故事中的人物</h3><p>人物资料在项目内共用，每个故事选择自己的出场阵容。</p></div><button className="primary" disabled={disabled} onClick={()=>{setName('');dialog.current?.showModal();}}><Plus size={16}/>新建人物</button></div>
    <div className="nc-toolbar"><div className="nc-segments"><button aria-pressed={view==='cards'} onClick={()=>setView('cards')}><LayoutGrid size={15}/>人物卡片</button><button aria-pressed={view==='graph'} onClick={()=>setView('graph')}><Network size={15}/>人物关系图</button></div><input aria-label="搜索人物" placeholder="搜索姓名、身份或阵营" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="人物范围" value={scope} onChange={e=>setScope(e.target.value)}><option value="cast">本故事出场 · {cast.size}</option><option value="all">项目人物库 · {characters.length}</option></select></div>
    {error&&<p className="ns-warning" role="alert">{error}</p>}
    <div className={'nc-layout'+(current||relation?' inspecting':'')}><div className="nc-stage">
      {!visible.length?<div className="nc-empty"><Users size={42}/><h4>{query?'没有匹配的人物':'为故事选择出场人物'}</h4><p>创建主角、伙伴或其他人物，或从项目人物库中选入。</p>{scope==='cast'&&<button className="gp-secondary" onClick={()=>setScope('all')}>浏览项目人物库</button>}</div>:view==='cards'?<div className="nc-cards">{visible.map(c=><button key={c.id} className={'nc-card'+(selected===c.id?' selected':'')} aria-label={'人物：'+c.name} aria-pressed={selected===c.id} onClick={()=>choose(c.id)}><Portrait character={c} art={art} workspaceId={workspaceId}/><span className="nc-card-name">{c.name||'未命名人物'}</span><span className="nc-card-role">{c.role||'身份待补充'}{c.faction?' · '+c.faction:''}</span><p>{c.description||'添加简介，描述这个人物在故事中的位置。'}</p><span className="nc-card-footer">{cast.has(c.id)?'本故事出场':'可加入本故事'}<ArrowRight size={14}/></span></button>)}</div>:<>
        <div className="nc-graph-actions"><span>拖动头像整理关系；点击连线编辑关系设定。</span><button className="gp-secondary" disabled={disabled} onClick={()=>{const ids=visible.map(c=>c.id);update(s=>({...s,characters:s.characters?.map(c=>{const i=ids.indexOf(c.id);return i<0?c:{...c,position:{x:150+i%3*290,y:110+Math.floor(i/3)*190}};})}));}}>整理布局</button></div>
        <RelationshipGraph characters={visible} relations={shown} selected={selected} selectedRelation={selectedRelation} art={art} workspaceId={workspaceId} disabled={disabled} onSelect={choose} onRelation={id=>{setRelation(id);setSelected('');}} onMove={(id,position)=>update(s=>({...s,characters:s.characters?.map(c=>c.id===id?{...c,position}:c)}))}/>
      </>}
      <div className="nc-relations"><div className="gp-card-heading"><h4>人物关系 · {shown.length}</h4><button className="gp-secondary" disabled={disabled||visible.length<2} onClick={()=>{const from=visible.find(c=>c.id===selected)||visible[0],to=visible.find(c=>c.id!==from.id)!;const r={id:crypto.randomUUID(),fromId:from.id,toId:to.id,label:'新的关系',description:'',secret:'',directed:false};update(s=>({...s,relationships:[...(s.relationships||[]),r]}));setRelation(r.id);setSelected('');}}>添加人物关系</button></div>{shown.map(r=><button key={r.id} className={r.id===selectedRelation?'selected':''} onClick={()=>{setRelation(r.id);setSelected('');}} aria-label={'关系：'+r.label}><span>{characters.find(c=>c.id===r.fromId)?.name} {r.directed?'→':'↔'} {characters.find(c=>c.id===r.toId)?.name}</span><b>{r.label}</b></button>)}{!shown.length&&<p className="gp-muted">连接人物，记录他们的关系、缘由和隐情。</p>}</div>
    </div>
    {(current||relation)&&<aside className="nc-inspector" aria-label="人物详情"><button className="nc-close" aria-label="关闭人物详情" onClick={()=>{setSelected('');setRelation('');}}>×</button>
      {current&&<><div className="nc-profile-head"><Portrait character={current} art={art} workspaceId={workspaceId}/><h3>{current.name||'未命名人物'}</h3><small>项目人物资料 · {appearances.length} 个故事引用</small></div><fieldset disabled={disabled}>
        <Text label="人物姓名" value={current.name} onChange={name=>edit({name})}/><div className="ns-grid"><Text label="身份" value={current.role} onChange={role=>edit({role})}/><Text label="阵营或群体" value={current.faction} onChange={faction=>edit({faction})}/></div><Text label="人物简介" rows={3} value={current.description} onChange={description=>edit({description})}/>
        <label className="gp-field">肖像素材<select aria-label="肖像素材" value={current.portrait?JSON.stringify(current.portrait):''} onChange={e=>edit({portrait:e.target.value?JSON.parse(e.target.value):null})}><option value="">使用文字头像</option>{current.portrait&&!art.assets.some(a=>a.id===current.portrait?.assetId&&a.versions.some(v=>v.id===current.portrait?.versionId&&v.files.some(f=>f.id===current.portrait?.fileId)))&&<option value={JSON.stringify(current.portrait)}>素材已失效，关联保留</option>}{art.assets.flatMap(a=>a.versions.flatMap(v=>v.files.filter(f=>/^image\/(png|jpeg|webp|gif|bmp|avif)$/i.test(f.mime)).map(f=><option key={a.id+v.id+f.id} value={JSON.stringify({assetId:a.id,versionId:v.id,fileId:f.id})}>{a.name} / {v.name} / {f.name}</option>)))}</select></label><label className="gp-field">人物颜色<input aria-label="人物颜色" type="color" value={current.color} onChange={e=>edit({color:e.target.value})}/></label>
        <details className="nc-details"><summary>背景、动机与表达</summary><Text label="人物背景" rows={4} value={current.background} onChange={background=>edit({background})}/><Text label="人物动机" rows={3} value={current.motivation} onChange={motivation=>edit({motivation})}/><Text label="人物性格" rows={3} value={current.personality} onChange={personality=>edit({personality})}/><Text label="说话风格" rows={3} value={current.speech} onChange={speech=>edit({speech})}/></details>
        <div className="gp-actions">{actor?<button className="gp-secondary" onClick={removeFromStory}>从本故事移出</button>:<button className="primary" onClick={()=>update(s=>addCharacterToStory(s,story.id,current.id))}>加入本故事</button>}<button className="gp-secondary" disabled={appearances.length>0||relations.some(r=>r.fromId===current.id||r.toId===current.id)||store.stories.some(s=>s.variables.some(v=>v.characterId===current.id))} onClick={()=>{update(s=>removeStoryCharacter(s,current.id));setSelected('');}}>删除人物</button></div>
      </fieldset><h4>相关故事状态</h4>{relatedStates.map(v=><button className="nc-reference" key={v.id} onClick={()=>onOpenState(v.id)}>{v.name}<span>初始：{storyValueText(v,v.initial)}</span></button>)}{!relatedStates.length&&<p className="gp-muted">可在故事状态中关联此人物，管理信任、好感或其他变化。</p>}<h4>出场与对白</h4>{appearances.map(a=><details key={a.story.id} open={a.story.id===story.id} className="nc-appearance"><summary>{a.story.title} · {a.nodes.length} 段</summary>{a.story.id!==story.id?<button className="ns-link" onClick={()=>onOpenStory(a.story.id)}>打开这个故事</button>:a.nodes.map(n=><button className="nc-reference" key={n.id} onClick={()=>onOpenNode(n.id)}>{n.title}<small>{story.scenes.find(s=>s.id===n.sceneId)?.title}</small></button>)}</details>)}</>}
      {relation&&<fieldset disabled={disabled}><h3>关系设定</h3><Select label="关系人物一" value={relation.fromId} options={characters.map(c=>({id:c.id,name:c.name}))} onChange={fromId=>{if(fromId)update(s=>({...s,relationships:s.relationships?.map(r=>r.id===relation.id?{...r,fromId,toId:fromId===r.toId?r.fromId:r.toId}:r)}));}}/><Select label="关系人物二" value={relation.toId} options={characters.filter(c=>c.id!==relation.fromId).map(c=>({id:c.id,name:c.name}))} onChange={toId=>{if(toId)update(s=>({...s,relationships:s.relationships?.map(r=>r.id===relation.id?{...r,toId}:r)}));}}/>
        {(['label','description','secret'] as const).map((key,i)=><Text key={key} label={['关系名称','关系缘由','关系隐情'][i]} rows={key==='label'?undefined:4} value={relation[key]} onChange={value=>update(s=>({...s,relationships:s.relationships?.map(r=>r.id===relation.id?{...r,[key]:value}:r)}))}/>)}<label className="nc-checkbox"><input type="checkbox" checked={relation.directed} onChange={e=>update(s=>({...s,relationships:s.relationships?.map(r=>r.id===relation.id?{...r,directed:e.target.checked}:r)}))}/>有方向的关系（人物一 → 人物二）</label><p className="gp-muted">这里记录人物设定。会随剧情变化的信任、好感等，在故事状态中定义。</p><button className="gp-secondary" onClick={()=>{update(s=>({...s,relationships:s.relationships?.filter(r=>r.id!==relation.id)}));setRelation('');}}>删除人物关系</button>
      </fieldset>}
    </aside>}
    </div>
    <dialog ref={dialog} className="gp-dialog" aria-label="新建人物"><form onSubmit={e=>{e.preventDefault();if(!name.trim()||disabled)return;const c=createStoryCharacter(name.trim(),characters.length);update(s=>addCharacterToStory({...s,characters:[...(s.characters||[]),c]},story.id,c.id));choose(c.id);setQuery('');dialog.current?.close();}}><h3>新建人物</h3><Text label="新人物姓名" value={name} onChange={setName}/><p className="gp-muted">保存到项目人物库，并加入当前故事。</p><div className="gp-actions"><button className="gp-secondary" type="button" onClick={()=>dialog.current?.close()}>取消</button><button className="primary" disabled={!name.trim()||disabled}>创建人物</button></div></form></dialog>
  </section>;
}

function GraphPerson({c,art,workspaceId,selected,onPointerDown,onSelect}:{c:StoryCharacter;art:ArtStore;workspaceId:string;selected:boolean;onPointerDown:(event:React.PointerEvent<SVGGElement>)=>void;onSelect:()=>void}) {
  const url=usePortrait(c,art,workspaceId),clip=useId();
  return <g transform={`translate(${c.position.x},${c.position.y})`} role="button" tabIndex={0} aria-label={'关系图人物：'+c.name} onPointerDown={onPointerDown} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect();}}}>
    <defs><clipPath id={clip}><circle r="36"/></clipPath></defs><circle r="42" fill="#222031" stroke={c.color} strokeWidth={selected?4:2}/>{url?<image href={url} x="-36" y="-36" width="72" height="72" clipPath={`url(#${clip})`} preserveAspectRatio="xMidYMid slice"/>:<text textAnchor="middle" y="11" fill={c.color} fontSize="30">{c.name.slice(0,1)}</text>}<rect x="-94" y="50" width="188" height="47" rx="9" fill="#252133"/><text textAnchor="middle" y="69" fill="#f1e9fa" fontSize="14">{c.name.slice(0,12)}</text><text textAnchor="middle" y="88" fill="#ada0c0" fontSize="11">{(c.role||'人物').slice(0,16)}</text>
  </g>;
}
function RelationshipGraph({characters,relations,selected,selectedRelation,art,workspaceId,disabled,onSelect,onRelation,onMove}:{characters:StoryCharacter[];relations:NonNullable<Props['controller']['store']['relationships']>;selected:string;selectedRelation:string;art:ArtStore;workspaceId:string;disabled:boolean;onSelect:(id:string)=>void;onRelation:(id:string)=>void;onMove:(id:string,p:{x:number;y:number})=>void}) {
  const arrow=useId(),ref=useRef<SVGSVGElement>(null),drag=useRef<{id:string;x:number;y:number;px:number;py:number;pointer:number}|null>(null),[moving,setMoving]=useState<{id:string;position:{x:number;y:number}}|null>(null);
  const displayed=characters.map(c=>moving?.id===c.id?{...c,position:moving.position}:c),width=Math.max(900,...characters.map(c=>c.position.x+150)),height=Math.max(510,...characters.map(c=>c.position.y+140));
  const local=(e:React.PointerEvent)=>{const point=new DOMPoint(e.clientX,e.clientY);return point.matrixTransform(ref.current!.getScreenCTM()!.inverse());};
  return <div className="nc-graph" role="region" aria-label="人物关系画布"><svg ref={ref} viewBox={`0 0 ${width} ${height}`} width={width} height={height} onPointerMove={e=>{if(!drag.current||drag.current.pointer!==e.pointerId)return;const p=local(e),d=drag.current;setMoving({id:d.id,position:{x:Math.max(110,Math.min(width-110,d.x+p.x-d.px)),y:Math.max(55,Math.min(height-110,d.y+p.y-d.py))}});}} onPointerUp={e=>{if(!drag.current||drag.current.pointer!==e.pointerId)return;const d=drag.current;drag.current=null;if(moving?.id===d.id)onMove(d.id,moving.position);setMoving(null);}} onPointerCancel={()=>{drag.current=null;setMoving(null);}}>
    <defs><marker id={arrow} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#b693d5"/></marker></defs>{relations.map(r=>{const a=displayed.find(c=>c.id===r.fromId),b=displayed.find(c=>c.id===r.toId);if(!a||!b)return null;const mid={x:(a.position.x+b.position.x)/2,y:(a.position.y+b.position.y)/2},distance=Math.max(1,Math.hypot(b.position.x-a.position.x,b.position.y-a.position.y)),end={x:b.position.x-(b.position.x-a.position.x)/distance*48,y:b.position.y-(b.position.y-a.position.y)/distance*48};return <g key={r.id} role="button" tabIndex={0} aria-label={'关系连线：'+r.label} onClick={()=>onRelation(r.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onRelation(r.id);}}}><line x1={a.position.x} y1={a.position.y} x2={b.position.x} y2={b.position.y} stroke="transparent" strokeWidth="22"/><line x1={a.position.x} y1={a.position.y} x2={end.x} y2={end.y} markerEnd={r.directed?`url(#${arrow})`:undefined} stroke={r.id===selectedRelation?'#d7bcff':'#675879'} strokeWidth="2"/><rect x={mid.x-66} y={mid.y-14} width="132" height="28" rx="14" fill="#342a43"/><text x={mid.x} y={mid.y+5} textAnchor="middle" fill="#e8d5fc" fontSize="12">{r.label.slice(0,9)}{r.directed?' →':' ↔'}</text></g>;})}
    {displayed.map(c=><GraphPerson key={c.id} c={c} art={art} workspaceId={workspaceId} selected={selected===c.id} onSelect={()=>onSelect(c.id)} onPointerDown={e=>{onSelect(c.id);if(disabled||e.button!==0)return;const p=local(e);drag.current={id:c.id,x:c.position.x,y:c.position.y,px:p.x,py:p.y,pointer:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();}}/>)}
  </svg></div>;
}

export function StoryVoices({story,disabled,onChange,onOpen}:{story:Narrative;disabled:boolean;onChange:(patch:Partial<Narrative>)=>void;onOpen:(id:string)=>void}) {
  const voices=story.actors.filter(a=>a.kind==='voice'),[selected,setSelected]=useState(''),voice=voices.find(v=>v.id===selected)||voices[0];
  const patch=(p:Partial<StoryActor>)=>voice&&onChange({actors:story.actors.map(a=>a.id===voice.id?{...a,...p}:a)});
  return <section aria-label="叙事发言者工作区"><div className="nc-heading"><div><span className="gp-kicker">NARRATIVE SPEAKERS</span><h3>叙事发言者 <small>{voices.length}</small></h3><p>为旁白、内心声音、系统播报或其他叙事视角设置独立身份。按故事需要添加。</p></div><button className="primary" disabled={disabled} onClick={()=>{const a:StoryActor={id:crypto.randomUUID(),name:'新发言者',description:'',kind:'voice',voiceType:'旁白'};onChange({actors:[...story.actors,a]});setSelected(a.id);}}><Plus size={16}/>添加叙事发言者</button></div>{!voices.length?<div className="nc-empty"><MessageCircle size={42}/><h4>这个故事尚未使用额外的叙事发言者</h4><p>人物对白和普通旁白已经可以独立组成故事。</p></div>:<div className="nv-layout"><div className="nv-list">{voices.map(v=><button key={v.id} aria-label={'发言者：'+v.name} className={v.id===voice?.id?'selected':''} onClick={()=>setSelected(v.id)}><MessageCircle size={18}/><span><b>{v.name}</b><small>{v.voiceType||'自定义'}</small></span></button>)}</div>{voice&&<div className="ns-card"><fieldset disabled={disabled}><Text label="发言者名称" value={voice.name} onChange={name=>patch({name})}/><Text label="发言者类型" value={voice.voiceType||''} onChange={voiceType=>patch({voiceType})}/><Text label="叙事职责与表达方式" rows={6} value={voice.description} onChange={description=>patch({description})}/><p className="gp-muted">在剧本中选择此发言者即可使用。需要自动插话时，在选项中配置触发条件。</p><button className="gp-secondary" disabled={story.nodes.some(n=>n.speakerId===voice.id)} onClick={()=>onChange({actors:story.actors.filter(a=>a.id!==voice.id)})}>删除叙事发言者</button></fieldset><h4>发言片段</h4>{story.nodes.filter(n=>n.speakerId===voice.id).map(n=><button key={n.id} className="nc-reference" onClick={()=>onOpen(n.id)}>{n.title}</button>)}</div>}</div>}</section>;
}
