import { useEffect, useRef, useState } from 'react';
import { BookOpen, GitBranch, Plus, Play, Archive, Copy } from 'lucide-react';
import { always, conditionOperators, copyNarrative, createNarrative, effectsText, narrativeIssues, nodeKindNames, predicateText, removeNarrativeNode, type Narrative, type NarrativeNode, type StoryChoice, type StoryEffect, type StoryPredicate } from './story-orchestration';
import { chooseStoryOption, rewindStory, startStory, visibleStoryChoices, type StoryPlaythrough } from './story-playthrough';
import { canImportStoryConfig, importDiscoStory } from './story-import-config';
import type { StoryOrchestrationController } from './useStoryOrchestration';
import type { ProjectData } from './data-model';
import './story-orchestration.css';

type Task = { id: string; title: string; archived?: boolean };
const emptyName = (s: string) => s.trim() || '未命名';
function Text({ label, value, onChange, rows }: { label: string; value: string; onChange: (v: string) => void; rows?: number }) {
  return <label className="gp-field">{label}{rows ? <textarea aria-label={label} rows={rows} value={value} onChange={e=>onChange(e.target.value)} /> : <input aria-label={label} value={value} onChange={e=>onChange(e.target.value)} />}</label>;
}
function NumberField({ label, value, onChange, min }: { label: string; value: number; onChange: (v: number) => void; min?: number }) {
  return <label className="gp-field">{label}<input aria-label={label} type="number" min={min} value={value} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(n);}} /></label>;
}
function Select({ label, value, options, onChange, blank = '请选择' }: { label: string; value: string; options: {id:string;name:string}[]; onChange:(v:string)=>void; blank?:string }) {
  return <label className="gp-field">{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">{blank}</option>{value && !options.some(o=>o.id===value) && <option value={value}>已失效：{value}</option>}{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;
}
function Conditions({ value, story, onChange, label }: { value:StoryPredicate; story:Narrative; onChange:(v:StoryPredicate)=>void; label:string }) {
  const variables=story.variables.map(v=>({id:v.id,name:v.name}));
  const change=(group:number,index:number,patch:object)=>onChange({groups:value.groups.map((g,gi)=>gi!==group?g:g.map((c,ci)=>ci===index?{...c,...patch}:c))});
  return <div className="ns-rules"><b>{label}</b><p className="gp-muted">满足任意一组即可；每组内需要全部满足。未添加组表示无附加条件。</p>{value.groups.map((g,gi)=><div className="ns-rule-group" key={gi}><div className="gp-card-heading"><strong>条件组 {gi+1}</strong><button className="gp-secondary" onClick={()=>onChange({groups:value.groups.filter((_,i)=>i!==gi)})}>删除{label}组 {gi+1}</button></div>{g.map((c,ci)=><div className="ns-rule-row" key={ci}>
    <Select label={`${label}变量 ${gi+1}-${ci+1}`} value={c.variableId} options={variables} onChange={variableId=>change(gi,ci,{variableId})}/><Select label={`${label}比较 ${gi+1}-${ci+1}`} value={c.op} options={conditionOperators.map((id,i)=>({id,name:['等于','不等于','大于','至少','小于','至多'][i]}))} onChange={op=>{if(op)change(gi,ci,{op});}}/><NumberField label={`${label}数值 ${gi+1}-${ci+1}`} value={c.value} onChange={value=>change(gi,ci,{value})}/><button className="gp-secondary" aria-label={`移除${label}条件 ${gi+1}-${ci+1}`} onClick={()=>onChange({groups:value.groups.map((x,i)=>i===gi?x.filter((_,j)=>j!==ci):x)})}>移除</button>
  </div>)}<button className="gp-secondary" onClick={()=>onChange({groups:value.groups.map((x,i)=>i===gi?[...x,{variableId:story.variables[0]?.id||'',op:'eq',value:1}]:x)})}>添加{label}条件 {gi+1}</button></div>)}<button className="gp-secondary" onClick={()=>onChange({groups:[...value.groups,[{variableId:story.variables[0]?.id||'',op:'eq',value:1}]]})}>添加{label}条件组</button></div>;
}
function Effects({ value, story, onChange, label }: { value:StoryEffect[]; story:Narrative; onChange:(v:StoryEffect[])=>void; label:string }) {
  const change=(i:number,patch:object)=>onChange(value.map((e,j)=>i===j?{...e,...patch}:e));
  return <div className="ns-rules"><b>{label}</b>{value.map((e,i)=><div className="ns-rule-row" key={i}><Select label={`${label}变量 ${i+1}`} value={e.variableId} options={story.variables.map(v=>({id:v.id,name:v.name}))} onChange={variableId=>change(i,{variableId})}/><Select label={`${label}操作 ${i+1}`} value={e.op} options={[{id:'set',name:'设为'},{id:'add',name:'增减'}]} onChange={op=>{if(op)change(i,{op});}}/><NumberField label={`${label}数值 ${i+1}`} value={e.value} onChange={value=>change(i,{value})}/><button className="gp-secondary" aria-label={`删除${label} ${i+1}`} onClick={()=>onChange(value.filter((_,j)=>i!==j))}>移除</button></div>)}<button className="gp-secondary" onClick={()=>onChange([...value,{variableId:story.variables[0]?.id||'',op:'set',value:1}])}>添加{label}</button></div>;
}
export function StoryModuleSettings({ controller, onOpen }: { controller:StoryOrchestrationController; onOpen:()=>void }) {
  const {store,update,blocked,pending}=controller;
  return <section className="ns-settings"><span className="gp-kicker">PROJECT MODULES</span><h2>可选模块</h2><p>为当前项目添加需要的创作工具。</p><div className="ns-module-card"><BookOpen size={30}/><div><h3>故事编排</h3><p>编写分支对白，设置条件、检定与选择后果，在独立试玩中阅读完整故事链。</p><small>{store.stories.length} 个已保存故事 · 关闭模块保留全部内容 · 本地项目</small></div><div className="gp-actions">{store.enabled ? <><button className="primary" onClick={onOpen}>打开故事编排</button><button className="gp-secondary" disabled={blocked||pending} onClick={()=>update(s=>({...s,enabled:false}))}>关闭故事编排</button></> : <button className="primary" disabled={blocked||pending} onClick={()=>{if(update(s=>({...s,enabled:true})))onOpen();}}>添加故事编排</button>}</div></div><p className="gp-muted">此开关只影响当前项目；项目导出时会保留启用状态和故事内容。</p><StoryRecovery controller={controller}/></section>;
}
function StoryRecovery({controller}:{controller:StoryOrchestrationController}) {
  if(!controller.error)return null;
  if(!controller.pending&&!controller.blocked)return <p className="ns-warning" role="alert">{controller.error}</p>;
  return <div className="ns-warning"><p>{controller.error}</p><div className="gp-actions"><button className="gp-secondary" onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(controller.store,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='story-orchestration-draft.json';a.click();URL.revokeObjectURL(u);}}>导出故事草稿</button>{controller.pending&&<button className="gp-secondary" onClick={controller.retry}>重试保存故事编排</button>}<button className="gp-secondary" onClick={()=>{if(!controller.pending||window.confirm('重新读取会放弃当前未保存的故事草稿。请先导出备份。继续？'))controller.reload();}}>重新读取故事存档</button></div></div>;
}

export function StoryOrchestration({controller,data,tasks,selectedId,onSelect,onOpenTask}:{controller:StoryOrchestrationController;data:ProjectData;tasks:Task[];selectedId:string;onSelect:(id:string)=>void;onOpenTask:(id:string)=>void}) {
  const {store,update,blocked}=controller;
  const [query,setQuery]=useState(''),[range,setRange]=useState('active'),[sceneId,setScene]=useState(''),[nodeId,setNode]=useState(''),[view,setView]=useState('script'),[name,setName]=useState(''),[error,setError]=useState('');
  const dialog=useRef<HTMLDialogElement>(null);
  const story=store.stories.find(s=>s.id===selectedId), scene=story?.scenes.find(s=>s.id===sceneId)??story?.scenes[0], node=story?.nodes.find(n=>n.id===nodeId && n.sceneId===scene?.id)??story?.nodes.find(n=>n.sceneId===scene?.id);
  const disabled=blocked||!!story?.archived;
  const select=(id:string)=>{onSelect(id);setScene('');setNode('');setError('');setView('script');};
  const change=(fn:(s:Narrative)=>Narrative)=>{if(!story||disabled)return;try{const next=fn(structuredClone(story));update(s=>({...s,stories:s.stories.map(v=>v.id===story.id?next:v)}));setError('');}catch(e){setError(String(e));}};
  const patch=(p:Partial<Narrative>)=>change(s=>({...s,...p}));
  const patchNode=(p:Partial<NarrativeNode>)=>change(s=>({...s,nodes:s.nodes.map(n=>n.id===node?.id?{...n,...p}:n)}));
  const openNode=(id:string)=>{const n=story?.nodes.find(n=>n.id===id);if(n){setNode(id);setScene(n.sceneId);setView('script');}};
  const add=()=>{const next=createNarrative(name);update(s=>({...s,stories:[...s.stories,next]}));setRange('active');setQuery('');select(next.id);dialog.current?.close();};
  const importConfig=()=>{try{const next=importDiscoStory(data,tasks.map(t=>t.id));update(s=>({...s,stories:[...s.stories,next]}));setRange('active');setQuery('');select(next.id);}catch(e){setError(String(e));}};
  const issues=story?narrativeIssues(story,tasks):[];
  return <div className="gp-workspace ns-workspace" role="region" aria-label="故事编排工作区">
    <aside className="gp-library"><div className="gp-library-heading"><div><span className="gp-kicker">NARRATIVE STUDIO</span><h2>故事库 <small>{store.stories.length}</small></h2></div><BookOpen size={22}/></div><p className="gp-muted">从一段对白，编排一条有选择、有后果的故事链。</p><button className="primary" disabled={blocked} onClick={()=>{setName('');dialog.current?.showModal();}}><Plus size={15}/>新建故事</button><label className="gp-search"><input aria-label="搜索编排故事" placeholder="搜索故事…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select label="故事目录范围" value={range} blank="全部" options={[{id:'active',name:'使用中'},{id:'archived',name:'已归档'}]} onChange={setRange}/><div className="gp-list">{store.stories.filter(s=>(!range||s.archived===(range==='archived'))&&(s.title+s.summary).includes(query)).map(s=><button className={'gp-list-card'+(s.id===story?.id?' selected':'')} key={s.id} aria-label={'选择编排故事：'+s.title} onClick={()=>select(s.id)}><strong>{emptyName(s.title)}</strong><p>{s.summary}</p><small>{s.scenes.length} 场景 · {s.nodes.length} 片段 · {s.choices.length} 选项{s.archived?' · 已归档':''}</small></button>)}</div>
      {canImportStoryConfig(data)&&<details className="ns-import"><summary>从现有对白配置导入</summary><p className="gp-muted">把港区疑案配置转为独立故事副本，原配置保留。后续编辑以故事编排中的内容为准。</p><button className="gp-secondary" disabled={blocked} onClick={importConfig}>导入港区疑案对白</button></details>}
    </aside>
    <section className="gp-detail"><StoryRecovery controller={controller}/>{error&&<p className="ns-warning" role="alert">{error}</p>}{!story?<div className="ns-empty"><BookOpen size={44}/><h2>让文字成为可以探索的故事</h2><p>创建故事、写下正文与选项，或从当前项目已有的对白配置导入。</p></div>:<>
      <div className="gp-editor-heading"><div><span className="gp-kicker">{story.archived?'ARCHIVED':'STORY DESIGN'}</span><h2>{emptyName(story.title)}</h2><p className="gp-muted">{story.nodes.length} 个片段 · {story.choices.length} 个选项 · {story.checks.length} 个检定</p></div><div className="gp-actions"><button className="gp-secondary" disabled={blocked} onClick={()=>{const n=copyNarrative(story);update(s=>({...s,stories:[...s.stories,n]}));select(n.id);setRange('active');}}><Copy size={14}/>复制故事</button><button className="gp-secondary" disabled={blocked} onClick={()=>{update(s=>({...s,stories:s.stories.map(x=>x.id===story.id?{...x,archived:!x.archived}:x)}));setRange(story.archived?'active':'archived');}}><Archive size={14}/>{story.archived?'恢复故事':'归档故事'}</button></div></div>
      <div className="ns-tabs">{[['script','剧本编辑'],['graph','分支结构'],['state','角色与状态'],['checks','检定与规则'],['play','故事试玩']].map(([id,title])=><button key={id} aria-pressed={view===id} className={view===id?'active':''} onClick={()=>setView(id)}>{title}</button>)}</div>
      {issues.length>0&&<details className="ns-warning"><summary>故事检查 · {issues.length} 项</summary><ul>{issues.map((i,n)=><li key={n}>{i.nodeId?<button className="ns-link" onClick={()=>openNode(i.nodeId!)}>{i.message}</button>:i.message}</li>)}</ul></details>}
      {view!=='play'&&<details className="ns-card"><summary>故事设置与关联任务</summary><fieldset disabled={disabled}><Text label="编排故事名称" value={story.title} onChange={title=>patch({title})}/><Text label="故事概要" rows={2} value={story.summary} onChange={summary=>patch({summary})}/><Select label="故事入口" value={story.entryId} options={story.nodes.map(n=>({id:n.id,name:n.title}))} onChange={entryId=>patch({entryId})}/><TaskLinks ids={story.taskIds} tasks={tasks} onChange={taskIds=>patch({taskIds})} onOpen={onOpenTask}/>{story.source&&<p className="gp-muted">来源：{story.source}</p>}</fieldset></details>}
      {view==='script'&&<><div className="ns-card"><div className="ns-row"><Select label="当前故事场景" value={scene?.id||''} options={story.scenes.map(s=>({id:s.id,name:s.chapter+' / '+s.title}))} onChange={id=>{setScene(id);setNode('');}}/><button className="gp-secondary" disabled={disabled} onClick={()=>{const id=crypto.randomUUID();patch({scenes:[...story.scenes,{id,title:'新场景',chapter:scene?.chapter||'第一章',description:''}]});setScene(id);setNode('');}}>添加场景</button></div>{scene&&<fieldset disabled={disabled}><div className="ns-grid"><Text label="章节名称" value={scene.chapter} onChange={chapter=>patch({scenes:story.scenes.map(s=>s.id===scene.id?{...s,chapter}:s)})}/><Text label="场景名称" value={scene.title} onChange={title=>patch({scenes:story.scenes.map(s=>s.id===scene.id?{...s,title}:s)})}/></div><Text label="场景说明" value={scene.description} rows={2} onChange={description=>patch({scenes:story.scenes.map(s=>s.id===scene.id?{...s,description}:s)})}/></fieldset>}
        <div className="ns-node-strip">{story.nodes.filter(n=>n.sceneId===scene?.id).map(n=><button className={node?.id===n.id?'selected':''} key={n.id} aria-label={'选择故事片段：'+n.title} onClick={()=>setNode(n.id)}><small>{nodeKindNames[n.kind]}</small><span>{emptyName(n.title)}</span></button>)}</div><button className="gp-secondary" disabled={disabled||!scene} onClick={()=>{if(!scene)return;const n:NarrativeNode={id:crypto.randomUUID(),sceneId:scene.id,title:'新片段',kind:'dialogue',speakerId:'',text:'',outcome:'',taskStatus:'unchanged',taskIds:[]};patch({nodes:[...story.nodes,n]});setNode(n.id);}}>添加故事片段</button></div>
        {node&&<fieldset className="ns-card" disabled={disabled}><div className="gp-card-heading"><h3>{nodeKindNames[node.kind]}</h3><button className="gp-secondary" onClick={()=>change(s=>removeNarrativeNode(s,node.id))}>删除故事片段</button></div><div className="ns-grid"><Text label="片段标题" value={node.title} onChange={title=>patchNode({title})}/><Select label="片段类型" value={node.kind} options={Object.entries(nodeKindNames).map(([id,name])=>({id,name}))} onChange={kind=>{if(kind)patchNode({kind:kind as NarrativeNode['kind']});}}/><Select label="说话人" value={node.speakerId} blank="旁白 / 无说话人" options={story.actors.map(a=>({id:a.id,name:a.name}))} onChange={speakerId=>patchNode({speakerId})}/></div><Text label="故事正文" value={node.text} rows={7} onChange={text=>patchNode({text})}/><Select label="移动到场景" value={node.sceneId} options={story.scenes.map(s=>({id:s.id,name:s.chapter+' / '+s.title}))} onChange={id=>{if(id){patchNode({sceneId:id});setScene(id);}}}/>
          <details className="ns-rules"><summary>此片段的结果与任务关联</summary><Text label="叙事结果" value={node.outcome} onChange={outcome=>patchNode({outcome})}/><Select label="任务进度结果" value={node.taskStatus} options={[{id:'unchanged',name:'不改变任务'},{id:'completed',name:'任务完成'},{id:'suspended',name:'任务暂缓'},{id:'failed',name:'任务失败'}]} onChange={status=>{if(status)patchNode({taskStatus:status as NarrativeNode['taskStatus']});}}/><TaskLinks ids={node.taskIds} tasks={tasks} onChange={taskIds=>patchNode({taskIds})} onOpen={onOpenTask}/><p className="gp-muted">叙事结果与任务进度分开记录；试玩只更新模拟任务状态。</p></details>
          <h3>玩家选项与自动插话</h3>{story.choices.filter(c=>c.fromId===node.id).map((c,index)=><ChoiceEditor key={c.id} choice={c} index={index} story={story} onChange={p=>patch({choices:story.choices.map(x=>x.id===c.id?{...x,...p}:x)})} onRemove={()=>patch({choices:story.choices.filter(x=>x.id!==c.id)})} onOpen={openNode}/>)}<button className="gp-secondary" disabled={node.kind==='ending'||node.kind==='return'} onClick={()=>patch({choices:[...story.choices,{id:crypto.randomUUID(),fromId:node.id,toId:'',label:'新的选择',condition:always(),effects:[],once:false,passive:false,cost:0,checkId:''}]})}>添加故事选项</button>
        </fieldset>}</>}
      {view==='graph'&&<StoryStructure story={story} onOpen={openNode}/>}
      {view==='state'&&<StoryStateEditor story={story} disabled={disabled} onChange={patch}/>}
      {view==='checks'&&<StoryChecks story={story} disabled={disabled} onChange={patch}/>}
      {view==='play'&&<StoryPlayer key={story.id} story={story} tasks={tasks}/>}
    </>}</section>
    <dialog className="gp-dialog" ref={dialog} aria-label="新建编排故事"><form onSubmit={e=>{e.preventDefault();if(name.trim()&&!blocked)add();}}><h2>新建故事</h2><Text label="新故事名称" value={name} onChange={setName}/><div className="gp-actions"><button className="gp-secondary" type="button" onClick={()=>dialog.current?.close()}>取消</button><button className="primary" disabled={!name.trim()||blocked}>创建故事</button></div></form></dialog>
  </div>;
}
function TaskLinks({ids,tasks,onChange,onOpen}:{ids:string[];tasks:Task[];onChange:(ids:string[])=>void;onOpen:(id:string)=>void}) {
  return <div className="ns-task-links">{ids.map(id=><div className="ns-row" key={id}><button className="ns-link" onClick={()=>onOpen(id)} disabled={!tasks.some(t=>t.id===id)}>{tasks.find(t=>t.id===id)?.title||'任务已失效：'+id}</button><button className="gp-secondary" aria-label={'解除故事任务：'+id} onClick={()=>onChange(ids.filter(x=>x!==id))}>解除</button></div>)}<Select label="关联任务" value="" options={tasks.filter(t=>!t.archived&&!ids.includes(t.id)).map(t=>({id:t.id,name:t.title}))} onChange={id=>{if(id)onChange([...ids,id]);}}/></div>;
}
function ChoiceEditor({choice:c,index,story,onChange,onRemove,onOpen}:{choice:StoryChoice;index:number;story:Narrative;onChange:(p:Partial<StoryChoice>)=>void;onRemove:()=>void;onOpen:(id:string)=>void}) {
  const prefix=`选项 ${index+1}`;
  return <details className="ns-choice-editor"><summary>{index+1}. {c.label||'未命名选项'} <small>{c.passive?'自动插话':c.checkId?'检定分支':story.nodes.find(n=>n.id===c.toId)?.title||'后继未设置'}</small></summary><Text label={prefix+'文本'} value={c.label} rows={2} onChange={label=>onChange({label})}/><div className="ns-grid"><Select label={prefix+'后继'} value={c.toId} options={story.nodes.map(n=>({id:n.id,name:story.scenes.find(s=>s.id===n.sceneId)?.title+' / '+n.title}))} onChange={toId=>onChange({toId})}/><Select label={prefix+'检定'} value={c.checkId} blank="不使用检定" options={story.checks.map(x=>({id:x.id,name:x.name}))} onChange={checkId=>onChange({checkId})}/></div><p className="gp-muted">选择检定后由检定的成功／失败后继分流。</p><div className="ns-row"><label><input type="checkbox" checked={c.once} onChange={e=>onChange({once:e.target.checked})}/> 后果只提交一次，已读可回看</label><label><input type="checkbox" checked={c.passive} onChange={e=>onChange({passive:e.target.checked})}/> 条件满足时自动插话</label></div><NumberField label={prefix+'时间成本'} value={c.cost} min={0} onChange={cost=>{if(cost>=0)onChange({cost});}}/><Conditions label={prefix+'开放'} value={c.condition} story={story} onChange={condition=>onChange({condition})}/><Effects label={prefix+'后果'} value={c.effects} story={story} onChange={effects=>onChange({effects})}/><div className="gp-actions"><button className="gp-secondary" onClick={()=>onOpen(c.toId)}>打开后继片段</button><button className="gp-secondary" onClick={onRemove}>删除{prefix}</button></div></details>;
}

function StoryStateEditor({story,disabled,onChange}:{story:Narrative;disabled:boolean;onChange:(p:Partial<Narrative>)=>void}) {
  const [error,setError]=useState('');
  return <fieldset disabled={disabled} className="ns-fields"><div className="ns-card"><h3>角色与声音</h3>{story.actors.map((a,i)=><div className="ns-entry" key={a.id}><Text label={'角色名称 '+(i+1)} value={a.name} onChange={name=>onChange({actors:story.actors.map(x=>x.id===a.id?{...x,name}:x)})}/><Text label={'角色说明 '+(i+1)} value={a.description} rows={2} onChange={description=>onChange({actors:story.actors.map(x=>x.id===a.id?{...x,description}:x)})}/><button className="gp-secondary" disabled={story.nodes.some(n=>n.speakerId===a.id)} onClick={()=>onChange({actors:story.actors.filter(x=>x.id!==a.id)})}>删除角色 {i+1}</button></div>)}<button className="gp-secondary" onClick={()=>onChange({actors:[...story.actors,{id:crypto.randomUUID(),name:'新角色',description:''}]})}>添加故事角色</button></div>
    <div className="ns-card"><h3>故事状态</h3><p className="gp-muted">为证据、假说、关系、资源和技能分别定义状态；条件与后果引用这些状态。</p>{error&&<p role="alert" className="ns-warning">{error}</p>}{story.variables.map((v,i)=><details className="ns-entry" key={v.id}><summary>{v.name} · {v.category} · 初值 {v.initial}</summary><Text label={'状态名称 '+(i+1)} value={v.name} onChange={name=>onChange({variables:story.variables.map(x=>x.id===v.id?{...x,name}:x)})}/><Text label={'状态分类 '+(i+1)} value={v.category} onChange={category=>onChange({variables:story.variables.map(x=>x.id===v.id?{...x,category}:x)})}/><NumberField label={'状态初值 '+(i+1)} value={v.initial} onChange={initial=>{if(v.minimum!==null&&initial<v.minimum||v.maximum!==null&&initial>v.maximum){setError('初值超出状态范围');return;}setError('');onChange({variables:story.variables.map(x=>x.id===v.id?{...x,initial}:x)});}}/>
      <div className="ns-grid">{(['minimum','maximum'] as const).map(k=><label className="gp-field" key={k}>{k==='minimum'?'最小值':'最大值'}（留空不限）<input type="number" aria-label={'状态'+k+' '+(i+1)} value={v[k]??''} onChange={e=>{const n=e.target.value===''?null:Number(e.target.value);if(n!==null&&(!Number.isFinite(n)||(k==='minimum'?n>v.initial:n<v.initial))){setError('范围需要包含当前初值');return;}setError('');onChange({variables:story.variables.map(x=>x.id===v.id?{...x,[k]:n}:x)});}}/></label>)}</div><p className="gp-muted">标识：{v.id}。删除后保留引用并在故事检查中提示修复。</p><button className="gp-secondary" onClick={()=>{if(window.confirm('删除状态后，相关条件和后果需要修复。继续？'))onChange({variables:story.variables.filter(x=>x.id!==v.id)});}}>删除状态 {i+1}</button></details>)}<button className="gp-secondary" onClick={()=>onChange({variables:[...story.variables,{id:crypto.randomUUID(),name:'新状态',category:'事实',initial:0,minimum:0,maximum:1}]})}>添加故事状态</button></div>
  </fieldset>;
}
function StoryChecks({story,disabled,onChange}:{story:Narrative;disabled:boolean;onChange:(p:Partial<Narrative>)=>void}) {
  const nodes=story.nodes.map(n=>({id:n.id,name:n.title})),variables=story.variables.map(v=>({id:v.id,name:v.name}));
  return <fieldset className="ns-fields" disabled={disabled}><div className="ns-card"><h3>检定</h3><p className="gp-muted">默认按2d6＋技能与条件修正对比难度；双1失败、双6成功。试玩也可指定成败检查替代路线。</p>{story.checks.map((c,i)=>{const patch=(p:object)=>onChange({checks:story.checks.map(x=>x.id===c.id?{...x,...p}:x)});return <details className="ns-entry" key={c.id}><summary>{c.name} · 难度 {c.difficulty}</summary><Text label={'检定名称 '+(i+1)} value={c.name} onChange={name=>patch({name})}/><div className="ns-grid"><Select label={'检定技能 '+(i+1)} value={c.variableId} options={variables} onChange={variableId=>patch({variableId})}/><NumberField label={'检定难度 '+(i+1)} value={c.difficulty} onChange={difficulty=>patch({difficulty})}/><Select label={'检定重试 '+(i+1)} value={c.retry} options={[{id:'always',name:'失败后可重试'},{id:'once',name:'仅一次检定'},{id:'on-change',name:'新来源解锁重试'}]} onChange={retry=>{if(retry)patch({retry});}}/></div><Select label={'检定成功后继 '+(i+1)} value={c.successId} options={nodes} onChange={successId=>patch({successId})}/><Select label={'检定失败后继 '+(i+1)} value={c.failureId} options={nodes} onChange={failureId=>patch({failureId})}/>
        <p className="gp-muted">以下任一来源数值高于上次尝试时的值，解锁一次重试：</p><div className="ns-checkboxes">{story.variables.map(v=><label key={v.id}><input type="checkbox" checked={c.retryVariableIds.includes(v.id)} onChange={e=>patch({retryVariableIds:e.target.checked?[...c.retryVariableIds,v.id]:c.retryVariableIds.filter(id=>id!==v.id)})}/>{v.name}</label>)}</div>
        <Effects label={'检定'+(i+1)+'成功后果'} value={c.successEffects} story={story} onChange={successEffects=>patch({successEffects})}/><Effects label={'检定'+(i+1)+'失败后果'} value={c.failureEffects} story={story} onChange={failureEffects=>patch({failureEffects})}/>{c.modifiers.map((m,mi)=><div className="ns-rule-group" key={mi}><NumberField label={`检定${i+1}修正 ${mi+1}`} value={m.value} onChange={value=>patch({modifiers:c.modifiers.map((x,j)=>j===mi?{...x,value}:x)})}/><Conditions label={`检定${i+1}修正${mi+1}`} value={m.condition} story={story} onChange={condition=>patch({modifiers:c.modifiers.map((x,j)=>j===mi?{...x,condition}:x)})}/><button className="gp-secondary" onClick={()=>patch({modifiers:c.modifiers.filter((_,j)=>j!==mi)})}>删除修正 {mi+1}</button></div>)}<button className="gp-secondary" onClick={()=>patch({modifiers:[...c.modifiers,{condition:always(),value:0}]})}>添加检定修正 {i+1}</button><Text label={'检定说明 '+(i+1)} rows={3} value={c.notes} onChange={notes=>patch({notes})}/><button className="gp-secondary" disabled={story.choices.some(x=>x.checkId===c.id)} onClick={()=>onChange({checks:story.checks.filter(x=>x.id!==c.id)})}>删除检定 {i+1}</button></details>;})}<button className="gp-secondary" onClick={()=>onChange({checks:[...story.checks,{id:crypto.randomUUID(),name:'新检定',variableId:story.variables[0]?.id||'',difficulty:10,retry:'once',retryVariableIds:[],successId:'',failureId:'',successEffects:[],failureEffects:[],modifiers:[],notes:''}]})}>添加故事检定</button></div>
    <div className="ns-card"><h3>时间与中断</h3><Select label="故事时钟" value={story.clockId} blank="不使用时钟" options={variables} onChange={clockId=>onChange({clockId})}/><NumberField label="时间上限（0为不限）" value={story.timeLimit} min={0} onChange={timeLimit=>{if(timeLimit>=0)onChange({timeLimit});}}/><p className="gp-muted">中断按列表顺序检查，命中第一条后进入指定片段。返回片段可继续中断前内容；故事结果不再触发中断。</p>{story.interrupts.map((rule,i)=>{const patch=(p:object)=>onChange({interrupts:story.interrupts.map(x=>x.id===rule.id?{...x,...p}:x)});return <details className="ns-entry" key={rule.id}><summary>{i+1}. {rule.name}</summary><Text label={'中断名称 '+(i+1)} value={rule.name} onChange={name=>patch({name})}/><Conditions label={'中断'+(i+1)} value={rule.condition} story={story} onChange={condition=>patch({condition})}/><Select label={'中断后继 '+(i+1)} value={rule.nodeId} options={nodes} onChange={nodeId=>patch({nodeId})}/><div className="gp-actions"><button className="gp-secondary" disabled={i===0} onClick={()=>{const next=[...story.interrupts];[next[i-1],next[i]]=[next[i],next[i-1]];onChange({interrupts:next});}}>提高优先级 {i+1}</button><button className="gp-secondary" onClick={()=>onChange({interrupts:story.interrupts.filter(x=>x.id!==rule.id)})}>删除中断 {i+1}</button></div></details>;})}<button className="gp-secondary" onClick={()=>onChange({interrupts:[...story.interrupts,{id:crypto.randomUUID(),name:'新中断',condition:always(),nodeId:''}]})}>添加故事中断</button></div>
  </fieldset>;
}

function StoryStructure({story,onOpen}:{story:Narrative;onOpen:(id:string)=>void}) {
  const [sceneId,setScene]=useState(story.scenes[0]?.id||'');
  const scene=story.scenes.find(s=>s.id===sceneId)??story.scenes[0],local=story.nodes.filter(n=>n.sceneId===scene?.id);
  const edges=story.choices.filter(c=>local.some(n=>n.id===c.fromId)).flatMap(c=>{const check=story.checks.find(k=>k.id===c.checkId);return check?[{id:c.id+'s',from:c.fromId,to:check.successId,label:c.label+' · 成功'},{id:c.id+'f',from:c.fromId,to:check.failureId,label:c.label+' · 失败'}]:[{id:c.id,from:c.fromId,to:c.toId,label:c.label}];});
  const external=story.nodes.filter(n=>!local.some(l=>l.id===n.id)&&edges.some(e=>e.to===n.id)), all=[...local,...external], positions=new Map(all.map((n,i)=>[n.id,{x:i<local.length?30:460,y:30+(i<local.length?i:i-local.length)*100}]));
  return <div className="ns-card"><h3><GitBranch size={17}/>场景与分支结构</h3><Select label="查看场景结构" value={scene?.id||''} options={story.scenes.map(s=>({id:s.id,name:s.chapter+' / '+s.title}))} onChange={setScene}/><p className="gp-muted">左侧为当前场景，右侧为跨场景后继。点击片段编辑正文；下方列出完整选项和条件。</p><div className="ns-graph"><svg width="710" height={Math.max(250,Math.max(local.length,external.length)*100+40)} role="group" aria-label="故事分支图">{edges.map((e,i)=>{const a=positions.get(e.from),b=positions.get(e.to);if(!a||!b)return null;const rail=285+(i%12)*12;return <path key={e.id} d={b.x>a.x?`M${a.x+215},${a.y+30} C350,${a.y+30} 380,${b.y+30} ${b.x},${b.y+30}`:`M${a.x+215},${a.y+20} H${rail} V${b.y+45} H${b.x+215}`} fill="none" stroke="#726188" strokeWidth="1.4"><title>{e.label}</title></path>;})}{all.map(n=>{const p=positions.get(n.id)!;return <g key={n.id} transform={`translate(${p.x} ${p.y})`} tabIndex={0} role="button" aria-label={'结构片段：'+n.title} onClick={()=>onOpen(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onOpen(n.id);}}}><rect width="215" height="65" rx="8" fill={n.kind==='ending'?'#304535':'#2b233b'} stroke="#a18ac7"/><text x="12" y="22" fill="#b7a4ce" fontSize="10">{n.id===story.entryId?'入口 · ':''}{nodeKindNames[n.kind]}</text><text x="12" y="46" fill="#eee4fa" fontSize="12">{n.title.slice(0,15)}{n.title.length>15?'…':''}</text><title>{n.text}</title></g>;})}</svg></div><div className="ns-edge-list">{story.choices.filter(c=>local.some(n=>n.id===c.fromId)).map(c=><p key={c.id}><button className="ns-link" onClick={()=>onOpen(c.fromId)}>{story.nodes.find(n=>n.id===c.fromId)?.title}</button> → <b>{c.label}</b> · {predicateText(c.condition,story)} · {c.checkId?'检定：'+story.checks.find(k=>k.id===c.checkId)?.name:story.nodes.find(n=>n.id===c.toId)?.title}</p>)}</div></div>;
}
function StoryPlayer({story,tasks}:{story:Narrative;tasks:Task[]}) {
  const [preview,setPreview]=useState<StoryPlaythrough|null>(null),[initial,setInitial]=useState<Record<string,number>>({}),[error,setError]=useState(''),[mode,setMode]=useState('dice'),[dice,setDice]=useState<[number,number]>([3,3]),[showLocked,setShowLocked]=useState(true);
  const transcript=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(transcript.current)transcript.current.scrollTop=transcript.current.scrollHeight;},[preview]);
  const fingerprint=JSON.stringify(story);
  useEffect(()=>{setPreview(null);setInitial({});setError('');},[fingerprint]);
  const act=(fn:()=>StoryPlaythrough)=>{try{setPreview(fn());setError('');}catch(e){setError(String(e));}};
  const frame=preview?.current,node=story.nodes.find(n=>n.id===frame?.nodeId),choices=frame?visibleStoryChoices(story,frame):[];
  return <section className="ns-player"><div className="ns-card"><div className="gp-card-heading"><h3><Play size={18}/>独立故事试玩</h3><div className="gp-actions"><button className="gp-secondary" disabled={!preview?.history.length} onClick={()=>preview&&setPreview(rewindStory(preview))}>回退一步</button><button className="gp-secondary" onClick={()=>{setPreview(null);setError('');}}>重置故事试玩</button></div></div><p className="gp-muted">条件会按模拟状态判断，选择后统一提交后果。所有状态、检定与任务进度只存在于本次试玩，不会改写设计或玩家存档。</p>{!preview&&<><details className="ns-initial"><summary>设置试玩初始状态</summary><div className="ns-grid">{story.variables.map(v=><NumberField key={v.id} label={'试玩初值：'+v.name} value={initial[v.id]??v.initial} onChange={value=>setInitial({...initial,[v.id]:value})}/>)}</div></details><button className="primary" onClick={()=>act(()=>startStory(story,initial))}>从故事入口开始</button></>}{error&&<p className="ns-warning" role="alert">{error}</p>}</div>
    {preview&&frame&&node&&<div className="ns-play-layout"><div><div ref={transcript} className="ns-transcript" aria-label="故事阅读记录">{frame.visited.slice(-120).map((id,i)=>{const n=story.nodes.find(n=>n.id===id)!;return <article key={i} className={'ns-passage '+(i===frame.visited.slice(-120).length-1?'current':'')}><small>{story.scenes.find(s=>s.id===n.sceneId)?.title} · {story.actors.find(a=>a.id===n.speakerId)?.name||'旁白'}</small><h3>{n.title}</h3><p>{n.text}</p></article>;})}</div>
      <div className="ns-card ns-live-choices"><h3>{node.kind==='ending'?'故事结果':'接下来…'}</h3>{node.kind==='ending'?<><strong className="ns-outcome">{node.outcome||node.title}</strong><p>任务进度：{{unchanged:'不改变',completed:'完成',suspended:'暂缓',failed:'失败'}[node.taskStatus]}</p></>:<>
        {choices.some(x=>x.choice.checkId)&&<div className="ns-grid"><Select label="试玩检定方式" value={mode} options={[{id:'dice',name:'按输入骰点计算'},{id:'success',name:'指定成功，验证路线'},{id:'failure',name:'指定失败，验证路线'}]} onChange={m=>{if(m)setMode(m);}}/>{mode==='dice'&&<><NumberField label="骰子一" value={dice[0]} onChange={n=>setDice([n,dice[1]])}/><NumberField label="骰子二" value={dice[1]} onChange={n=>setDice([dice[0],n])}/></>}</div>}
        <label className="ns-locked-toggle"><input type="checkbox" checked={showLocked} onChange={e=>setShowLocked(e.target.checked)}/> 显示暂不可用选项</label>{choices.filter(x=>showLocked||!x.reason).map(({choice:c,reason})=><div className="ns-live-choice" key={c.id}><button aria-label={"故事选择："+c.label} disabled={!!reason} onClick={()=>act(()=>chooseStoryOption(story,preview,c.id,mode==='dice'?dice:mode as 'success'|'failure'))}>{c.label}{c.checkId&&<small>检定 · {story.checks.find(k=>k.id===c.checkId)?.name}</small>}</button>{reason?<p className="ns-lock-reason">需要：{reason}</p>:<small>{c.once&&frame.used.includes(c.id)?'已读，可回看':`${c.cost?`消耗时间 ${c.cost} · `:''}${effectsText(c.effects,story)}`}</small>}</div>)}{!choices.length&&<p className="ns-warning">当前片段没有可继续的玩家选项，请检查故事设计。</p>}</>}
      </div></div><aside className="ns-state-panel"><h3>模拟状态</h3>{story.variables.map(v=><div className={frame.state[v.id]!==v.initial?'changed':''} key={v.id}><span>{v.name}<small>{v.category}</small></span><b>{frame.state[v.id]}</b></div>)}<h3>模拟任务进度</h3>{Object.entries(frame.tasks).map(([id,status])=><p key={id}>{tasks.find(t=>t.id===id)?.title||id} · {{completed:'完成',suspended:'暂缓',failed:'失败'}[status]||status}</p>)}<details><summary>选择与变化记录 · {frame.log.length}</summary>{frame.log.map((l,i)=><div className="ns-log" key={i}><b>{l.text}</b>{l.changes.map((c,j)=><p key={j}>{c}</p>)}</div>)}</details></aside></div>}
  </section>;
}
