import {useState} from 'react';
import {ClipboardList,Send,MessageSquare,CheckCircle2,ArrowRight} from 'lucide-react';
import {taskInbox,dispatchTask} from '../shared/task-inbox.mjs';
import {artGrants} from '../shared/art-permissions.mjs';
import {ScheduleRecovery} from './ProjectSchedule';
import {EngineFeedbackPanel} from './EngineFeedbackPanel';
import type {useProjectSchedule} from './useProjectSchedule';
import type {EngineConfig} from './engine';
import type {CollaborationSource} from './engine-sync';
import './task-inbox.css';
type Props={controller:ReturnType<typeof useProjectSchedule>;projectId:string;config:EngineConfig;collaboration:CollaborationSource;blockedReason:string;onApplied:(reloadContent?:boolean)=>boolean;onOpenTask:(id:string)=>void;onOpenAuthoring:()=>void;testMode?:boolean};
export function TaskInbox({controller:c,projectId,config,collaboration,blockedReason,onApplied,onOpenTask,onOpenAuthoring,testMode}:Props){
 const [memberId,setMemberId]=useState(''),[tab,setTab]=useState('tasks'),[query,setQuery]=useState(''),[form,setForm]=useState(''),[fromId,setFromId]=useState(''),[toId,setToId]=useState(''),[taskId,setTaskId]=useState(''),[text,setText]=useState(''),[error,setError]=useState('');
 const members=c.store.personnel?.members||[],box=taskInbox(c.store,memberId),blocked=!!testMode||c.blocked||c.pending;
 const match=(title:string)=>title.toLowerCase().includes(query.toLowerCase());
 const tasks=(tab==='reviews'?box.reviews:tab==='sent'?box.dispatched:box.tasks).filter(t=>match(t.title));
 const submit=()=>{setError('');try{if(!taskId||!fromId)throw new Error('请选择任务和发起成员');const ok=c.update(s=>{if(form==='dispatch')return dispatchTask(s,fromId,toId,taskId,crypto.randomUUID());const member=s.personnel?.members.find(m=>m.id===fromId),task=s.tasks.find(t=>t.id===taskId);if(!member?.active||!task||!text.trim())throw new Error('请填写建议内容');if(!member.permissions.includes('propose')&&!artGrants(member).includes('propose'))throw new Error('成员没有提出建议权限');if(!member.permissions.includes('propose')&&task.kind!=='美术'&&!task.references.some(r=>['asset','requirement'].includes(r.kind)))throw new Error('素材建议应关联素材制作任务');return {...s,tasks:s.tasks.map(t=>t.id!==taskId?t:{...t,proposals:[...(t.proposals||[]),{id:crypto.randomUUID(),memberId:fromId,text:text.trim(),at:new Date().toISOString()}]})};});if(ok){setForm('');setText('');}}catch(e){setError(String(e));}};
 return <section className="task-inbox" aria-label="任务清单"><div className="ai-heading"><div><span className="eyebrow">TASK INBOX</span><h2>每个人的任务与协作建议</h2><p className="gp-muted">任务与项目排期实时共用；在这里查收、派发和跟进。</p></div><div className="ai-toolbar"><button disabled={blocked} onClick={()=>{setForm('proposal');setError('');}}><MessageSquare size={16}/>提出建议</button><button disabled={blocked} className="primary" onClick={()=>{setForm('dispatch');setError('');}}><Send size={16}/>派发任务</button></div></div>
 <ScheduleRecovery controller={c}/><div className="inbox-filters"><label>查看成员<select aria-label="任务清单成员" value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">全部成员</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}{m.active?'':'（停用）'}</option>)}</select></label><input type="search" aria-label="搜索任务清单" placeholder="搜索任务或建议…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <div className="ar-module-tabs" role="tablist" aria-label="任务清单视图">{[['tasks','收到的任务',box.tasks.length],['proposals','协作建议',box.proposals.filter(p=>!p.resolution).length],['reviews','待我验收',box.reviews.length],['sent','我派发的',box.dispatched.length],['feedback','引擎反馈',null]].map(([id,label,count])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(String(id))}>{label}{count!==null&&<small> {count}</small>}</button>)}</div>
 {tab==='feedback'?<><p className="gp-muted">读取当前工程中的签名反馈，核对任务、建议和派发请求后应用。</p><EngineFeedbackPanel projectId={projectId} config={config} collaboration={collaboration} blockedReason={blockedReason} onApplied={onApplied}/><button onClick={onOpenAuthoring}>查看项目文件夹中的内容修改提交 <ArrowRight size={16}/></button></>:tab==='proposals'?<><p className="gp-muted">新增、删除、分类与关联调整先记录建议。标记处理结果不会自动修改素材或排期。</p><div className="inbox-list">{box.proposals.filter(p=>match(p.title+p.text)).map(p=><article className="gp-card" key={p.taskId+':'+p.id}><div className="gp-card-heading"><h3>{p.title}</h3><span>{p.resolution==='accepted'?'已采纳':p.resolution==='dismissed'?'不采纳':'待处理'}</span></div><p className="gp-muted">{members.find(m=>m.id===p.memberId)?.name||'历史成员'} · {new Date(p.at).toLocaleString()}</p><p className="inbox-text">{p.text}</p><div className="ai-toolbar"><button onClick={()=>onOpenTask(p.taskId)}>打开关联任务</button>{!p.resolution&&(['accepted','dismissed'] as const).map(resolution=><button key={resolution} disabled={blocked} onClick={()=>c.update(s=>({...s,tasks:s.tasks.map(t=>t.id!==p.taskId?t:{...t,proposals:t.proposals?.map(x=>x.id!==p.id?x:{...x,resolution,resolvedAt:new Date().toISOString()})})}))}>{resolution==='accepted'?'标记已采纳':'不采纳'}</button>)}</div></article>)}</div>{!box.proposals.length&&<div className="inbox-empty"><MessageSquare/><h3>暂无协作建议</h3><p>将素材增删或组织调整的原因和影响关联到任务，交给负责人处理。</p></div>}</>:<div className="inbox-list">{tasks.map(t=><article className="gp-card" key={t.id}><div className="gp-card-heading"><h3>{t.title}</h3><span>{t.status}</span></div><p className="gp-muted">{t.owner||'未指定负责人'} · {t.kind} · {t.end?'计划完成 '+t.end:'尚未排期'}</p><p className="inbox-text">{t.description||'尚未填写工作说明'}</p>{t.acceptance&&<p>验收要求：{t.acceptance}</p>}{tab==='sent'&&t.dispatchHistory?.map(r=><p className="gp-muted" key={r.id}>{members.find(m=>m.id===r.fromId)?.name||r.fromId} → {members.find(m=>m.id===r.toId)?.name||r.toId} · {new Date(r.at).toLocaleString()}</p>)}<button onClick={()=>onOpenTask(t.id)}>{tab==='reviews'?<CheckCircle2 size={16}/>:<ClipboardList size={16}/>}打开任务与验收</button></article>)}{!tasks.length&&<div className="inbox-empty"><ClipboardList/><h3>这里还没有匹配的任务</h3><p>在项目排期创建工作，在人员分配指定成员，或由主美派发已有素材任务。</p></div>}</div>}
 {form&&<dialog className="gp-dialog" aria-label={form==='dispatch'?'派发美术任务':'提出协作建议'} ref={el=>{if(el&&!el.open)el.showModal();}} onCancel={()=>setForm('')}><h3>{form==='dispatch'?'派发美术任务':'提出协作建议'}</h3><p className="gp-muted">本地工作区管理操作；派发沿用现有任务，不复制进度。引擎侧提交必须使用成员签名。</p><fieldset disabled={blocked}><label className="gp-field">发起成员<select aria-label="发起成员" value={fromId} onChange={e=>setFromId(e.target.value)}><option value="">选择成员</option>{members.filter(m=>m.active&&(form==='dispatch'?artGrants(m).includes('dispatch'):m.permissions.includes('propose')||artGrants(m).includes('propose'))).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="gp-field">关联任务<select aria-label="关联任务" value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">选择任务</option>{c.store.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>{form==='dispatch'?<label className="gp-field">接收成员<select aria-label="接收成员" value={toId} onChange={e=>setToId(e.target.value)}><option value="">选择技术美术或美术开发</option>{members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>:<label className="gp-field">建议内容<textarea aria-label="建议内容" maxLength={30000} rows={5} placeholder="说明建议新增或删除什么，以及对引用、分类、排期的影响。" value={text} onChange={e=>setText(e.target.value)}/></label>}</fieldset><ScheduleRecovery controller={c}/>{error&&<p role="alert">{error}</p>}<div className="ai-toolbar"><button onClick={()=>setForm('')}>取消</button><button className="primary" disabled={blocked} onClick={submit}>确认{form==='dispatch'?'派发':'记录建议'}</button></div></dialog>}
 </section>;
}
